Repository airyhq/airy, pull requests merged in 2020-11, with the labels that each got.

#382 [#381] Classify pull requests as our conventions specify
  .github/pr-labeler.yml
  .github/release-drafter.yml
  docs/docs/guidelines/contributing.md
Labels: fix

#380 [#378] Do not require token as most sources do not require it
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/chat_plugin/ChatPluginSource.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/facebook/FacebookSource.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/google/GoogleSource.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/twilio/TwilioSmsSource.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/twilio/TwilioWhatsappSource.java
  docs/BUILD.bazel
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
  docs/sidebars.js
Labels: fix

#389 [#378] Fix the code also and not only the docs for channel connection token
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ConnectChannelRequestPayload.java
Labels: fix

#390 [#386] Add missing cors configuration
  backend/lib/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  backend/lib/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
  backend/lib/spring/web/src/main/java/co/airy/spring/web/filters/CorsFilterConfig.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
  frontend/chat-plugin/example.html
Labels: fix

#383 Docs/chat plugin
  docs/docs/index.md
Labels: docs

#392 [#388] Chat plugin text render bug fixed
  frontend/chat-plugin/src/components/chat/index.tsx
Labels: fix

#395 [#394] Fix broken link in documentation
  README.md
Labels: bug

#391 [#344] Enable copy&paste of code snippets
  docs/docs/guidelines/contributing.md
  docs/docusaurus.config.js
Labels: docs

#406 [#405] Populate delivery state correctly
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java
  docs/docs/api/http.md
Labels: fix

#404 Generate random strings with helm
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/api.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/postgresql.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/postgres/templates/configmap.yaml
  infrastructure/helm-chart/charts/postgres/values.yaml
  infrastructure/scripts/provision/core.sh
Labels: fix

#410 [#408] Prioritize first apps
  docs/docs/guides/airy-core-in-production.md
  infrastructure/helm-chart/charts/apps/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-demo/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-sender/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-webhook/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-sender/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-webhook/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-sender/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-webhook/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-publisher/templates/deployment.yaml
  infrastructure/scripts/conf.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
Labels: fix
