Repository airyhq/airy, pull requests merged in 2020-12, with the labels that each got.

#409 Add Vbox known issue
  docs/docs/guides/airy-core-in-test-env.md
  infrastructure/scripts/lib/k8s.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/provision/create-topics.sh
  infrastructure/scripts/provision/prerequisites.sh
Labels: docs

#418 [417] Fix chatplugin chart
  infrastructure/helm-chart/charts/apps/charts/frontend-chat-plugin/templates/deployment.yaml
Labels: fix

#407 Filter conversations on metadata
  WORKSPACE
  backend/api/admin/src/main/java/co/airy/core/api/admin/sources/twilio/TwilioWhatsappSource.java
  backend/api/communication/BUILD
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/LuceneQueryResult.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/filter/ChannelIdsFilter.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/filter/ConversationIdsFilter.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/filter/DisplayNameFilter.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/filter/Filter.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/IndexingProcessor.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneDiskStore.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneStore.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/ReadOnlyLuceneStore.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationListRequestPayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationListResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ResponseMetadata.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  backend/lib/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  backend/lib/mapping/src/test/java/co/airy/mapping/TwilioTest.java
  backend/lib/spring/auth/src/main/java/co/airy/spring/auth/Jwt.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/WebSocketConfig.java
  backend/sources/facebook/sender/src/main/java/co/airy/core/sources/facebook/Sender.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  backend/sources/google/sender/src/main/java/co/airy/core/sources/google/Sender.java
  backend/sources/google/sender/src/main/java/co/airy/core/sources/google/services/Api.java
  backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java
  backend/sources/twilio/webhook/src/main/java/co/airy/core/sources/twilio/TwilioWebhook.java
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
  maven_install.json
Labels: feature

#414 [#413] Add /metadata.set endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/SetMetadataRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  docs/docs/api/http.md
  docs/docs/glossary.md
Labels: feature

#429 [#427] Return default contact information
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/avro/communication/metadata-action/src/main/java/co/airy/avro/communication/MetadataKeys.java
Labels: feature

#420 [#290] Channels page
  backend/lib/mapping/src/ts-generator/java/co/airy/ts_generator/Main.java
  frontend/demo/BUILD
  frontend/demo/src/App.tsx
  frontend/demo/src/actions/channel/index.ts
  frontend/demo/src/actions/user/index.ts
  frontend/demo/src/api/airyConfig.ts
  frontend/demo/src/model/Channel.ts
  frontend/demo/src/pages/Channels/index.module.scss
  frontend/demo/src/pages/Channels/index.tsx
  frontend/demo/src/pages/Login/index.tsx
  frontend/demo/src/reducers/data/channels/index.ts
  frontend/demo/src/reducers/data/index.ts
  frontend/types/content.ts
  package.json
  yarn.lock
Labels: feature

#426 [#425] Migrate Code formating to Bazel tools
  BUILD
  CONTRIBUTING.md
  WORKSPACE
  checkstyle.xml
  docs/BUILD.bazel
  maven_install.json
  scripts/lint.sh
  tools/build/java_library.bzl
  tools/build/springboot.bzl
  tools/build/web/typescript.bzl
  tools/code-format/BUILD
  tools/code-format/chdir.js
  tools/code-format/checkstyle.bzl
  tools/code-format/prettier.bzl
Labels: feature

#430 [#413] Add /metadata.remove endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/RemoveMetadataRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  docs/docs/api/http.md
Labels: feature

#439 [#370] Add conversation metadata filter docs
  docs/docs/api/http.md
Labels: feature

#441 [#437] Replace alignment in favor of sender type
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/MessageResponsePayload.java
  docs/docs/api/http.md
  docs/docs/api/websocket.md
  docs/docs/sources/chat-plugin.md
  frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
Labels: feature

#443 [442] Fix glossary TOC
  docs/docs/glossary.md
  docs/docs/guidelines/release-process.md
  docs/docs/guides/airy-core-and-rasa.md
  docs/docs/guides/airy-core-in-production.md
  docs/docs/guides/airy-core-in-test-env.md
  docs/docs/guides/architecture.md
  docs/docs/index.md
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/twilio-source.mdx
  docs/docs/sources/whatsapp-twilio.md
Labels: docs, fix

#454 [#451] Bash test messages generator
  infrastructure/scripts/lib/api.sh
  infrastructure/scripts/smoke-generator.sh
  infrastructure/scripts/smoke-test.sh
Labels: feature

#458 [#453] Update release docs
  docs/docs/guidelines/release-process.md
Labels: docs

#459 [#457] Improve conversations query (indexes, restoration, api)
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/DisplayName.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneDiskStore.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/StoreChangeLogger.java
Labels: feature

#465 Hotfix for CI
  WORKSPACE
Labels: fix

#456 [#452] Split auth dependency
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/UsersController.java
  backend/api/auth/src/test/java/co/airy/core/api/auth/UsersControllerTest.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketConfig.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  lib/java/spring/auth/BUILD
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
  lib/java/spring/jwt/BUILD
  lib/java/spring/jwt/src/main/java/co/airy/spring/jwt/Jwt.java
  lib/java/spring/test/BUILD
  lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelper.java
Labels: feature

#460 [310] Add go api client lib
  lib/go/apiclient/BUILD
  lib/go/apiclient/api-client-test/BUILD
  lib/go/apiclient/api-client-test/users_test.go
  lib/go/apiclient/apiclient.go
  lib/go/apiclient/go.mod
  lib/go/apiclient/go.sum
  lib/go/apiclient/payloads/BUILD
  lib/go/apiclient/payloads/login_request.go
  lib/go/apiclient/payloads/login_response.go
  lib/go/apiclient/payloads/signup_request.go
  lib/go/apiclient/payloads/signup_response.go
  lib/go/apiclient/users.go
Labels: feature

#471 [#470] Specify --no-ff option in merge commands
  docs/docs/guidelines/release-process.md
Labels: docs

#469 [#393] AllowedOrigin in airy.conf
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/api/admin/src/main/resources/application.properties
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  infrastructure/airy.conf.all
  infrastructure/airy.conf.tpl
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/api.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api-communication/templates/deployment.yaml
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AllowedOriginsConfig.java
Labels: feature

#431 [#257] Add tags to core
  frontend/demo/BUILD
  frontend/demo/src/App.tsx
  frontend/demo/src/actions/settings/index.tsx
  frontend/demo/src/actions/tags/index.tsx
  frontend/demo/src/assets/images/empty-state/tags-empty-state.svg
  frontend/demo/src/assets/images/icons/close.svg
  frontend/demo/src/assets/images/icons/edit.svg
  frontend/demo/src/assets/images/icons/plus.svg
  frontend/demo/src/assets/images/icons/price-tag.svg
  frontend/demo/src/assets/images/icons/trash.svg
  frontend/demo/src/components/ColorSelector.module.scss
  frontend/demo/src/components/ColorSelector.tsx
  frontend/demo/src/components/Dialog.module.scss
  frontend/demo/src/components/Dialog.tsx
  frontend/demo/src/components/SearchField.tsx
  frontend/demo/src/components/Sidebar/index.tsx
  frontend/demo/src/components/style.module.scss
  frontend/demo/src/model/Tag.ts
  frontend/demo/src/pages/Tags/EmptyStateTags.tsx
  frontend/demo/src/pages/Tags/FAKESETTINGS.ts
  frontend/demo/src/pages/Tags/SimpleTagForm.module.scss
  frontend/demo/src/pages/Tags/SimpleTagForm.tsx
  frontend/demo/src/pages/Tags/TableRow.module.scss
  frontend/demo/src/pages/Tags/TableRow.tsx
  frontend/demo/src/pages/Tags/Tag.module.scss
  frontend/demo/src/pages/Tags/Tag.tsx
  frontend/demo/src/pages/Tags/index.module.scss
  frontend/demo/src/pages/Tags/index.tsx
  frontend/demo/src/reducers/data/index.ts
  frontend/demo/src/reducers/data/settings/index.ts
  frontend/demo/src/reducers/data/tags/index.ts
  frontend/demo/src/reducers/index.ts
  frontend/demo/src/routes/routes.ts
  frontend/demo/src/selectors/tags.ts
  package.json
  yarn.lock
Labels: feature

#476 [#386] Add quote function
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/api.yaml
Labels: fix

#478 Several improvements
  docs/docs/index.md
Labels: docs

#477 Several initial updates
  docs/docs/api/http.md
Labels: docs

#487 [#484] Remove reset password docs
  docs/docs/api/http.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
Labels: docs

#492 [#490] Reorganize sidebar
  CONTRIBUTING.md
  README.md
  docs/docs/guides/airy-core-in-production.md
  docs/docs/guides/contributing.md
  docs/docs/overview/architecture.md
  docs/docs/overview/design-principles.md
  docs/docs/overview/kafka.md
  docs/docs/overview/release-process.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: docs

#502 Add codeowners configuration
  .github/CODEOWNERS
Labels: chore

#504 [#462] Assign the label chore to dependabot pull requests
  .github/pr-labeler.yml
Labels: chore

#500 Fix sources configmap
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-webhook/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-webhook/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-webhook/templates/deployment.yaml
  infrastructure/scripts/conf.sh
  infrastructure/scripts/status.sh
  infrastructure/scripts/trigger/start.sh
Labels: fix

#505 [#473] Rely on allowed origins setup from the env
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AllowedOriginsConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/IgnoreAuthPattern.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
Labels: feature

#510 [#506] Remove unused labels
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-webhook/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-webhook/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-webhook/templates/service.yaml
Labels: fix

#512 Fix codeowners syntax
  .github/CODEOWNERS
Labels: fix

#511 [#498] Fix image tags on conf
  infrastructure/scripts/conf.sh
Labels: fix

#514 [#499] Future-proof metadata model
  backend/BUILD
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java
  backend/avro/communication/BUILD
  backend/avro/communication/metadata.avsc
  backend/avro/communication/metadata/src/main/java/co/airy/avro/communication/MetadataKeys.java
  backend/avro/communication/metadata/src/main/java/co/airy/avro/communication/MetadataMapper.java
  backend/avro/communication/metadata/src/main/java/co/airy/avro/communication/MetadataRepository.java
  backend/avro/communication/metadata/src/main/java/co/airy/avro/communication/Subject.java
  backend/sources/google/webhook/src/main/java/co/airy/core/sources/google/GoogleWebhook.java
  docs/docs/guides/airy-core-in-test-env.md
  frontend/demo/src/App.tsx
Labels: feature

#518 Doc/489 how to run the frontend
  frontend/README.md
  frontend/assets/airy_demo_login.png
  frontend/assets/airy_primary_rgb.svg
  frontend/demo/README.md
Labels: docs

#520 Changing content render api
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/MessageResponsePayload.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  backend/sources/twilio/sender/src/main/java/co/airy/core/sources/twilio/Sender.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
  docs/docs/api/http.md
  lib/java/mapping/src/main/java/co/airy/mapping/ContentMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/OutboundMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/SourceMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Image.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
Labels: feature

#529 [#523] Return source type in the channel payload
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  docs/docs/api/http.md
Labels: feature

#521 [#493] Route Google metadata to get displayname
  backend/sources/google/events-router/BUILD
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventInfo.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/GoogleInfoExtractor.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/InfoExtractor.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/ObjectMapperConfig.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
Labels: feature

#530 [#524] remove hyperlinks
  frontend/demo/README.md
Labels: docs

#531 Added Image content model for gogle
  lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java
Labels: feature

#532 [#496] Added Image content model for Twilio
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
Labels: feature

#539 [#496] Added Image content model for Facebook
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/resources/facebook/image.json
Labels: feature

#540 [#169] Use distroless for java images
  WORKSPACE
  tools/build/springboot.bzl
Labels: feature

#552 [#547] Introduce model lib for metadata and messages
  backend/BUILD
  backend/api/communication/BUILD
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java
  backend/avro/communication/BUILD
  backend/model/message/BUILD
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/metadata/BUILD
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataRepository.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/Subject.java
  backend/sources/chat-plugin/BUILD
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/facebook/events-router/BUILD
  backend/sources/google/connector/BUILD
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java
  backend/sources/google/events-router/BUILD
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/InfoExtractor.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  backend/sources/twilio/connector/BUILD
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java
  backend/sources/twilio/events-router/BUILD
  backend/webhook/publisher/BUILD
  lib/java/mapping/BUILD
Labels: feature

#553 [#551] Use test.properties everywhere
  backend/api/auth/BUILD
  backend/api/auth/src/test/java/co/airy/core/api/auth/UsersControllerTest.java
  backend/api/auth/src/test/resources/test.properties
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/WebhookControllerTest.java
  backend/sources/facebook/connector/src/test/resources/test.properties
  backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java
  backend/sources/facebook/events-router/src/test/resources/test.properties
  backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  backend/sources/google/events-router/src/test/resources/test.properties
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/WebhookControllerTest.java
  backend/sources/twilio/connector/src/test/resources/test.properties
  backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java
  backend/sources/twilio/events-router/src/test/resources/test.properties
  backend/webhook/publisher/BUILD
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
  backend/webhook/publisher/src/test/resources/test.properties
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
Labels: chore

#556 [#548] Extract payload to web library and introduce date lib
  backend/api/admin/BUILD
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/TagsController.java
  backend/api/auth/BUILD
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/UsersController.java
  backend/api/communication/BUILD
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketController.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/sources/chat-plugin/BUILD
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/events-router/BUILD
  backend/sources/google/connector/BUILD
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/WebhookController.java
  backend/sources/google/events-router/BUILD
  backend/sources/twilio/connector/BUILD
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
  backend/sources/twilio/events-router/BUILD
  backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/TwilioInfoExtractor.java
  backend/webhook/publisher/BUILD
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Mapper.java
  lib/java/date/BUILD
  lib/java/date/src/main/java/co/airy/date/format/DateFormat.java
  lib/java/payload/src/main/java/co/airy/payload/format/DateFormat.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/payload/EmptyResponsePayload.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/payload/RequestErrorResponsePayload.java
Labels: chore

#557 Stop logging facebook webhook requests
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java
  lib/java/spring/web/BUILD
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/RequestLoggingConfig.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/RequestLoggingFilter.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/RequestLoggingIgnorePatterns.java
Labels: feature

#560 [#485] [#486] Enrich HTTP docs
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationListRequestPayload.java
  docs/docs/api/http.md
  docs/docs/glossary.md
  docs/docs/index.md
Labels: docs

#563 [#562] Fix chatplugin generator
  infrastructure/scripts/chatplugin-generator.sh
Labels: fix

#561 [#466] Change public name of go modules
  lib/go/apiclient/go.mod
  lib/go/apiclient/payloads/go.mod
Labels: fix

#555 [#503] Customize commit interval so the test environment can have a d…
  backend/api/admin/src/main/resources/application.properties
  backend/api/communication/src/main/resources/application.properties
  backend/sources/chat-plugin/src/main/resources/application.properties
  backend/sources/facebook/connector/src/main/resources/application.properties
  backend/sources/facebook/events-router/src/main/resources/application.properties
  backend/sources/google/connector/src/main/resources/application.properties
  backend/sources/google/connector/src/test/resources/test.properties
  backend/sources/google/events-router/src/main/resources/application.properties
  backend/sources/twilio/connector/src/main/resources/application.properties
  backend/sources/twilio/events-router/src/main/resources/application.properties
  backend/webhook/publisher/src/main/resources/application.properties
  docs/docs/guides/airy-core-in-production.md
  infrastructure/airy.conf.all
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/kafka.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-publisher/templates/deployment.yaml
  lib/java/spring/kafka/streams/src/main/java/co/airy/spring/kafka/streams/KafkaStreamsConfig.java
Labels: feature

#565 [#564] Fix kafka configmap in helm
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/kafka.yaml
Labels: fix

#566 Introduce namespacing for topics
  .github/workflows/main.yml
  docs/docs/guides/airy-core-in-production.md
  docs/docs/overview/kafka.md
  infrastructure/README.md
  infrastructure/scripts/provision/create-topics.sh
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
  infrastructure/tools/topics/src/main/resources/topic.sh.tpl
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/AbstractTopic.java
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/application/ApplicationCommunicationReadReceipts.java
  package.json
  scripts/lint.sh
Labels: feature

#570 [#569] Facebook Messages from page are not parsed…
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java
Labels: fix

#573 [#572] Messages from facebook page should have…
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java
Labels: feature
