Repository airyhq/airy, pull requests merged in 2021-11, with the labels that each got.

#2529 Add CLI outdated version warning
  cli/integration/version_test.go
  cli/pkg/cmd/root.go
Labels: feature

#2538 [2457] Fix upgrade to same version
  cli/pkg/helm/helm.go
  infrastructure/helm-chart/templates/controller/deployment.yaml
Labels: fix

#2535 [#2434] Fix broken instagram Facebook inbox ingestion
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
Labels: fix

#2540 [#2518] Add fargate annotation
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/communication/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/websocket/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/integration/charts/webhook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/media/charts/resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/backend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/frontend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/facebook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/google/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/twilio/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/viber/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ngrok.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/deployment.yaml
  infrastructure/helm-chart/templates/controller/deployment.yaml
Labels: feature

#2542 [#2511] Fix Airy status command
  cli/pkg/cmd/status/status.go
  cli/pkg/console/output.go
  lib/go/httpclient/payloads/client_config_response_payload.go
Labels: fix

#2537 Print airy core version with version command
  cli/integration/version_test.go
  cli/pkg/cmd/BUILD
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/root.go
  cli/pkg/cmd/upgrade/upgrade.go
  cli/pkg/workspace/init.go
Labels: feature

#2547 [#2511] Fix docs for helm upgrade
  docs/docs/getting-started/installation/helm.md
  docs/docs/getting-started/upgrade.md
Labels: docs

#2551 [#2548] Use the cli with helm
  cli/go.sum
  cli/pkg/cmd/create/BUILD
  cli/pkg/cmd/upgrade/BUILD
  cli/pkg/helm/BUILD
  cli/pkg/kube/BUILD
  cli/pkg/kube/context.go
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/helm.md
  docs/docs/getting-started/installation/minikube.md
Labels: fix

#2558 [#2557] Fix jumping conversationlist
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
Labels: fix

#2561 [#2560] Dev_cli.sh fails to apply the config
  scripts/dev_cli.sh
Labels: feature

#2545 [#2544] Include the analytics demo files in the jupyter hub
  infrastructure/terraform/demos/analytics/files/jupyter-config.yaml
Labels: fix

#2564 [#2563] Allow for disabling emojis in the chatplugin
  frontend/chat-plugin/lib/BUILD
  frontend/ui/src/components/Input.tsx
  lib/typescript/components/BUILD
  lib/typescript/components/inputs/Input/index.tsx
  lib/typescript/components/loaders/AiryLoader/data.ts
  lib/typescript/components/loaders/AiryLoader/index.tsx
  lib/typescript/components/loaders/AiryLoader/style.module.scss
  lib/typescript/components/loaders/index.ts
  package.json
  yarn.lock
Labels: feature

#2555 [#2518] Add terraform code for core deployment
  cli/pkg/helm/helm.go
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/terraform.md
  docs/static/icons/terraform.svg
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/communication/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/websocket/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/integration/charts/source-api/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/integration/charts/webhook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/media/charts/resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/backend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/frontend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/facebook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/google/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/twilio/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/viber/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ngrok.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/service.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/serviceaccount.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/deployment.yaml
  infrastructure/helm-chart/templates/controller/deployment.yaml
  infrastructure/helm-chart/templates/provisioning/job-wait.yaml
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  infrastructure/helm-chart/templates/provisioning/scripts.yaml
  infrastructure/helm-chart/templates/serviceaccount.yaml
  infrastructure/terraform/kubernetes/main.tf
  infrastructure/terraform/kubernetes/outputs.tf
  infrastructure/terraform/kubernetes/variables.tf
  infrastructure/terraform/main/main.tf
  infrastructure/terraform/main/variables.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/outputs.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/outputs.tf
  infrastructure/terraform/modules/core/variables.tf
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
Labels: feature

#2578 [#2576] Render Survey response Google Business Messages
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/components/SurveyResponse/index.module.scss
  lib/typescript/render/providers/google/components/SurveyResponse/index.tsx
  lib/typescript/render/providers/google/googleModel.ts
Labels: fix

#2574 [#2108] render attachments via whatsapp
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/services/types/attachmentsTypes.ts
  lib/typescript/components/alerts/ErrorPopUp/style.module.scss
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/attachments.ts
  lib/typescript/render/components/Audio/index.module.scss
  lib/typescript/render/components/File/index.module.scss
  lib/typescript/render/components/File/index.tsx
  lib/typescript/render/components/Image/index.module.scss
  lib/typescript/render/components/Image/index.tsx
  lib/typescript/render/components/Video/index.module.scss
  lib/typescript/render/components/Video/index.tsx
  lib/typescript/render/index.ts
  lib/typescript/render/outbound/chatplugin.ts
  lib/typescript/render/outbound/facebook.ts
  lib/typescript/render/outbound/google.ts
  lib/typescript/render/outbound/twilio.ts
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/MediaTemplate/index.module.scss
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/components/RequestedLiveAgent/index.tsx
  lib/typescript/render/providers/twilio/TwilioRender.tsx
  lib/typescript/render/providers/twilio/components/CurrentLocation/index.module.scss
  lib/typescript/render/providers/twilio/components/CurrentLocation/index.tsx
  lib/typescript/render/providers/twilio/twilioModel.ts
  lib/typescript/render/services/decodeURIComponentMessage.ts
  lib/typescript/render/services/index.ts
  lib/typescript/render/services/mediaAttachments.ts
Labels: feature

#2585 Custom message colors chatplugin + Documentation
  docs/docs/sources/chatplugin/customization.md
  frontend/chat-plugin/dev/config.ts
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/config.ts
  frontend/ui/src/assets/scss/colors.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
  lib/typescript/assets/scss/colors.scss
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/components/UnknownSourceText/index.module.scss
Labels: feature

#2584 fixed input accept formatting
  frontend/ui/src/services/types/attachmentsTypes.ts
  lib/typescript/render/services/mediaAttachments.ts
Labels: fix

#2603 [#2119] Send/render attachments chatplugin
  frontend/chat-plugin/dev/config.ts
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/InputSelector/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/InputSelector/index.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/api/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/chat-plugin/lib/src/components/dragAndDrop/index.module.scss
  frontend/chat-plugin/lib/src/components/dragAndDrop/index.tsx
  frontend/chat-plugin/lib/src/global.d.ts
  frontend/chat-plugin/lib/src/websocket/index.ts
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  lib/typescript/assets/images/icons/paperclipChatplugin.svg
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
  lib/typescript/render/providers/twilio/TwilioRender.tsx
  lib/typescript/render/services/mediaAttachments.ts
Labels: feature

#2587 [#2586] Terraform core module has wrong Helm link
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-ui/templates/ingress.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/frontend/ingress.yaml
  infrastructure/helm-chart/charts/components/templates/ingress.yaml
  infrastructure/terraform/main/main.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/variables.tf
Labels: feature

#2607 [#2605] Fix predefined cli version
  cli/pkg/helm/helm.go
Labels: fix

#2613 [#2154] Fixed add tag behaviour
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
Labels: fix

#2609 [#2604] Added attachment toggle for chatplugin
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/config.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: feature

#2625 [#2434] Fix instagram ingestion race condition
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/EventsRouter.java
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
Labels: fix
