Repository airyhq/airy, pull requests merged in 2021-06, with the labels that each got.

#1879 [#1716] Edit contact information
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationUpdateContactRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsUpdateTest.java
  docs/docs/api/endpoints/conversations.md
Labels: feature

#1888 Follow up: Add missing path
  infrastructure/helm-chart/templates/ingress.yaml
Labels: feature

#1890 [#1887] facebook render library improvement: postback and images
  lib/typescript/render/components/Image/index.module.scss
  lib/typescript/render/components/Image/index.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: fix

#1897 [#1868] tagging filtered conversations doesn't work properly
  frontend/ui/src/reducers/data/conversations/index.ts
Labels: fix

#1900 [#1898] Webhook should start from latest message
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/BeanstalkPublisher.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
Labels: fix

#1902 [#1716] Enabled edit displayName
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/NoConversations/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  lib/typescript/assets/images/icons/edit-pencil.svg
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/endpoints/updateContact.ts
  lib/typescript/httpclient/src/payload/UpdateContactRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
Labels: feature

#1903 [#1899] Remove filtered total
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/PaginationData.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/introduction.md
  docs/docs/api/endpoints/messages.md
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
Labels: feature

#1908 [#1904] Refactored conversations reducer
  frontend/ui/src/reducers/data/conversations/index.ts
  frontend/ui/src/reducers/data/conversationsFilter/index.ts
  frontend/ui/src/reducers/data/index.ts
  frontend/ui/src/selectors/conversations.ts
Labels: fix

#1909 [#1762] attachments don't get displayed properly in the message input
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/FallbackAttachment/index.module.scss
  lib/typescript/render/providers/facebook/components/FallbackAttachment/index.tsx
  lib/typescript/render/providers/facebook/components/MediaTemplate/index.module.scss
Labels: fix

#1915 [#1907] Fixed customize screen for 13' displays
  frontend/ui/src/App.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  frontend/ui/src/reducers/data/conversationsFilter/index.ts
Labels: fix

#1918 [#1913] Last message icon for image sent in Google conversation displays text
  lib/typescript/render/SourceMessagePreview.tsx
Labels: fix

#1920 [#1919] Fixed min-height
  frontend/ui/src/App.module.scss
Labels: fix

#1923 [#1921] Hotfix: Filter out Facebook echoes sent by airy
  VERSION
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
Labels: fix

#1922 [#1921] Hotfix: Facebook echo ingestion
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  docs/docs/changelog.md
Labels: fix

#1925 [#1924] Fixed long message in messageInput
  frontend/ui/src/App.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/index.module.scss
Labels: fix

#1938 [#1936] Minor grammar edits- Getting Started
  docs/docs/getting-started/glossary.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/quickstart.md
  docs/docs/getting-started/troubleshooting.md
Labels: docs

#1934 [#1932] Added scrollToBotton in messageList
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
Labels: fix

#1940 [#1939] Redirect root request to /ui
  infrastructure/helm-chart/templates/ingress-ui.yaml
Labels: fix

#1937 [#1926] Polishing the docs
  docs/docs/api/introduction.md
  docs/docs/api/webhook.md
  docs/docs/cli/introduction.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/installation/security.md
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chatplugin/installation.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
  docs/docs/ui/inbox.md
  docs/sidebars.js
  docs/src/css/custom.css
Labels: docs

#1945 [#1926] Docs for using a custom public hostname
  docs/docs/getting-started/installation/aws.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/twilio-sources.mdx
Labels: docs

#1983 [#1967] Fixed messageInput
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  lib/typescript/render/components/Text/index.module.scss
Labels: fix

#1992 [#1952] Fix embedded path for Airy create on Windows
  cli/pkg/workspace/template/copy.go
  docs/docs/cli/introduction.md
  docs/docs/getting-started/installation/introduction.md
Labels: fix

#2001 [#1939] Redirect / to /ui
  cli/pkg/providers/aws/aws.go
  docs/docs/getting-started/installation/aws.md
  infrastructure/helm-chart/templates/ingress-ui.yaml
Labels: fix

#2007 [#1974] Upgrade to Facebook API graph version 11
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Api.java
Labels: chore

#1995 [#1985] Bug: Template Title not Rendering
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: fix

#2006 [#1991] re-organizing infinite scroll for conversationlist and messagelist
  frontend/ui/BUILD
  frontend/ui/src/components/ResizableWindowList/index.module.scss
  frontend/ui/src/components/ResizableWindowList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  package.json
  yarn.lock
Labels: fix

#1961 [#1752] Add connect cluster chart
  docs/docs/getting-started/installation/configuration.md
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/templates/jmx-configmap.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka-connect/values.yaml
  infrastructure/images/kafka-connect/Dockerfile
  infrastructure/images/kafka-connect/Makefile
Labels: feature

#2033 [#2030] Expose all jvm dependencies
  .github/CODEOWNERS
  WORKSPACE
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/PrincipalAccess.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/CookieSecurityContextRepository.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/HttpLogFilter.java
  repositories.bzl
Labels: chore

#2039 [#2038] Fix broken download links on release page
  docs/docs/changelog.md
Labels: fix

#2054 [#2009] Fixed unnecessary recalls and rerenders
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.module.scss
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.tsx
  lib/typescript/render/components/Avatar/index.tsx
Labels: fix

#2067 [#1819] Add Airy favicon
  .github/workflows/main.yml
  WORKSPACE
  frontend/ui/development.html
Labels: feature

#2068 [#2060] edit text templates
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/services/types/messageTypes.ts
Labels: fix

#2066 [#2056] Added first transition and animations
  frontend/ui/src/assets/animations/animations.scss
  frontend/ui/src/assets/animations/index.ts
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/index.module.scss
Labels: feature

#2057 [#1391] Cypress test for suggested replies
  frontend/ui/handles/index.ts
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx
  integration/cypress.json
  integration/ui/suggested_replies.spec.ts
Labels: feature

#2061 [#1914] Cypress test for conversation state
  frontend/ui/handles/index.ts
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
  integration/ui/state_conversations.spec.ts
Labels: feature
