Repository airyhq/airy, pull requests merged in 2021-09, with the labels that each got.

#2363 [#2229] instagram source render story mention in inbox UI
  lib/typescript/assets/images/icons/external-link.svg
  lib/typescript/dates/convert.ts
  lib/typescript/dates/index.ts
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/InstagramStoryMention/index.module.scss
  lib/typescript/render/providers/facebook/components/InstagramStoryMention/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#2367 [#2227] instagram source show story reply in inbox UI
  lib/typescript/assets/images/icons/play-circle.svg
  lib/typescript/dates/convert.ts
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.module.scss
  lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#2371 [#2370] Fix inbox counter bug when paginating
  frontend/ui/src/reducers/data/conversations/index.ts
Labels: fix

#2376 [#2358] preventing second enter when sending messages
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
Labels: feature

#2391 [#2390] Document supported minikube versions
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#2395 [#2394] Fixes source api ingress typo
  .github/ISSUE_TEMPLATE/---docs.md
  infrastructure/helm-chart/charts/core/templates/ingress.yaml
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/CommonProviders.java
Labels: fix

#2402 [#2390] Switch to nginx ingress controller
  cli/pkg/helm/BUILD
  cli/pkg/helm/helm.go
  cli/pkg/providers/aws/aws.go
  cli/pkg/workspace/airy_yaml.go
  cli/pkg/workspace/template/src/airy.yaml
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/security.md
  frontend/chat-plugin/dev/BUILD
  frontend/ui/BUILD
  infrastructure/helm-chart/charts/core/charts/provisioning/templates/job-wait.yaml
  infrastructure/helm-chart/charts/core/charts/upgrading/templates/0.29.0.yaml
  infrastructure/helm-chart/charts/core/charts/upgrading/templates/cleanup-old-jobs.yaml
  infrastructure/helm-chart/charts/core/charts/upgrading/templates/scripts.yaml
  infrastructure/helm-chart/charts/core/charts/upgrading/templates/serviceaccount.yaml
  infrastructure/helm-chart/charts/core/charts/upgrading/values.yaml
  infrastructure/helm-chart/charts/core/templates/configmap.yaml
  infrastructure/helm-chart/charts/core/templates/ingress-ui.yaml
  infrastructure/helm-chart/charts/core/templates/ingress.yaml
  infrastructure/helm-chart/charts/core/templates/ngrok.yaml
  infrastructure/helm-chart/charts/core/values.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/host-update.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller-http.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller-https-letsencrypt.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/letsencrypt.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/scripts.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/service.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/serviceaccount.yaml
  infrastructure/helm-chart/charts/ingress-controller/values.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/ingress.yaml
  infrastructure/helm-chart/values.yaml
Labels: fix

#2408 [#2390] Add ingress class for ngrok
  infrastructure/helm-chart/charts/core/templates/ngrok.yaml
Labels: fix

#2325 [#2257] Add analytics demo
  .gitignore
  docs/docs/guides/analytics-demo.md
  docs/sidebars.js
  docs/static/img/guides/analytics-demo/airy_core_ui.png
  docs/static/img/guides/analytics-demo/ec2_security_group.png
  docs/static/img/guides/analytics-demo/fake_data_df.png
  docs/static/img/guides/analytics-demo/fake_data_inbox.png
  docs/static/img/guides/analytics-demo/jupyterhub.png
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/deployment.yaml
  infrastructure/terraform/demos/analytics/files/jupyter-config.yaml
  infrastructure/terraform/demos/analytics/files/values.yaml
  infrastructure/terraform/demos/analytics/main.tf
  infrastructure/terraform/demos/analytics/outputs.tf
  infrastructure/terraform/demos/analytics/variables.tf
  infrastructure/terraform/demos/analytics/workspace/cli.yaml
Labels: feature

#2412 [#2257] Rename files
  docs/static/img/guides/analytics-demo/demo_data_df.png
  docs/static/img/guides/analytics-demo/demo_data_inbox.png
Labels: docs

#2409 Improve AWS docs
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/guides/backup.md
  docs/sidebars.js
  infrastructure/tools/restore/pv.yaml
  infrastructure/tools/restore/pvc.yaml
Labels: docs

#2404 [#2109] render send file attachments via facebook messenger
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  lib/typescript/assets/images/icons/download.svg
  lib/typescript/assets/images/icons/file-audio.svg
  lib/typescript/assets/images/icons/file-download.svg
  lib/typescript/assets/images/icons/paperclip.svg
  lib/typescript/assets/images/icons/pause.svg
  lib/typescript/assets/images/icons/play.svg
  lib/typescript/assets/images/icons/stop.svg
  lib/typescript/assets/images/icons/volume.svg
  lib/typescript/components/alerts/ErrorPopUp/index.tsx
  lib/typescript/components/alerts/ErrorPopUp/style.module.scss
  lib/typescript/dates/format.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/endpoints/uploadFile.ts
  lib/typescript/httpclient/src/payload/UploadFileRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
  lib/typescript/render/attachments.ts
  lib/typescript/render/components/Audio/index.module.scss
  lib/typescript/render/components/Audio/index.tsx
  lib/typescript/render/components/File/index.module.scss
  lib/typescript/render/components/File/index.tsx
  lib/typescript/render/components/Image/index.module.scss
  lib/typescript/render/components/Video/index.module.scss
  lib/typescript/render/components/index.ts
  lib/typescript/render/outbound/facebook.ts
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#2420 [#2405] Icons for Rendering/Sending File Attachments
  lib/typescript/render/SourceMessagePreview.tsx
Labels: feature

#2426 [#628] make library compatible with node.js
  lib/typescript/httpclient/BUILD
  lib/typescript/httpclient/client.ts
  package.json
  yarn.lock
Labels: feature

#2431 Add more chatplugin options
  docs/docs/sources/chatplugin/customization.md
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/chat-plugin/lib/src/config.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  lib/typescript/assets/images/icons/paperplane.svg
Labels: feature

#2433 Added more options to the UI
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: feature

#2442 [#2390] Fix serviceAccount for helm
  infrastructure/helm-chart/charts/core/templates/serviceaccount.yaml
Labels: fix

#2446 [#2390] Fix duplicate ingress port definition
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller.yaml
Labels: fix

#2451 [#2434] Fix instagram echo ingestion
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
Labels: fix

#2430 [#2423] track core installation
  cli/go.mod
  cli/go.sum
  cli/pkg/cmd/create/BUILD
  cli/pkg/cmd/create/create.go
  cli/pkg/console/BUILD
  cli/pkg/console/segment.go
  cli/pkg/providers/BUILD
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/BUILD
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  cli/pkg/workspace/airy_yaml.go
  docs/docs/cli/usage.md
  go.mod
  go.sum
  go_repositories.bzl
  scripts/dev_cli.sh
Labels: feature

#2444 [#2443] Allow for compatability with mobile login flows
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/AuthCookie.java
  lib/java/spring/core/src/main/resources/default.properties
Labels: feature
