Repository airyhq/airy, pull requests merged in 2021-02, with the labels that each got.

#786 Keep default in sync with the rest of the system
  infrastructure/cli/cmd/api/login.go
Labels: fix

#782 [#754] Specify CPUs and memory at bootstrap
  docs/docs/getting-started/deployment/test-environment.md
  infrastructure/Vagrantfile
  scripts/bootstrap.sh
Labels: feature

#787 [#739] Fix Airy cli version when provisioning
  .github/workflows/main.yml
  infrastructure/scripts/provision/core.sh
Labels: fix

#708 [#538] Wire websocket server to the redux store
  frontend/demo/BUILD
  frontend/demo/src/App.tsx
  frontend/demo/src/actions/channel/index.ts
  frontend/demo/src/actions/conversations/index.ts
  frontend/demo/src/actions/messages/index.ts
  frontend/demo/src/components/AiryWebsocket/index.tsx
  frontend/demo/src/reducers/data/channels/index.ts
  frontend/demo/src/reducers/data/conversations/index.ts
  frontend/demo/src/reducers/data/messages/index.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/mappers/channelMapper.ts
  lib/typescript/httpclient/mappers/conversationMapper.ts
  lib/typescript/httpclient/model/Conversation.ts
  lib/typescript/websocketclient/BUILD
  lib/typescript/websocketclient/README.md
  lib/typescript/websocketclient/index.ts
  lib/typescript/websocketclient/stompWrapper.ts
  package.json
  tsconfig.json
Labels: feature

#795 [#791] Message Input UI/Design Improvement
  frontend/demo/src/pages/Inbox/MessageInput/index.module.scss
  frontend/demo/src/pages/Inbox/MessageInput/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
Labels: fix

#803 Fix expanding message container
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
Labels: fix

#808 [#804] Websocket crashes when new conversation is…
  frontend/demo/src/reducers/data/conversations/index.ts
Labels: feature

#811 [#809] Httpclientinstance does not get new auth…
  frontend/demo/src/actions/user/index.ts
  lib/typescript/httpclient/index.ts
Labels: feature

#816 [#813] Prevent sending empty messages
  frontend/demo/src/pages/Inbox/MessageInput/index.tsx
Labels: fix

#817 [#815] Rename sources
  docs/docs/getting-started/introduction.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
Labels: docs

#716 Feature/642 extract message rendering to a library
  frontend/assets/BUILD
  frontend/assets/images/icons/airy_demo_login.png
  frontend/assets/images/icons/airy_primary_rgb.svg
  frontend/assets/index.ts
  frontend/assets/scss/colors.scss
  frontend/assets/scss/fonts.scss
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/iframe.tsx
  frontend/demo/BUILD
  frontend/demo/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/dates/BUILD
  lib/typescript/dates/format.ts
  lib/typescript/dates/index.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/mappers/index.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/payload/MessagePayload.ts
  lib/typescript/httpclient/payload/index.ts
  lib/typescript/render/BUILD
  lib/typescript/render/index.tsx
  lib/typescript/render/messages/TextRender/index.module.scss
  lib/typescript/render/messages/TextRender/index.tsx
  tsconfig.json
Labels: feature

#793 display messages from auth in chat plugin
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/websocket/index.ts
  lib/typescript/httpclient/payload/MessagePayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: fix

#801 [#754] Fix bootstrap for empty vars
  infrastructure/Vagrantfile
  scripts/bootstrap.sh
Labels: fix

#823 [#819] Introduce sources introduction
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/introduction.md
  docs/sidebars.js
Labels: docs

#825 [#824] When sending a message to the Chat Plugin,…
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
Labels: feature

#822 Add more docs on the installation process
  docs/docs/getting-started/cli.md
  docs/docs/getting-started/installation.md
Labels: docs

#837 [#735] Show airy logo on darkmode
  docs/docusaurus.config.js
  docs/static/img/logo_dark.svg
  docs/static/img/logo_light.svg
Labels: docs

#839 [#605] Rename also the charts
  docs/docs/getting-started/deployment/production.md
  infrastructure/cli/cmd/ui/ui.go
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-demo/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/values.yaml
Labels: chore

#770 Fix/750 rename response metadata
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationListResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageListResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/PaginationData.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/introduction.md
  docs/docs/api/endpoints/messages.md
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/actions/messages/index.ts
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/mappers/paginatedPayloadMapper.ts
  lib/typescript/httpclient/payload/PaginatedPayload.ts
  lib/typescript/httpclient/payload/PaginatedResponse.ts
  lib/typescript/httpclient/payload/ResponseMetadataPayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: fix

#843 [#833] Bottom space in conversation list
  frontend/ui/src/components/ResizableWindowList/index.module.scss
  frontend/ui/src/components/ResizableWindowList/index.tsx
Labels: feature

#845 [#832] Merging messages when loading conversations
  frontend/ui/src/pages/Inbox/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
Labels: fix

#830 [#729] Make auth header compliant with rfc6750 (Bearer auth)
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketConfig.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/JwtAuthenticationFilter.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/WebSocketConfig.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  docs/docs/api/authentication.md
  docs/docs/getting-started/quickstart.md
  frontend/chat-plugin/src/components/api/index.tsx
  frontend/chat-plugin/src/components/websocket/index.ts
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java
  lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelper.java
  lib/typescript/httpclient/index.ts
  lib/typescript/websocketclient/stompWrapper.ts
Labels: feature

#850 [#575] Fix window: any type definition
  frontend/ui/src/env.ts
Labels: chore

#851 [#834]Delete link in old inbox and css fix
  frontend/ui/src/components/TopBar/index.module.scss
  frontend/ui/src/components/TopBar/index.tsx
Labels: fix

#836 Introduce channels domain to source specific channel APIs
  .prettierignore
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
  docs/docs/api/endpoints/channel-disconnect.mdx
  docs/docs/api/endpoints/channels.md
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/pages/Channels/index.tsx
  infrastructure/helm-chart/templates/ingress.yaml
  lib/typescript/httpclient/index.ts
Labels: feature

#838 [#772] Add Airy Core, Airy Enterprise, Need help? and github links to navigationBar
  docs/docusaurus.config.js
Labels: feature

#853 [#827] Chatplugin uses its own payload
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/MessagesTreeSet.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageListResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageUpsertPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  backend/model/message/BUILD
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageContainer.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/WebSocketController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/AuthenticationResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/MessageUpsertPayload.java
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/messages.md
  docs/docs/api/websocket.md
Labels: feature

#865 [#796 ] Add shellcheck lint
  infrastructure/images/kafka/scripts/configure-kafka.sh
  infrastructure/images/kafka/scripts/configure-zookeeper.sh
  infrastructure/images/kafka/scripts/entrypoint.sh
  infrastructure/scripts/chatplugin-generator.sh
  infrastructure/scripts/lib/api.sh
  infrastructure/scripts/lib/k8s.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/provision/create-topics.sh
  infrastructure/scripts/provision/prerequisites.sh
  infrastructure/scripts/smoke-test.sh
  infrastructure/scripts/status.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
  scripts/bootstrap.sh
  scripts/lint.sh
  scripts/push-images.sh
  scripts/release.sh
  tools/build/springboot_pkg.sh
Labels: chore

#864 Fix facebook text render
  bazel.tsconfig.json
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
  frontend/ui/src/reducers/data/messages/index.ts
  frontend/ui/src/selectors/conversations.ts
  lib/typescript/dates/BUILD
  lib/typescript/dates/compare.ts
  lib/typescript/dates/format.ts
  lib/typescript/dates/index.ts
  lib/typescript/httpclient/model/Conversation.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/render/components/Avatar/index.module.scss
  lib/typescript/render/components/Avatar/index.tsx
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/components/index.ts
  lib/typescript/render/index.tsx
  lib/typescript/render/messages/TextRender/index.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
  lib/typescript/render/renderProviders.ts
  lib/typescript/render/shared.ts
  tsconfig.json
Labels: fix

#857 [#841] Logout if user auth token is wrong
  frontend/ui/src/InitializeAiryApi.ts
  lib/typescript/httpclient/index.ts
Labels: fix

#870 [#796] Mv shellsheck installation to workflow
  .github/workflows/main.yml
  scripts/lint.sh
Labels: fix

#887 Highlight component for docs
  docs/docs/api/authentication.md
  docs/docs/api/introduction.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/getting-started/cli.md
  docs/docs/getting-started/deployment/introduction.md
  docs/docs/getting-started/glossary.md
  docs/docs/getting-started/installation.md
  docs/docs/getting-started/introduction.md
  docs/docs/getting-started/quickstart.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/integrations/rasa.md
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/introduction.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
  docs/src/components/Highlighter.js
  docs/src/css/custom.css
Labels: docs

#873 [#846] Docs for airy config yaml
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/deployment/configuration.md
  docs/docs/getting-started/deployment/production.md
  docs/docs/getting-started/deployment/vagrant.md
  docs/docs/sources/facebook.md
  docs/sidebars.js
  infrastructure/airy.tpl.yaml
Labels: docs

#907 Fix Chatplugin style
  frontend/chat-plugin/example.html
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  lib/typescript/render/components/Text/index.module.scss
Labels: fix

#891 Map metadata to object
  backend/model/metadata/BUILD
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java
  backend/model/metadata/src/test/java/co/airy/model/metadata/ObjectMapperTest.java
Labels: feature

#901 Feature/858 render rich card
  lib/typescript/render/components/Media/index.module.scss
  lib/typescript/render/components/Media/index.tsx
  lib/typescript/render/components/RichCard/index.module.scss
  lib/typescript/render/components/RichCard/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
Labels: feature

#896 [#876] cli install doc revamp
  docs/docs/api/authentication.md
  docs/docs/api/introduction.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/cli/installation.md
  docs/docs/cli/introduction.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/cli.md
  docs/docs/getting-started/deployment/configuration.md
  docs/docs/getting-started/deployment/introduction.md
  docs/docs/getting-started/deployment/vagrant.md
  docs/docs/getting-started/glossary.md
  docs/docs/getting-started/installation.md
  docs/docs/getting-started/introduction.md
  docs/docs/getting-started/quickstart.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/integrations/rasa.md
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/introduction.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/whatsapp-twilio.md
  docs/sidebars.js
  docs/src/components/Box.js
  docs/src/components/TLDR.js
Labels: docs

#912 fixed rich card rendering with product requirements
  lib/typescript/render/components/RichCard/index.module.scss
  lib/typescript/render/components/RichCard/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
Labels: fix

#916 [#899] Quickstart with steps
  docs/docs/getting-started/quickstart.md
Labels: docs

#917 [#893] Enable showLastUpdateTime
  docs/docusaurus.config.js
Labels: docs

#847 [#722] Add AKHQ as optional tool
  infrastructure/airy.tpl.yaml
  infrastructure/helm-chart/charts/tools/Chart.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/Chart.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/configmap.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/ingress.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/service.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/values.yaml
  infrastructure/helm-chart/values.yaml
Labels: feature

#902 [#852] Feature/852 add google rich text to render library
  lib/typescript/render/components/RichText/index.module.scss
  lib/typescript/render/components/RichText/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
Labels: feature

#921 [#855] Render Button Template from Facebook
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#923 [#922] Add yaml config doc to sidebars
  docs/sidebars.js
Labels: fix

#933 [#910] Add message metadata API
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  frontend/ui/README.md
  lib/typescript/httpclient/payload/MessagePayload.ts
Labels: feature

#928 New Airy websocket using Airy events
  backend/api/websocket/BUILD
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/Stores.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketConfig.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketController.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/ChannelEvent.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/Event.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/MessageEvent.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/MetadataEvent.java
  backend/api/websocket/src/main/resources/application.properties
  backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java
  backend/api/websocket/src/test/resources/test.properties
  backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java
  docs/docs/api/websocket.md
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/values.yaml
  infrastructure/helm-chart/templates/ingress.yaml
  lib/typescript/httpclient/mappers/channelMapper.ts
  lib/typescript/httpclient/payload/MessagePayload.ts
Labels: feature

#937 [#910] Add message metadata API documentation
  docs/docs/api/endpoints/messages.md
  docs/docs/api/websocket.md
  docs/docs/sources/chat-plugin.md
Labels: feature

#942 Feature/861 render quick replies from facebook
  lib/typescript/render/components/RichCard/Media/index.module.scss
  lib/typescript/render/components/RichCard/Media/index.tsx
  lib/typescript/render/components/RichCard/index.tsx
  lib/typescript/render/components/Video/index.module.scss
  lib/typescript/render/components/Video/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/QuickReplies/index.module.scss
  lib/typescript/render/providers/facebook/components/QuickReplies/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#872 [#675] Add Templates Endpoints documentation
  docs/docs/api/endpoints/templates.md
  docs/docs/getting-started/glossary.md
Labels: feature

#951 [#860] Render Generic Template Carousel from…
  lib/typescript/render/BUILD
  lib/typescript/render/assets/icons/chevron_left.svg
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
  package.json
  yarn.lock
Labels: feature

#953 [#949] Improve UI of chatplugin
  frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/src/components/chat/index.module.scss
  lib/typescript/render/components/RichText/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
Labels: feature

#943 [309] homebrew cli tap
  .github/workflows/main.yml
  VERSION
  docs/docs/cli/installation.md
  docs/sidebars.js
  scripts/upload-cli-binaries.sh
Labels: feature

#940 [#914] Add ingress and docs for AKHQ
  docs/docs/getting-started/deployment/configuration.md
  docs/docs/getting-started/deployment/production.md
  docs/docs/getting-started/deployment/vagrant.md
  infrastructure/Vagrantfile
  infrastructure/airy.tpl.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/configmap.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/ingress.yaml
Labels: fix

#958 [#956] Fix side problem in chatplugin source
  frontend/chat-plugin/src/components/chat/index.tsx
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/shared.ts
Labels: fix

#959 [#950] Add update homebrew formula step to release process
  docs/docs/cli/installation.md
  docs/docs/concepts/release-process.md
Labels: feature

#961 Allow any message to be sent to the chat plugin
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
Labels: feature

#963 [#938] Buttons, buttons everywhere
  README.md
  docs/docs/api/introduction.md
  docs/docs/cli/installation.md
  docs/docs/getting-started/deployment/introduction.md
  docs/docs/getting-started/installation.md
  docs/docs/getting-started/introduction.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/sources/introduction.md
  docs/src/components/ButtonBoxList/index.js
  docs/src/components/ButtonBoxList/styles.module.css
  docs/static/icons/airy-bubble.svg
  docs/static/icons/bolt.svg
  docs/static/icons/cloud.svg
  docs/static/icons/deploy.svg
  docs/static/icons/diamond.svg
  docs/static/icons/drafting.svg
  docs/static/icons/facebook-messenger.svg
  docs/static/icons/google.svg
  docs/static/icons/server-stack.svg
  docs/static/icons/slack.svg
  docs/static/icons/sms.svg
  docs/static/icons/vagrant.svg
  docs/static/icons/webhooks.svg
  docs/static/icons/whatsapp.svg
  docs/static/img/getting-started/deployment/introduction/apache_kafka-vertical.svg
Labels: docs

#964 Fix missing annotation in google webhook
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/WebhookController.java
Labels: fix

#978 Do not rely on jar ordering
  tools/build/springboot_pkg.sh
Labels: fix

#971 Put cobra cmd docs in one file
  .prettierignore
  backend/api/websocket/BUILD
  docs/cli-doc/BUILD
  docs/cli-doc/generate_cli_docs.go
  docs/cli-doc/util.go
  docs/docs/cli/airy.md
  docs/docs/cli/airy_api.md
  docs/docs/cli/airy_api_login.md
  docs/docs/cli/airy_api_signup.md
  docs/docs/cli/airy_config.md
  docs/docs/cli/airy_config_apply.md
  docs/docs/cli/airy_init.md
  docs/docs/cli/airy_status.md
  docs/docs/cli/airy_ui.md
  docs/docs/cli/airy_version.md
  docs/docs/cli/installation.md
  docs/docs/cli/introduction.md
  docs/docs/cli/reference.md
  docs/docs/getting-started/deployment/configuration.md
  docs/sidebars.js
  scripts/lint.sh
Labels: docs

#979 [#733] Docs under main website
  docs/docusaurus.config.js
Labels: fix

#984 [#960] Scope svg styles so that we don't break the sidebar
  docs/src/components/ButtonBox/styles.module.css
Labels: fix

#985 [#975] Rename Airy Core Platform
  README.md
  backend/avro/README.md
  docs/docs/concepts/design-principles.md
  docs/docs/sources/google.md
  frontend/README.md
  frontend/ui/README.md
  infrastructure/helm-chart/Chart.yaml
  infrastructure/helm-chart/charts/apps/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/api/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/Chart.yaml
  infrastructure/helm-chart/charts/tools/Chart.yaml
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/status.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
Labels: chore

#955 [#882] New /metadata.upsert API endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/UpsertMetadataRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  docs/docs/api/endpoints/metadata.md
Labels: feature

#990 [#849] Introduce dynamic page titles
  frontend/ui/src/App.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
  frontend/ui/src/pages/Login/index.tsx
  frontend/ui/src/pages/NotFound/index.tsx
  frontend/ui/src/pages/Tags/index.tsx
  frontend/ui/src/services/pageTitle.ts
Labels: feature

#993 Start frontend components in start.sh
  infrastructure/scripts/trigger/start.sh
Labels: fix

#973 [#807] Introduction to UI docs
  docs/docs/apps/ui.md
  docs/docs/apps/ui/components.md
  docs/docs/apps/ui/inbox.md
  docs/docs/apps/ui/introduction.md
  docs/docs/apps/ui/tags.md
  docs/docs/apps/ui/ui-quick-start.md
  docs/sidebars.js
  docs/static/icons/cog.svg
  docs/static/icons/information-architecture.svg
  docs/static/icons/price-tag.svg
  docs/static/icons/prototype.svg
  docs/static/icons/sms.svg
  docs/static/icons/users.svg
  docs/static/img/apps/ui/demotags.gif
Labels: feature

#991 Fix Netlify docs previews
  docs/docusaurus.config.js
Labels: chore

#977 [#934] Parse (but don't map) API message response…
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/messages.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/sources/chat-plugin.md
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
Labels: feature

#996 [#967] Add UI Quickstart
  docs/docs/apps/ui/introduction.md
  docs/docs/apps/ui/quickstart.md
  docs/docs/apps/ui/ui-quick-start.md
  docs/sidebars.js
  docs/static/img/apps/ui/login.gif
Labels: docs

#1021 [#670] Render Rich Card Carousel (Google Style)…
  frontend/chat-plugin/src/components/chat/index.tsx
  lib/typescript/render/assets/icons/chevron_left.svg
  lib/typescript/render/components/Carousel/index.module.scss
  lib/typescript/render/components/Carousel/index.tsx
  lib/typescript/render/components/RichCardCarousel/index.module.scss
  lib/typescript/render/components/RichCardCarousel/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
Labels: feature

#988 [#918] Consume Airy Events from new websocket in the UI
  .eslintrc
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  backend/model/channel/src/main/java/co/airy/model/channel/ChannelPayload.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageContainer.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
  docs/docs/api/endpoints/channels.md
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/actions/messages/index.ts
  frontend/ui/src/actions/metadata/index.ts
  frontend/ui/src/actions/settings/index.tsx
  frontend/ui/src/components/AiryWebsocket/index.tsx
  frontend/ui/src/cookies/webStore.ts
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/index.tsx
  frontend/ui/src/reducers/data/channels/index.ts
  frontend/ui/src/reducers/data/conversations/index.ts
  frontend/ui/src/reducers/data/index.ts
  frontend/ui/src/reducers/data/settings/index.ts
  frontend/ui/src/selectors/channels.ts
  frontend/ui/src/selectors/conversations.ts
  infrastructure/helm-chart/templates/ingress.yaml
  lib/java/spring/jwt/src/main/java/co/airy/spring/jwt/Jwt.java
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/mappers/channelMapper.ts
  lib/typescript/httpclient/mappers/connectChannelMapper.ts
  lib/typescript/httpclient/mappers/conversationMapper.ts
  lib/typescript/httpclient/mappers/index.ts
  lib/typescript/httpclient/model/Conversation.ts
  lib/typescript/httpclient/payload/ChannelApiPayload.ts
  lib/typescript/httpclient/payload/ChannelPayload.ts
  lib/typescript/httpclient/payload/ChannelsPayload.ts
  lib/typescript/httpclient/payload/index.ts
  lib/typescript/websocketclient/index.ts
  lib/typescript/websocketclient/payload.ts
Labels: feature

#1025 [#1023] Websocket uses tls when the page is loaded via https
  frontend/chat-plugin/src/components/websocket/index.ts
  frontend/ui/src/components/AiryWebsocket/index.tsx
  lib/typescript/websocketclient/index.ts
Labels: fix

#1024 [#957] Add ErrorBoundaries for the RenderLibrary
  lib/typescript/render/index.tsx
Labels: feature

#1026 [#886] Remove deprecated communication websocket
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketConfig.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ContactResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationResponsePayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsTagTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/Stores.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketConfig.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketController.java
  backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java
  backend/model/channel/src/main/java/co/airy/model/channel/ChannelPayload.java
  backend/model/event/src/main/java/co/airy/model/event/payload/ChannelEvent.java
  backend/model/event/src/main/java/co/airy/model/event/payload/MetadataEvent.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataRepository.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/dto/MetadataMap.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
  docs/docs/api/websocket.md
  infrastructure/helm-chart/templates/ingress.yaml
  lib/typescript/websocketclient/index.ts
Labels: chore

#1013 [#999] ButtonBox v3
  docs/src/components/ButtonBox/index.js
  docs/src/components/ButtonBox/styles.module.css
  docs/static/icons/bolt.svg
  docs/static/icons/cloud.svg
  docs/static/icons/deploy.svg
  docs/static/icons/drafting.svg
  docs/static/icons/information-architecture.svg
  docs/static/icons/prototype.svg
  docs/static/icons/server-stack.svg
Labels: docs

#1030 [#1029] Webhook consumer bootstrapping fixed
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/values.yaml
  infrastructure/helm-chart/templates/ingress.yaml
Labels: fix

#1033 [#885] Fix webhook payload
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/RedisQueue.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/payload/QueueMessage.java
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
Labels: fix

#1011 Feature/905 extract avatar and time from message render library
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
  lib/typescript/render/components/MessageInfoWrapper/index.tsx
  lib/typescript/render/components/RichCard/index.tsx
  lib/typescript/render/components/RichText/index.module.scss
  lib/typescript/render/components/RichText/index.tsx
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/components/Text/index.tsx
Labels: feature

#1037 [#954] Extracting svgs from the apps and…
  frontend/assets/images/empty-state/inbox-empty-state.svg
  frontend/assets/images/empty-state/tags-empty-state.svg
  frontend/assets/images/icons/airy-icon.svg
  frontend/assets/images/icons/airy_avatar.svg
  frontend/assets/images/icons/arrow-left-2.svg
  frontend/assets/images/icons/checkmark-circle.svg
  frontend/assets/images/icons/checkmark.svg
  frontend/assets/images/icons/chevron-down.svg
  frontend/assets/images/icons/chevron_left.svg
  frontend/assets/images/icons/close.svg
  frontend/assets/images/icons/cog.svg
  frontend/assets/images/icons/edit.svg
  frontend/assets/images/icons/facebook_rounded.svg
  frontend/assets/images/icons/git-merge.svg
  frontend/assets/images/icons/google-messages.svg
  frontend/assets/images/icons/google_avatar.svg
  frontend/assets/images/icons/inbox.svg
  frontend/assets/images/icons/messenger_avatar.svg
  frontend/assets/images/icons/paperplane.svg
  frontend/assets/images/icons/plus.svg
  frontend/assets/images/icons/price-tag.svg
  frontend/assets/images/icons/search.svg
  frontend/assets/images/icons/shortcut.svg
  frontend/assets/images/icons/sign-out.svg
  frontend/assets/images/icons/sms-icon.svg
  frontend/assets/images/icons/sms_avatar.svg
  frontend/assets/images/icons/speak-bubble.svg
  frontend/assets/images/icons/trash.svg
  frontend/assets/images/icons/whatsapp-icon.svg
  frontend/assets/images/icons/whatsapp_avatar.svg
  frontend/assets/images/logo/airy_primary_rgb.png
  frontend/assets/images/logo/airy_primary_rgb.svg
  frontend/ui/src/components/IconChannel/index.tsx
  frontend/ui/src/components/IconChannelFilter/index.tsx
  frontend/ui/src/components/SearchField.tsx
  frontend/ui/src/components/Sidebar/index.tsx
  frontend/ui/src/components/Tag/index.tsx
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Login/index.tsx
  frontend/ui/src/pages/Tags/EmptyStateTags.tsx
  frontend/ui/src/pages/Tags/TableRow.tsx
  frontend/ui/src/pages/Tags/index.module.scss
  frontend/ui/src/pages/Tags/index.tsx
Labels: chore

#1039 [#1002] Chat Plugin Size
  frontend/chat-plugin/src/App.module.scss
  frontend/chat-plugin/src/components/chat/index.module.scss
Labels: feature

#1057 [#842] Remove ugly border around filter icon
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
Labels: fix

#1053 Ensure that the Facebook token is set on the channel
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
Labels: fix

#1056 [#1017] Introduce the airy create command
  docs/docs/cli/reference.md
  infrastructure/cli/cmd/BUILD
  infrastructure/cli/cmd/create/BUILD
  infrastructure/cli/cmd/create/create.go
  infrastructure/cli/cmd/root.go
  infrastructure/cli/integration/golden/cli.no-args.golden
  infrastructure/cli/integration/golden/cli.yaml
Labels: feature

#1060 [#1038] ChatPlugin does not render RichText
  lib/typescript/render/BUILD
  lib/typescript/render/components/RichText/index.module.scss
  lib/typescript/render/components/RichText/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  package.json
  yarn.lock
Labels: feature

#1058 Update golang deps
  BUILD
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  backend/webhook/redis-worker/go.mod
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/cli/cmd/config/BUILD
  infrastructure/controller/BUILD
  infrastructure/controller/pkg/configmap-controller/BUILD
  infrastructure/lib/go/k8s/handler/BUILD
  infrastructure/lib/go/k8s/util/BUILD
  main.go
  tools/update-deps/BUILD
  tools/update-deps/README.md
  tools/update-deps/go.mod
  tools/update-deps/go.sum
  tools/update-deps/main.go
  tools/update-deps/modules.go
Labels: feature

#1062 Upgrade rules nodejs to 3.1
  WORKSPACE
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/BUILD
  lib/typescript/httpclient/index.ts
  lib/typescript/websocketclient/index.ts
  package.json
  yarn.lock
Labels: chore

#1040 Feature/862 render suggestions google
  frontend/assets/images/icons/link.svg
  frontend/assets/images/icons/phone.svg
  lib/typescript/render/components/Image/index.tsx
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/components/Suggestions/index.module.scss
  lib/typescript/render/providers/google/components/Suggestions/index.tsx
  lib/typescript/render/providers/google/googleModel.ts
  lib/typescript/render/renderProviders.ts
Labels: feature

#1064 [#1063] Fix docs for status command
  docs/docs/getting-started/deployment/vagrant.md
Labels: fix

#1066 [#848] Handle Postback / Suggestion Messages /…
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: feature

#986 [#665] Build UI aspect of channels page
  frontend/assets/images/icons/airy_avatar.svg
  frontend/assets/images/icons/filter-alt.svg
  frontend/assets/images/icons/google_avatar.svg
  frontend/assets/images/icons/messenger_avatar.svg
  frontend/assets/images/icons/placeholder.svg
  frontend/assets/images/icons/plus-circle.svg
  frontend/assets/images/icons/search.svg
  frontend/assets/images/icons/sms-channel.svg
  frontend/assets/images/icons/sms.svg
  frontend/assets/images/icons/sms_avatar.svg
  frontend/assets/images/icons/whatsapp_avatar.svg
  frontend/ui/src/assets/images/icons/add-icon.svg
  frontend/ui/src/assets/images/icons/filter.svg
  frontend/ui/src/assets/images/icons/search-channel-icon.svg
  frontend/ui/src/pages/Channels/ChannelsSources/ChannelDetails.module.scss
  frontend/ui/src/pages/Channels/ChannelsSources/ChannelDetails.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/ChannelsConnected.module.scss
  frontend/ui/src/pages/Channels/ChannelsSources/ChannelsConnected.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/ChatPluginSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/FacebookSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/GoogleSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/TwilloSmsSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/WhatsappSmsSource.tsx
  frontend/ui/src/pages/Channels/index.module.scss
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.module.scss
Labels: feature

#1061 [#932] Add Twilio SMS and Whatsapp to render library
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/render/components/Carousel/index.module.scss
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
  lib/typescript/render/components/MessageInfoWrapper/index.tsx
  lib/typescript/render/providers/twilio/twilioSMS/TwilioSMSRender.tsx
  lib/typescript/render/providers/twilio/twilioSMS/twilioSMSModel.ts
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/twilioWhatsappModel.ts
  lib/typescript/render/renderProviders.ts
Labels: fix

#1065 [#1042] Fixes rendering and sending messaged to Facebook and sending for Google
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/httpclient/payload/SendMessagesRequestPayload.ts
  lib/typescript/render/index.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  tools/update-deps/BUILD
Labels: fix

#1070 fix size chatplugin in example.html
  frontend/chat-plugin/src/defaultScript.tsx
  lib/typescript/render/components/Text/index.module.scss
Labels: fix

#1076 [#814] Add cmd+enter and better disabled state to…
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
Labels: feature

#1069 Add suggest replies endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageSuggestRepliesRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java
  docs/docs/api/endpoints/messages.md
Labels: feature

#1071 [#1068] improve channels UI
  frontend/ui/src/actions/config/index.ts
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceDescription/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceDescription/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/FacebookSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/GoogleSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioSmsSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioWhatsAppSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/index.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/ChannelsConnected.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/ChatPluginSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/FacebookSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/GoogleSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/TwilloSmsSource.tsx
  frontend/ui/src/pages/Channels/ChannelsSources/WhatsappSmsSource.tsx
  frontend/ui/src/pages/Channels/index.module.scss
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/reducers/data/config/index.ts
  frontend/ui/src/reducers/data/index.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/payload/ConfigPayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: fix

#1079 [#1014] Add helm image containing the charts
  WORKSPACE
  backend/api/admin/BUILD
  backend/api/auth/BUILD
  backend/api/communication/BUILD
  backend/api/websocket/BUILD
  backend/media/BUILD
  backend/sources/chat-plugin/BUILD
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/events-router/BUILD
  backend/sources/google/connector/BUILD
  backend/sources/google/events-router/BUILD
  backend/sources/twilio/connector/BUILD
  backend/sources/twilio/events-router/BUILD
  backend/webhook/publisher/BUILD
  backend/webhook/redis-worker/BUILD
  frontend/chat-plugin/BUILD
  frontend/ui/BUILD
  infrastructure/.gitignore
  infrastructure/cli/go.sum
  infrastructure/controller/BUILD
  infrastructure/helm-chart/BUILD
  tools/build/container_push.bzl
  tools/build/container_release.bzl
Labels: feature

#1082 [#1080] Change style of ChatPlugin + fix carousel
  frontend/chat-plugin/src/components/chat/index.module.scss
  lib/typescript/render/components/Carousel/index.module.scss
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
  lib/typescript/render/components/RichCard/Media/index.module.scss
  lib/typescript/render/components/RichCard/index.module.scss
  lib/typescript/render/components/RichCard/index.tsx
Labels: feature

#1077 Add cypress rule
  integration/ui/BUILD
  integration/ui/cypress.json
  integration/ui/login.spec.ts
  integration/ui/tsconfig.json
  package.json
  yarn.lock
Labels: feature

#1089 [#1088] Fix missing Facebook channel disconnect
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/payload/DisconnectChannelRequestPayload.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
Labels: fix

#1074 [#1016] Create topics with k8s job
  infrastructure/helm-chart/charts/prerequisites/templates/kafka.yaml
  infrastructure/helm-chart/charts/prerequisites/values.yaml
  infrastructure/helm-chart/charts/provisioning/Chart.yaml
  infrastructure/helm-chart/charts/provisioning/templates/job-kafka.yaml
  infrastructure/helm-chart/charts/provisioning/templates/kafka-create-topics.yaml
  infrastructure/helm-chart/charts/provisioning/templates/scripts.yaml
  infrastructure/helm-chart/charts/provisioning/values.yaml
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/status.sh
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
  scripts/lint.sh
Labels: feature

#1095 [#1093] Fix image url for Facebook channel connection
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  docs/docs/api/endpoints/channels.md
Labels: fix

#1096 [1092] Merge deployment and installation sections
  docs/docs/apps/ui/quickstart.md
  docs/docs/cli/installation.md
  docs/docs/getting-started/deployment/introduction.md
  docs/docs/getting-started/installation.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/production.md
  docs/docs/getting-started/installation/vagrant.md
  docs/docs/getting-started/quickstart.md
  docs/docs/integrations/rasa.md
  docs/docs/sources/facebook.md
  docs/sidebars.js
Labels: docs

#1091 [#1015] Refactor the scheduling of the components
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-publisher/templates/deployment.yaml
  infrastructure/helm-chart/charts/controller/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/values.yaml
  infrastructure/helm-chart/charts/provisioning/templates/job-kafka.yaml
  infrastructure/helm-chart/charts/provisioning/templates/scripts.yaml
  infrastructure/scripts/provision/create-topics.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
Labels: feature

#1100 [#1099] Add missing allowed origin env
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml
Labels: fix
