Repository airyhq/airy, pull requests merged in 2021-03, with the labels that each got.

#1114 Fix/1104 split endpoints in http library in multiple files
  lib/typescript/httpclient/README.md
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/connectFacebookChannel.ts
  lib/typescript/httpclient/endpoints/createTag.ts
  lib/typescript/httpclient/endpoints/deleteTag.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/exploreFacebookChannels.ts
  lib/typescript/httpclient/endpoints/getConfig.ts
  lib/typescript/httpclient/endpoints/getConversationInfo.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/endpoints/listTags.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/endpoints/readConversations.ts
  lib/typescript/httpclient/endpoints/sendMessages.ts
  lib/typescript/httpclient/endpoints/tagConversation.ts
  lib/typescript/httpclient/endpoints/untagConversation.ts
  lib/typescript/httpclient/endpoints/updateTag.ts
  lib/typescript/httpclient/index.ts
Labels: fix

#1121 [#1120] Fix Shellcheck
  scripts/bootstrap.sh
Labels: fix

#1118 [#1117] Template docs are not accessible
  docs/sidebars.js
Labels: feature

#1125 [#1124] Template endpoints return 404
  infrastructure/helm-chart/templates/ingress.yaml
Labels: bug

#1119 fixed highlight in inbox
  frontend/ui/src/pages/Inbox/Messenger/index.tsx
Labels: fix

#1078 [#660] Enable users to connect via Airy Live Chat
  frontend/assets/images/icons/plus-circle.svg
  frontend/assets/scss/colors.scss
  frontend/ui/index.html
  frontend/ui/nginx.conf
  frontend/ui/src/App.tsx
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/components/IconChannel/index.tsx
  frontend/ui/src/env.ts
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceDescription/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginConnect.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/FacebookSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/GoogleSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioSmsSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioWhatsAppSource.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
  frontend/ui/src/reducers/data/channels/index.ts
  frontend/ui/src/routes/routes.ts
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/connectChatPluginChannel.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/endpoints/updateChannel.ts
  lib/typescript/httpclient/payload/ConnectChatPluginRequestPayload.ts
  lib/typescript/httpclient/payload/UpdateChannelRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
  yarn.lock
Labels: feature

#1128 [#1126] /templates.info And /templates.update are returning 404
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  infrastructure/helm-chart/templates/ingress.yaml
Labels: feature

#1127 [#983] The login call should not send the auth…
  frontend/ui/src/InitializeAiryApi.ts
  frontend/ui/src/actions/user/index.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
Labels: feature

#1131 [#1094] Minor UI improvements to the docs
  docs/docs/api/introduction.md
  docs/docs/apps/ui/introduction.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/production.md
  docs/docs/getting-started/introduction.md
  docs/docs/getting-started/quickstart.md
  docs/src/components/ButtonBox/styles.module.css
  docs/static/icons/desktop-computer.svg
  docs/static/icons/diamond.svg
  docs/static/icons/electric-plug.svg
  docs/static/icons/fishing-pole.svg
  docs/static/icons/gear.svg
  docs/static/icons/hammer-and-wrench.svg
  docs/static/icons/high-voltage.svg
  docs/static/icons/kafka.svg
  docs/static/icons/label.svg
  docs/static/icons/rocket.svg
  docs/static/icons/speech-balloon.svg
Labels: docs

#1129 [#1000] ConversationList scrolls over TopBar
  frontend/ui/src/components/TopBar/index.module.scss
Labels: feature

#1135 Add dependabot config
  .github/dependabot.yml
Labels: chore

#1141 [#1034] Tag empty state has strange scrolling…
  frontend/ui/src/pages/Tags/EmptyStateTags.module.scss
  frontend/ui/src/pages/Tags/EmptyStateTags.tsx
  frontend/ui/src/pages/Tags/index.module.scss
Labels: fix

#1149 [#1142] Backbutton & search aligned
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.module.scss
Labels: fix

#1153 [#1152] Fix conditional config apply
  infrastructure/scripts/provision/core.sh
Labels: fix

#1151 Restructure cli to prepare for providers
  docs/cli-doc/BUILD
  docs/cli-doc/generate_cli_docs.go
  docs/docs/cli/reference.md
  infrastructure/cli/BUILD
  infrastructure/cli/main.go
  infrastructure/cli/pkg/cmd/BUILD
  infrastructure/cli/pkg/cmd/api/BUILD
  infrastructure/cli/pkg/cmd/api/api.go
  infrastructure/cli/pkg/cmd/api/login.go
  infrastructure/cli/pkg/cmd/api/signup.go
  infrastructure/cli/pkg/cmd/config/BUILD
  infrastructure/cli/pkg/cmd/config/config.go
  infrastructure/cli/pkg/cmd/config/configmaps.go
  infrastructure/cli/pkg/cmd/config/parser.go
  infrastructure/cli/pkg/cmd/create/BUILD
  infrastructure/cli/pkg/cmd/create/create.go
  infrastructure/cli/pkg/cmd/create/helm.go
  infrastructure/cli/pkg/cmd/root.go
  infrastructure/cli/pkg/cmd/status/BUILD
  infrastructure/cli/pkg/cmd/status/status.go
  infrastructure/cli/pkg/cmd/ui/BUILD
  infrastructure/cli/pkg/cmd/ui/ui.go
  infrastructure/cli/pkg/providers/BUILD
  infrastructure/cli/pkg/providers/aws/BUILD
  infrastructure/cli/pkg/providers/aws/aws.go
  infrastructure/cli/pkg/providers/minikube/BUILD
  infrastructure/cli/pkg/providers/minikube/minikube.go
  infrastructure/cli/pkg/providers/providers.go
  infrastructure/scripts/provision/core.sh
Labels: chore

#1143 [#1113] Chat Plugin: keep text in input bar if…
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
Labels: feature

#1162 [#1161] Fix metadata 404
  infrastructure/helm-chart/templates/ingress.yaml
Labels: fix

#1159 Restructure cli for building providers
  docs/docs/cli/reference.md
  infrastructure/cli/pkg/cmd/create/BUILD
  infrastructure/cli/pkg/cmd/create/create.go
  infrastructure/cli/pkg/kube/BUILD
  infrastructure/cli/pkg/kube/context.go
  infrastructure/cli/pkg/providers/BUILD
  infrastructure/cli/pkg/providers/aws/BUILD
  infrastructure/cli/pkg/providers/aws/aws.go
  infrastructure/cli/pkg/providers/minikube/BUILD
  infrastructure/cli/pkg/providers/minikube/minikube.go
  infrastructure/cli/pkg/providers/provider.go
  infrastructure/cli/pkg/providers/providers.go
Labels: chore

#1166 [#1165] Fix template endpoint content field
  BUILD
  WORKSPACE
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  docs/docs/api/endpoints/templates.md
Labels: fix

#1177 [#1174] Build the right cli version on develop
  .github/workflows/main.yml
  scripts/push-images.sh
  tools/build/bazel_status.sh
  tools/build/container_release.bzl
Labels: fix

#1181 [#1055] Expired Websocket Connection
  frontend/chat-plugin/src/components/chat/index.module.scss
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/websocket/index.ts
Labels: feature

#1194 [#1101] Filtering by channel not functioning
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
Labels: fix

#1122 [#1022] Change ingress hostnames and deploy traefik ingress controller
  docs/docs/apps/ui/quickstart.md
  docs/docs/cli/reference.md
  docs/docs/getting-started/installation/production.md
  docs/docs/getting-started/installation/vagrant.md
  docs/docs/getting-started/quickstart.md
  docs/docs/integrations/rasa.md
  docs/docs/sources/chatplugin/installation.md
  docs/docs/sources/chatplugin/quickstart.md
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/example.html
  frontend/chat-plugin/src/api/index.tsx
  frontend/chat-plugin/src/defaultScript.tsx
  frontend/chat-plugin/src/websocket/index.ts
  frontend/ui/BUILD
  frontend/ui/README.md
  frontend/ui/index.html
  frontend/ui/src/env.ts
  frontend/ui/src/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginConnect.tsx
  infrastructure/Vagrantfile
  infrastructure/airy.tpl.yaml
  infrastructure/cli/integration/golden/cli.no-args.golden
  infrastructure/cli/pkg/cmd/root.go
  infrastructure/cli/pkg/cmd/ui/ui.go
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/configmap.yaml
  infrastructure/helm-chart/charts/tools/charts/ahkq/templates/ingress.yaml
  infrastructure/helm-chart/templates/configmap.yaml
  infrastructure/helm-chart/templates/ingress-controller.yaml
  infrastructure/helm-chart/templates/ingress-ui.yaml
  infrastructure/helm-chart/templates/ingress.yaml
  infrastructure/helm-chart/values.yaml
  infrastructure/scripts/provision/prerequisites.sh
  infrastructure/scripts/status.sh
  integration/ui/cypress.json
  lib/typescript/httpclient/README.md
  lib/typescript/httpclient/client.ts
  lib/typescript/websocketclient/README.md
  scripts/bootstrap.sh
Labels: feature

#1196 [#1174] Follow up fix to bug introduced by PR #1177
  tools/build/bazel_status.sh
Labels: fix

#1198 [#1174] Follow up of the follow up of the fix
  infrastructure/cli/integration/version_test.go
Labels: fix

#1202 Fix chatplugin build by upgrading bazel-tools
  WORKSPACE
Labels: fix

#1208 [#1204] Add sourceType to templates API
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  backend/avro/communication/template.avsc
  backend/model/template/src/main/java/co/airy/model/template/TemplatePayload.java
  docs/docs/api/endpoints/templates.md
Labels: feature

#1203 Fix chat plugin build by upgrading bazel-tools (#2)
  .prettierignore
  WORKSPACE
  yarn.lock
Labels: fix

#1209 [#1205] Fix update deps command and the gazelle repositories
  WORKSPACE
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  tools/update-deps/main.go
Labels: fix

#1216 [#1214] Duplicate messages in the redux store
  frontend/ui/src/reducers/data/messages/index.ts
Labels: fix

#1207 Chatplugin overview section
  docs/docs/sources/chatplugin/overview.md
Labels: docs

#1224 [#677] add missing ingress definition for suggest replies endpoint
  infrastructure/helm-chart/templates/ingress.yaml
Labels: fix

#1225 [#1217] Make validation work for auth app
  BUILD
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/SignupRequestPayload.java
  backend/api/auth/src/test/java/co/airy/core/api/auth/UsersControllerTest.java
Labels: fix

#1230 [#1228] Scope templates list by source type
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ListTemplatesRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  docs/docs/api/endpoints/templates.md
  docs/docusaurus.config.js
  docs/src/plugins/prism_themes/github.js
Labels: feature

#1231 Fix Golang dependencies, upgrade Gazelle
  WORKSPACE
  backend/webhook/redis-worker/go.mod
  docs/cli-doc/go.mod
  docs/cli-doc/go.sum
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  infrastructure/cli/pkg/cmd/create/BUILD
  infrastructure/cli/pkg/cmd/create/helm.go
  infrastructure/cli/pkg/providers/aws/BUILD
  infrastructure/cli/pkg/providers/aws/aws.go
  infrastructure/cli/pkg/workspace/BUILD
  infrastructure/cli/pkg/workspace/defaults.yaml
  infrastructure/cli/pkg/workspace/files.go
  infrastructure/controller/go.mod
  infrastructure/controller/go.sum
  infrastructure/lib/go/k8s/handler/go.mod
  infrastructure/lib/go/k8s/handler/go.sum
  infrastructure/lib/go/k8s/util/go.mod
  infrastructure/lib/go/k8s/util/go.sum
  lib/go/httpclient/go.mod
  lib/go/httpclient/go.sum
  tools/update-deps/go.mod
  tools/update-deps/go.sum
  tools/update-deps/main.go
Labels: fix

#1233 More readable examples
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chatplugin/quickstart.md
Labels: docs

#1234 [#1197] Rename chat_plugin to chatplugin everywhere
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  docs/docs/api/endpoints/channels.md
  frontend/README.md
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/components/IconChannel/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginSource.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem.tsx
  frontend/ui/src/routes/routes.ts
  lib/java/mapping/src/main/java/co/airy/mapping/ContentMapper.java
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/httpclient/model/Channel.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/render/renderProviders.ts
Labels: chore

#1123 [#868] Templates manager
  frontend/assets/images/empty-state/templates-empty-state.png
  frontend/assets/images/icons/smiley.svg
  frontend/assets/images/icons/template-alt.svg
  frontend/assets/images/not-found/templates-not-found.png
  frontend/ui/src/actions/index.ts
  frontend/ui/src/actions/templates/index.ts
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/TemplateSelector/index.module.scss
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  frontend/ui/src/reducers/data/index.ts
  frontend/ui/src/reducers/data/templates/index.ts
  frontend/ui/src/services/format/date.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/endpoints/listTemplates.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/model/RenderedContent.ts
  lib/typescript/httpclient/model/Template.ts
  lib/typescript/httpclient/model/index.ts
  lib/typescript/httpclient/payload/ListTemplatesPayload.ts
  lib/typescript/httpclient/payload/ListTemplatesRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
  lib/typescript/render/components/Carousel/index.module.scss
  lib/typescript/render/components/Carousel/index.tsx
  lib/typescript/render/components/RichCard/index.module.scss
  lib/typescript/render/components/RichText/index.tsx
  lib/typescript/render/components/index.ts
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/QuickReplies/index.module.scss
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/twilio/twilioSMS/TwilioSMSRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
  lib/typescript/render/shared.ts
Labels: feature

#1199 [#871] Httpclient methods need return value
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/actions/config/index.ts
  frontend/ui/src/actions/templates/index.ts
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/index.tsx
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/connectChatPluginChannel.ts
  lib/typescript/httpclient/endpoints/connectFacebookChannel.ts
  lib/typescript/httpclient/endpoints/createTag.ts
  lib/typescript/httpclient/endpoints/deleteTag.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/exploreFacebookChannels.ts
  lib/typescript/httpclient/endpoints/getConfig.ts
  lib/typescript/httpclient/endpoints/getConversationInfo.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/endpoints/listTags.ts
  lib/typescript/httpclient/endpoints/listTemplates.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/endpoints/readConversations.ts
  lib/typescript/httpclient/endpoints/sendMessages.ts
  lib/typescript/httpclient/endpoints/tagConversation.ts
  lib/typescript/httpclient/endpoints/untagConversation.ts
  lib/typescript/httpclient/endpoints/updateChannel.ts
  lib/typescript/httpclient/endpoints/updateTag.ts
  lib/typescript/httpclient/model/Config.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/model/index.ts
  lib/typescript/httpclient/payload/ChannelPayload.ts
  lib/typescript/httpclient/payload/ChannelsPayload.ts
  lib/typescript/httpclient/payload/ConversationPayload.ts
  lib/typescript/httpclient/payload/DisconnectChannelRequestPayload.ts
  lib/typescript/httpclient/payload/ListTagsResponsePayload.ts
  lib/typescript/httpclient/payload/ListTemplatesPayload.ts
  lib/typescript/httpclient/payload/MessagePayload.ts
  lib/typescript/httpclient/payload/TagPayload.ts
  lib/typescript/httpclient/payload/UserPayload.ts
  lib/typescript/httpclient/payload/index.ts
  lib/typescript/websocketclient/payload.ts
Labels: feature

#1243 [#1241] Fix chatplugin ui path collision
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chatplugin/quickstart.md
  frontend/chat-plugin/BUILD
  infrastructure/helm-chart/templates/ingress-ui.yaml
Labels: fix

#1245 [#1241] Fix chatplugin ui path collision. Follow up fix.
  frontend/chat-plugin/example.html
Labels: fix

#1223 [#656] Enable users to connect via Twilio Sms and Whatsapp
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioSmsConnect.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioSmsConnect.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioSmsSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioWhatsAppSource.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/Sources/TwilioWhatsappConnect.tsx
  frontend/ui/src/pages/Channels/ChannelsMainPage/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem.module.scss
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelsList.tsx
  frontend/ui/src/pages/Channels/Twilio/RequirementsDialog.module.scss
  frontend/ui/src/pages/Channels/Twilio/RequirementsDialog.tsx
  frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.module.scss
  frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
  frontend/ui/src/routes/routes.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/connectTwilioSmsChannel.ts
  lib/typescript/httpclient/endpoints/connectTwilioWhatsappChannel.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/httpclient/model/Channel.ts
  lib/typescript/httpclient/payload/ConnectChannelRequestApiPayload.ts
  lib/typescript/httpclient/payload/ConnectChannelRequestPayload.ts
  lib/typescript/httpclient/payload/ConnectTwilioSmsRequestPayload.ts
  lib/typescript/httpclient/payload/ConnectTwilioWhatsappRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: feature

#1251 fixed templates modal and fixed type template with api change
  frontend/ui/src/pages/Inbox/TemplateSelector/index.module.scss
  lib/typescript/httpclient/model/Template.ts
Labels: fix

#1253 [#1236] Fixed issues with filter by channel
  frontend/ui/src/components/IconChannelFilter/index.tsx
  frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.module.scss
  frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.module.scss
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
Labels: fix

#1248 [#1247] Optional variables for templates creation
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ListTemplatesRequestPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  backend/avro/communication/template.avsc
  backend/model/template/src/main/java/co/airy/model/template/TemplatePayload.java
  docs/docs/api/endpoints/templates.md
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  lib/typescript/httpclient/endpoints/listTemplates.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/model/Template.ts
  lib/typescript/httpclient/payload/ListTemplatesRequestPayload.ts
  lib/typescript/render/providers/facebook/FacebookRender.tsx
Labels: feature

#1256 [#1255] Aligned channelName and channelSourceId
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.module.scss
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem.module.scss
Labels: fix

#1254 [#1090] Add fallback image to channels
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.module.scss
  frontend/ui/src/pages/Channels/ChannelsMainPage/SourceInfo/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem.tsx
  frontend/ui/src/services/image/index.ts
Labels: fix

#1252 [#1050] Add test for filtering and creating a tag
  frontend/ui/handles/index.ts
  frontend/ui/src/components/ColorSelector.tsx
  frontend/ui/src/components/ResizableWindowList/index.tsx
  frontend/ui/src/components/SearchField.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Tags/index.tsx
  integration/chat-plugin/create_conversation.spec.ts
  integration/cypress.json
  integration/ui/create_tag.spec.ts
  integration/ui/filtering.spec.ts
  yarn.lock
Labels: feature

#1273 [#1270] Installation: Toggle broken & Update for…
  docs/docs/cli/installation.md
Labels: feature

#1276 [#1263] Airy Core Components: Move to own page
  docs/docs/getting-started/components.md
  docs/docs/getting-started/introduction.md
  docs/sidebars.js
Labels: docs

#1277 [#1265] Merge cheatsheet from introduction into reference
  docs/docs/cli/installation.md
  docs/docs/cli/introduction.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/vagrant.md
  docs/sidebars.js
Labels: docs

#1288 [#1281] Added RichCard and RichCardCarousel to google
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/googleModel.ts
Labels: feature

#1280 [#968] Improve UI/Inbox docs
  docs/docs/apps/ui/inbox.md
  docs/static/img/apps/ui/FacebookButtonTemplate.png
  docs/static/img/apps/ui/FacebookTemplatePayload.png
  docs/static/img/apps/ui/FilteringInbox.gif
  docs/static/img/apps/ui/GoogleRichCardPayload.png
  docs/static/img/apps/ui/RichCardCarousel.gif
  docs/static/img/apps/ui/RichCardCarouselExample.png
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx
Labels: feature

#1308 [#1264] Prepare config page for the new milestone
  docs/docs/getting-started/installation/configuration.md
  infrastructure/airy.tpl.yaml
Labels: docs

#1311 [#1041] follow up fix: missing quotes in web dev script
  scripts/web-dev.sh
Labels: fix

#1315 [#1314] Have one TLDR
  WORKSPACE
  docs/docs/cli/installation.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/components.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/introduction.md
  docs/docs/sources/chatplugin/installation.md
  docs/docs/sources/chatplugin/overview.md
  maven_install.json
Labels: docs

#1316 API key authentication
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/GetWebhookResponse.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  backend/avro/communication/webhook.avsc
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
  docs/docs/api/authentication.md
  docs/docs/getting-started/installation/configuration.md
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/templates/api.yaml
  infrastructure/helm-chart/charts/apps/charts/api/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
Labels: feature

#1319 Invert icons on darkTheme
  docs/docs/api/introduction.md
  docs/docs/apps/ui/inbox.md
  docs/docs/apps/ui/introduction.md
  docs/docs/apps/ui/quickstart.md
  docs/docs/getting-started/components.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/introduction.md
  docs/docs/getting-started/quickstart.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/sources/chatplugin/overview.md
  docs/docs/sources/chatplugin/quickstart.md
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/introduction.md
  docs/src/components/ButtonBox/index.js
  docs/src/components/ButtonBox/styles.module.css
Labels: chore

#1327 [#1323] Fix minikube command
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#1324 [#677] Render Suggested Replies
  frontend/ui/src/components/ListenOutsideClick/index.tsx
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.module.scss
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  frontend/ui/src/reducers/data/messages/index.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/render/components/Carousel/index.module.scss
Labels: feature

#1329 [#1267] Created generic logo component
  frontend/ui/src/components/SourceLogo/index.module.scss
  frontend/ui/src/components/SourceLogo/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsBySourceCard/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
Labels: feature

#1330 [#1328] Develop version of airy CLI is not…
  .github/workflows/main.yml
Labels: feature

#1331 [#1267] Updated sourceLogo component
  frontend/ui/src/components/ChannelAvatar/index.module.scss
  frontend/ui/src/components/ChannelAvatar/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsBySourceCard/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
Labels: fix

#1334 [#1303] Long messages from contacts shrink the…
  frontend/ui/src/components/AvatarImage/index.module.scss
  lib/typescript/render/components/Avatar/index.module.scss
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
Labels: fix

#1340 [#1298] MessageTextArea in inbox doesn't shrink…
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
Labels: fix

#1341 [#970] Improved ui components docs
  docs/docs/apps/ui/components.md
  docs/static/icons/githubIcon.svg
  docs/static/img/apps/ui/storybookExample.png
Labels: feature

#1346 Fix build
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioConnect.tsx
Labels: chore

#1344 [#1049] Script that executes all integration tests
  integration/BUILD
  integration/cypress.json
Labels: feature

#1349 [#1306] Fix contact metadata problem
  frontend/ui/BUILD
  frontend/ui/src/components/AiryWebsocket/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  lib/typescript/httpclient/endpoints/connectChatPluginChannel.ts
  lib/typescript/httpclient/endpoints/connectFacebookChannel.ts
  lib/typescript/httpclient/endpoints/connectTwilioSmsChannel.ts
  lib/typescript/httpclient/endpoints/connectTwilioWhatsappChannel.ts
  lib/typescript/httpclient/endpoints/exploreFacebookChannels.ts
  lib/typescript/httpclient/endpoints/getConversationInfo.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/updateChannel.ts
  lib/typescript/websocketclient/index.ts
Labels: fix

#1333 [#1312] Add users.list
  backend/api/auth/src/main/java/co/airy/core/api/auth/config/JdbiConfiguration.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/UsersController.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/AcceptInvitationRequestPayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/AcceptInvitationResponsePayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/InviteUserRequestPayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/InviteUserResponsePayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/ListResponsePayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/LoginResponsePayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/UserPayload.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/dao/InvitationDAO.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/dao/UserDAO.java
  backend/api/auth/src/test/java/co/airy/core/api/auth/UsersControllerTest.java
Labels: feature

#1345 [#1325] Move ListenOutsideClick to component lib
  frontend/ui/src/components/ListenOutsideClick/index.tsx
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  yarn.lock
Labels: feature

#1350 [#1097] Allow users to fetch a chat plugin resume token
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Principal.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/Jwt.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/JwtAuthenticationFilter.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/ResumeTokenRequestPayload.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  backend/sources/chat-plugin/src/test/resources/test.properties
  docs/docs/api/authentication.md
  docs/docs/api/endpoints/chatplugin.md
  infrastructure/helm-chart/charts/apps/charts/api/templates/api.yaml
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/Headers.java
Labels: feature

#1358 Update the release process
  docs/docs/concepts/release-process.md
Labels: chore

#1360 [#1318] Improve components page
  docs/docs/apps/ui/introduction.md
  docs/docs/getting-started/components.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/minikube.md
  docs/src/components/Image/index.js
  docs/static/img/getting-started/components-dark.png
  docs/static/img/getting-started/components-light.png
Labels: docs

#1367 Follow up on webpack upgrade
  WORKSPACE
Labels: fix

#1364 [#1326] Move Carousel to components lib
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx
  lib/typescript/render/BUILD
  lib/typescript/render/components/Carousel/index.module.scss
  lib/typescript/render/components/Carousel/index.tsx
  lib/typescript/render/components/RichCardCarousel/index.tsx
  lib/typescript/render/index.tsx
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
  yarn.lock
Labels: feature

#1368 Docs/1355 add debugging advices to all sources
  docs/docs/sources/applyVariables-note.mdx
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/twilio-sources.mdx
  docs/static/img/sources/facebook/facebook_ui.png
Labels: docs

#1375 [#1369] Improved filtering for channels
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
Labels: fix

#1371 [#1097] Fix CORS issue introduced by PR #1350
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/JwtAuthenticationFilter.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java
Labels: fix

#1240 [#1018] Introduce aws provider for airy create
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/production.md
  docs/docs/sources/applyVariables-note.mdx
  docs/sidebars.js
  docs/static/icons/aws.svg
  docs/static/icons/kafka.svg
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  infrastructure/cli/pkg/cmd/create/create.go
  infrastructure/cli/pkg/providers/aws/BUILD
  infrastructure/cli/pkg/providers/aws/aws.go
  infrastructure/cli/pkg/providers/aws/files.go
  infrastructure/cli/pkg/providers/aws/kubeConfigTemplate.yaml
  infrastructure/cli/pkg/providers/aws/rolepolicy.json
  infrastructure/cli/pkg/providers/minikube/minikube.go
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/statefulset.yaml
  infrastructure/helm-chart/values.yaml
Labels: feature

#1398 [#1383] Change size of message bubble
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
Labels: fix

#1401 Move CLI to root
  .github/workflows/main.yml
  cli/BUILD
  cli/go.mod
  cli/go.sum
  cli/integration/BUILD
  cli/integration/api_login_test.go
  cli/integration/golden/BUILD
  cli/integration/golden/cli.login.golden
  cli/integration/golden/cli.no-args.golden
  cli/integration/golden/cli.version.golden
  cli/integration/golden/cli.yaml
  cli/integration/golden/users.signup.golden
  cli/integration/mockserver.go
  cli/integration/noargs_test.go
  cli/integration/runner.go
  cli/integration/test_file.go
  cli/integration/version_test.go
  cli/main.go
  cli/pkg/cmd/BUILD
  cli/pkg/cmd/api/BUILD
  cli/pkg/cmd/api/api.go
  cli/pkg/cmd/api/endpoint.go
  cli/pkg/cmd/api/login.go
  cli/pkg/cmd/api/signup.go
  cli/pkg/cmd/config/BUILD
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/config/configmaps.go
  cli/pkg/cmd/config/parser.go
  cli/pkg/cmd/create/BUILD
  cli/pkg/cmd/create/create.go
  cli/pkg/cmd/create/helm.go
  cli/pkg/cmd/root.go
  cli/pkg/cmd/status/BUILD
  cli/pkg/cmd/status/status.go
  cli/pkg/cmd/ui/BUILD
  cli/pkg/cmd/ui/ui.go
  cli/pkg/console/BUILD
  cli/pkg/console/failure.go
  cli/pkg/console/output.go
  cli/pkg/kube/BUILD
  cli/pkg/kube/context.go
  cli/pkg/kube/hosts.go
  cli/pkg/providers/BUILD
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/aws/files.go
  cli/pkg/providers/aws/kubeConfigTemplate.yaml
  cli/pkg/providers/aws/rolepolicy.json
  cli/pkg/providers/minikube/BUILD
  cli/pkg/providers/minikube/hostsfile.go
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  cli/pkg/workspace/BUILD
  cli/pkg/workspace/defaults.yaml
  cli/pkg/workspace/files.go
  docs/cli-doc/BUILD
  docs/cli-doc/go.mod
  docs/docs/cli/installation.md
  frontend/ui/README.md
  scripts/upload-cli-binaries.sh
Labels: chore

#1402 [#1392] Cypress testing for filtering is false positive
  integration/ui/filter_conversation.spec.ts
Labels: fix

#1412 [#1299] Video Fallback for the render library
  lib/typescript/render/components/Image/index.tsx
  lib/typescript/render/components/ImageWithFallback/index.tsx
  lib/typescript/render/components/RichCard/Media/index.tsx
  lib/typescript/render/components/Video/index.tsx
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
  lib/typescript/render/providers/facebook/components/QuickReplies/index.tsx
  lib/typescript/render/services/fallbackImage.ts
  lib/typescript/render/services/index.ts
Labels: feature

#1425 [#1383] Change size of message bubble
  lib/typescript/render/components/MessageInfoWrapper/index.module.scss
  lib/typescript/render/components/Text/index.module.scss
  package.json
  yarn.lock
Labels: feature

#1385 [#1215] Index metadata
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/dto/MetadataNode.java
Labels: feature

#1421 added intro ui
  docs/docs/ui/introduction.md
  docs/static/icons/comment-bubble.svg
  docs/static/img/ui/FacebookButtonTemplate.png
  docs/static/img/ui/suggested-replies.png
  docs/static/img/ui/tags-ui.png
Labels: docs

#1419 [#1418] Change Cypress hostnames for aws provider
  integration/chat-plugin/create_conversation.spec.ts
  integration/chat-plugin/websocket_test.spec.ts
  integration/cypress.json
  integration/ui/connect_chatplugin.spec.ts
  integration/ui/create_tag.spec.ts
  integration/ui/filter_conversation.spec.ts
  integration/ui/send_chatplugin_message.spec.ts
Labels: feature

#1428 [#1409] Update deps commmunity feedback
  go.mod
  tools/update-deps/README.md
  tools/update-deps/modules.go
Labels: chore

#1424 [#1244] Display lightbulb icon for previous…
  frontend/assets/images/icons/lightbulb.svg
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/render/components/MessageInfoWrapper/index.tsx
Labels: feature

#1436 Fix/1413 expand chat plugin by default
  frontend/chat-plugin/src/components/chat/index.tsx
Labels: fix

#1441 [#925] Fix examples
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chatplugin/quickstart.md
Labels: fix

#1414 Remove Airy init and restructure cli
  .gitignore
  cli/integration/BUILD
  cli/integration/api_login_test.go
  cli/integration/cli_test.go
  cli/integration/golden/BUILD
  cli/integration/golden/cli.no-args.golden
  cli/integration/mockserver.go
  cli/integration/noargs_test.go
  cli/integration/runner.go
  cli/integration/test_file.go
  cli/pkg/cmd/BUILD
  cli/pkg/cmd/config/BUILD
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/config/parser.go
  cli/pkg/cmd/create/create.go
  cli/pkg/cmd/create/helm.go
  cli/pkg/cmd/root.go
  cli/pkg/cmd/status/BUILD
  cli/pkg/cmd/status/status.go
  cli/pkg/console/failure.go
  cli/pkg/console/output.go
  cli/pkg/providers/BUILD
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/BUILD
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  cli/pkg/workspace/BUILD
  cli/pkg/workspace/files.go
  cli/pkg/workspace/init.go
  cli/pkg/workspace/template/airy.yaml
  docs/docs/cli/installation.md
  docs/docs/cli/reference.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/minikube.md
  go.sum
Labels: chore
