Repository airyhq/airy, pull requests merged in 2021-01, with the labels that each got.

#574 [#496] Add audio content model
  lib/java/mapping/src/main/java/co/airy/mapping/model/Audio.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
  lib/java/mapping/src/test/resources/facebook/audio.json
Labels: feature

#534 [#450] Introduce Airy k8s controller
  go_repositories.bzl
  infrastructure/controller/BUILD
  infrastructure/controller/go.mod
  infrastructure/controller/go.sum
  infrastructure/controller/main.go
  infrastructure/controller/pkg/configmap-controller/BUILD
  infrastructure/controller/pkg/configmap-controller/configmap-controller.go
  infrastructure/helm-chart/charts/controller/Chart.yaml
  infrastructure/helm-chart/charts/controller/templates/deployment.yaml
  infrastructure/helm-chart/charts/controller/templates/serviceAccount.yaml
  infrastructure/helm-chart/charts/controller/values.yaml
  infrastructure/lib/go/k8s/handler/BUILD
  infrastructure/lib/go/k8s/handler/callbacks.go
  infrastructure/lib/go/k8s/handler/config.go
  infrastructure/lib/go/k8s/handler/configmaps.go
  infrastructure/lib/go/k8s/handler/containers.go
  infrastructure/lib/go/k8s/handler/deployments.go
  infrastructure/lib/go/k8s/handler/go.mod
  infrastructure/lib/go/k8s/handler/go.sum
  infrastructure/lib/go/k8s/util/BUILD
  infrastructure/lib/go/k8s/util/go.mod
  infrastructure/lib/go/k8s/util/go.sum
  infrastructure/lib/go/k8s/util/util.go
Labels: cli, feature, infrastructure

#577 [#496] Add video content model
  lib/java/mapping/src/main/java/co/airy/mapping/model/Video.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
  lib/java/mapping/src/test/resources/facebook/video.json
Labels: feature

#579 [#496] Add file content model
  lib/java/mapping/src/main/java/co/airy/mapping/model/File.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
  lib/java/mapping/src/test/resources/facebook/file.json
Labels: feature

#580 [#331] Introduce local container push target
  tools/build/container_push.bzl
Labels: chore

#588 Lower case the webhook subdomains
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
Labels: fix

#589 [#587] fix chat plugin development env
  frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/websocket/index.ts
  frontend/chat-plugin/src/defaultScript.tsx
  frontend/chat-plugin/src/iframe.tsx
  frontend/chat-plugin/src/routes/chat/index.tsx
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
Labels: fix

#590 [#526] Rename pg values
  docs/docs/guides/airy-core-in-production.md
  infrastructure/airy.conf.all
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/postgresql.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
Labels: feature

#586 [#327] Introduce a release script that automates the process
  scripts/release.sh
Labels: feature

#583 [#169] Optimize kafka images
  docs/docs/guides/airy-core-in-production.md
  docs/docs/guides/airy-core-in-test-env.md
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/.helmignore
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/NOTES.txt
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/hpa.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/ingress.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/serviceaccount.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/templates/tests/test-connection.yaml
  infrastructure/helm-chart/charts/kafka/charts/cp-kafka/cp-kafka/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/headless-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/nodeport-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/headless-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/values.yaml
  infrastructure/images/kafka/Dockerfile
  infrastructure/images/kafka/Makefile
  infrastructure/images/kafka/config/server.properties
  infrastructure/images/kafka/config/zookeeper.properties
  infrastructure/images/kafka/scripts/configure-kafka.sh
  infrastructure/images/kafka/scripts/configure-zookeeper.sh
  infrastructure/images/kafka/scripts/entrypoint.sh
  infrastructure/scripts/conf.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/provision/create-topics.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
Labels: feature

#596 Use karapace.io schema registry
  infrastructure/airy.conf.all
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/Chart.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/schema-registry/values.yaml
  infrastructure/images/schema-registry/.gitignore
  infrastructure/images/schema-registry/Dockerfile
  infrastructure/images/schema-registry/Makefile
  infrastructure/images/schema-registry/config.json
  infrastructure/images/schema-registry/requirements.txt
  infrastructure/scripts/conf.sh
  infrastructure/scripts/status.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
Labels: feature

#601 [#412] Push only changed images for beta
  .github/workflows/main.yml
  scripts/push-images.sh
  scripts/release.sh
Labels: chore

#604 [#412] Actually pass the branch ref
  .github/workflows/main.yml
  scripts/.gitkeep
  scripts/push-images.sh
Labels: fix

#608 [#412] Use the correct ENV var
  scripts/push-images.sh
Labels: fix

#609 [#412] Always deploy images
  scripts/push-images.sh
Labels: fix

#610 [#335] Provisioning optimization
  infrastructure/airy.conf.all
  infrastructure/airy.conf.tpl
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-connector/templates/deployment.yaml
  infrastructure/scripts/conf.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/provision/prerequisites.sh
  infrastructure/scripts/status.sh
  infrastructure/scripts/trigger/start.sh
  scripts/bootstrap.sh
Labels: feature

#567 [#400] Load messages of conversations
  frontend/demo/src/App.module.scss
  frontend/demo/src/App.tsx
  frontend/demo/src/actions/messages/index.ts
  frontend/demo/src/assets/images/empty-state/inbox-empty-state.svg
  frontend/demo/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/Avatar.scss
  frontend/demo/src/pages/Inbox/Messenger/MessageList/Avatar.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerListItem/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerListItem/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/index.scss
  frontend/demo/src/pages/Inbox/Messenger/index.tsx
  frontend/demo/src/pages/Inbox/index.tsx
  frontend/demo/src/reducers/data/index.ts
  frontend/demo/src/reducers/data/messages/index.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/payload/ListMessagesRequestPayload.ts
  lib/typescript/httpclient/payload/MessagePayload.ts
  lib/typescript/httpclient/payload/index.ts
  package.json
  yarn.lock
Labels: feature, frontend

#615 [#614] Fix release script
  docs/docs/overview/release-process.md
  scripts/release.sh
Labels: feature

#625 [#599] Display avatar + time in messages
  frontend/demo/README.md
  frontend/demo/src/components/AvatarImage/index.module.scss
  frontend/demo/src/components/AvatarImage/index.tsx
  frontend/demo/src/components/Sidebar/index.tsx
  frontend/demo/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/Avatar.scss
  frontend/demo/src/pages/Inbox/Messenger/MessageList/Avatar.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerListItem/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerListItem/index.tsx
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/model/Contact.ts
  lib/typescript/httpclient/model/Conversation.ts
Labels: feature

#645 [#642] Update typescript content typings
  lib/java/mapping/src/ts-generator/java/co/airy/ts_generator/Main.java
  lib/typescript/types/content.ts
Labels: chore

#602 [#497] Upload metadata and message source files
  .gitignore
  .ijwb/.bazelproject
  .ijwb/.idea/fileTemplates/Stream App.java
  WORKSPACE
  backend/media/BUILD
  backend/media/src/main/java/co/airy/core/media/MessageMediaResolver.java
  backend/media/src/main/java/co/airy/core/media/MetadataResolver.java
  backend/media/src/main/java/co/airy/core/media/Stores.java
  backend/media/src/main/java/co/airy/core/media/config/AwsConfig.java
  backend/media/src/main/java/co/airy/core/media/dto/MessageMediaRequest.java
  backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java
  backend/media/src/main/resources/application.properties
  backend/media/src/test/java/co/airy/core/media/MessagesTest.java
  backend/media/src/test/java/co/airy/core/media/MetadataTest.java
  backend/media/src/test/resources/test.properties
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataRepository.java
  backend/sources/twilio/events-router/BUILD
  backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/TwilioInfoExtractor.java
  docs/docs/guides/airy-core-in-production.md
  infrastructure/airy.conf.all
  infrastructure/controller/pkg/configmap-controller/configmap-controller.go
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/user-storage.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/values.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/values.yaml
  infrastructure/scripts/trigger/stop.sh
  lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java
  lib/java/url/BUILD
  lib/java/url/src/main/java/co/airy/url/UrlUtil.java
  maven_install.json
Labels: backend, feature

#603 [#501] Resume conversation in chat plugin
  frontend/chat-plugin/src/components/api/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/websocket/index.ts
Labels: feature

#649 Feat/306 cli config
  BUILD
  infrastructure/cli/BUILD
  infrastructure/cli/cmd/BUILD
  infrastructure/cli/cmd/auth/BUILD
  infrastructure/cli/cmd/auth/auth.go
  infrastructure/cli/cmd/bootstrap/BUILD
  infrastructure/cli/cmd/bootstrap/bootstrap.go
  infrastructure/cli/cmd/config/BUILD
  infrastructure/cli/cmd/config/config.go
  infrastructure/cli/cmd/root.go
  infrastructure/cli/cmd/ui/BUILD
  infrastructure/cli/cmd/ui/ui.go
  infrastructure/cli/cmd/version.go
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  infrastructure/cli/main.go
  infrastructure/cli/main_test.go
  infrastructure/cli/pkg/tests/BUILD
  infrastructure/cli/pkg/tests/golden/BUILD
  infrastructure/cli/pkg/tests/golden/airycli.yaml
  infrastructure/cli/pkg/tests/golden/cli.no-args.golden
  infrastructure/cli/pkg/tests/mockserver.go
  infrastructure/controller/BUILD
  infrastructure/controller/pkg/configmap-controller/BUILD
  infrastructure/lib/go/k8s/handler/BUILD
  infrastructure/lib/go/k8s/util/BUILD
  lib/go/httpclient/BUILD
  lib/go/httpclient/payloads/BUILD
Labels: feature

#657 add mappers to ts http client lib
  lib/typescript/httpclient/endpoints/connectChannel.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/exploreChannels.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/endpoints/listTags.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/mappers/channelMapper.ts
  lib/typescript/httpclient/mappers/channelsMapper.ts
  lib/typescript/httpclient/mappers/connectChannelApiMapper.ts
  lib/typescript/httpclient/mappers/conversationMapper.ts
  lib/typescript/httpclient/mappers/conversationsMapper.ts
  lib/typescript/httpclient/mappers/disconnectChannelApiMapper.ts
  lib/typescript/httpclient/mappers/messageMapper.ts
  lib/typescript/httpclient/mappers/messageMapperData.ts
  lib/typescript/httpclient/mappers/tagsMapper.ts
  lib/typescript/httpclient/mappers/userMapper.ts
Labels: fix

#652 [#651] Use Google Cloud Storage for the bazel remote cache
  .bazelrc
  .github/workflows/main.yml
Labels: chore

#663 Disable go plugin by default since it only works for ultimate users
  .ijwb/.bazelproject
Labels: chore

#664 refactored lib with class that can be instantiated
  frontend/demo/src/AiryConfig.ts
  frontend/demo/src/InitializeAiryApi.ts
  frontend/demo/src/actions/channel/index.ts
  frontend/demo/src/actions/conversations/index.ts
  frontend/demo/src/actions/messages/index.ts
  frontend/demo/src/actions/tags/index.tsx
  frontend/demo/src/actions/user/index.ts
  frontend/demo/src/cookies/cookie.ts
  frontend/demo/src/cookies/index.ts
  frontend/demo/src/cookies/webStore.ts
  frontend/demo/src/pages/Channels/index.tsx
  frontend/demo/src/reducers/data/user/index.ts
  frontend/demo/src/reducers/index.ts
  lib/typescript/httpclient/README.md
  lib/typescript/httpclient/api/airyConfig.ts
  lib/typescript/httpclient/endpoints/connectChannel.ts
  lib/typescript/httpclient/endpoints/createTag.ts
  lib/typescript/httpclient/endpoints/deleteTag.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/exploreChannels.ts
  lib/typescript/httpclient/endpoints/index.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listConversations.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/endpoints/listTags.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/endpoints/readConversations.ts
  lib/typescript/httpclient/endpoints/updateTag.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/payload/PaginatedPayload.ts
Labels: fix

#666 Remove .bazelproject from vcs
  .gitignore
  .ijwb/.bazelproject
Labels: chore

#648 [#646] Configurable ingress hostnames
  docs/docs/guides/airy-core-in-production.md
  infrastructure/helm-chart/charts/ingress/Chart.yaml
  infrastructure/helm-chart/charts/ingress/templates/ingress.yaml
  infrastructure/helm-chart/charts/ingress/values.yaml
  infrastructure/scripts/conf.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/status.sh
Labels: feature

#668 Introduce /client.config
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ClientConfigResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ServiceDiscovery.java
  backend/api/admin/src/main/resources/application.properties
  backend/api/admin/src/test/java/co/airy/core/api/admin/ClientConfigControllerTest.java
  backend/api/admin/src/test/resources/test.properties
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/google/connector/BUILD
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/BUILD
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
  infrastructure/cli/cmd/root.go
  infrastructure/helm-chart/charts/apps/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/ingress/templates/ingress.yaml
Labels: feature

#672 Endpoints should return {} instead of nothing
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
Labels: fix

#674 [#421] Consider service disabled if any exception occurs
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
Labels: fix

#647 [#621] Controller starts/stops apps based on config map changes
  infrastructure/controller/BUILD
  infrastructure/controller/main.go
  infrastructure/controller/pkg/configmap-controller/BUILD
  infrastructure/controller/pkg/configmap-controller/configmap-controller.go
  infrastructure/controller/pkg/configmap-controller/controller.go
  infrastructure/controller/pkg/configmap-controller/create.go
  infrastructure/controller/pkg/configmap-controller/delete.go
  infrastructure/controller/pkg/configmap-controller/update.go
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/frontend.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-demo/templates/deployment.yaml
  infrastructure/lib/go/k8s/handler/configmaps.go
  infrastructure/lib/go/k8s/handler/containers.go
  infrastructure/lib/go/k8s/handler/deployments.go
Labels: feature

#669 [#308] Upload cli binaries to S3
  .github/release-drafter.yml
  .github/workflows/main.yml
  infrastructure/cli/BUILD
Labels: feature

#673 [#620] Download kubeconf file
  infrastructure/cli/cmd/root.go
  infrastructure/cli/pkg/tests/golden/cli.no-args.golden
  scripts/bootstrap.sh
Labels: feature

#676 [#641] Add content type for source templates
  lib/java/mapping/src/main/java/co/airy/mapping/model/Content.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/SourceTemplate.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/resources/facebook/template_generic.json
Labels: feature

#680 [#640] Enrich send message API with source template messages
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/SendMessageRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsInfoTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsTagTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/Topics.java
  docs/docs/api/http.md
  lib/java/mapping/src/main/java/co/airy/mapping/model/SourceTemplate.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/typescript/types/content.ts
Labels: feature

#682 [#402] Tag conversations
  frontend/demo/src/App.tsx
  frontend/demo/src/actions/conversations/index.ts
  frontend/demo/src/actions/tags/index.tsx
  frontend/demo/src/components/ColorSelector.tsx
  frontend/demo/src/components/Tag/index.module.scss
  frontend/demo/src/components/Tag/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/index.tsx
  frontend/demo/src/pages/Tags/FAKESETTINGS.ts
  frontend/demo/src/pages/Tags/SimpleTagForm.tsx
  frontend/demo/src/pages/Tags/TableRow.tsx
  frontend/demo/src/pages/Tags/index.tsx
  frontend/demo/src/reducers/data/conversations/index.ts
  frontend/demo/src/reducers/data/settings/index.ts
  frontend/demo/src/types/tag.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/payload/TagConversationRequestPayload.ts
  lib/typescript/httpclient/payload/UntagConversationRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
  yarn.lock
Labels: feature

#684 [#678] Update VERSION file after release
  VERSION
  scripts/release.sh
Labels: fix

#686 Introduce status command
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientControllerConfig.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ServiceDiscovery.java
  backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java
  infrastructure/cli/cmd/BUILD
  infrastructure/cli/cmd/api/BUILD
  infrastructure/cli/cmd/api/api.go
  infrastructure/cli/cmd/api/login.go
  infrastructure/cli/cmd/api/signup.go
  infrastructure/cli/cmd/auth/auth.go
  infrastructure/cli/cmd/root.go
  infrastructure/cli/cmd/status/BUILD
  infrastructure/cli/cmd/status/status.go
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  infrastructure/cli/main_test.go
  infrastructure/cli/pkg/tests/golden.go
  infrastructure/cli/pkg/tests/golden/BUILD
  infrastructure/cli/pkg/tests/golden/airycli.yaml
  infrastructure/cli/pkg/tests/golden/cli.auth.golden
  infrastructure/cli/pkg/tests/golden/cli.login.golden
  infrastructure/cli/pkg/tests/golden/cli.no-args.golden
  infrastructure/cli/pkg/tests/golden/cli.yaml
  lib/go/httpclient/BUILD
  lib/go/httpclient/client.go
  lib/go/httpclient/http-client-test/users_test.go
  lib/go/httpclient/httpclient.go
  lib/go/httpclient/payloads/BUILD
  lib/go/httpclient/payloads/client_config_request_payload.go
  lib/go/httpclient/payloads/client_config_response_payload.go
  lib/go/httpclient/payloads/login_request_payload.go
  lib/go/httpclient/payloads/login_response_payload.go
  lib/go/httpclient/payloads/signup_request_payload.go
  lib/go/httpclient/payloads/signup_response_payload.go
  lib/go/httpclient/users.go
Labels: feature

#689 Add missing docs for authenticating with the websocket
  docs/docs/api/http.md
  docs/docs/api/websocket.md
Labels: chore

#688 [#622] Affect only deployments with a particular…
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/controller/templates/deployment.yaml
Labels: feature

#690 [#667] Support Google suggestion responses
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventInfo.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/InfoExtractor.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  docs/docs/api/webhook.md
  lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java
  lib/java/mapping/src/test/resources/google/suggestionResponse.json
  lib/java/mapping/src/test/resources/google/text.json
Labels: feature

#683 [#644] Facebook connector sends out templates
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
  backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Api.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Mapper.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/model/SendMessagePayload.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java
  backend/sources/google/connector/BUILD
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/services/Mapper.java
  backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/src/components/api/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/websocket/index.ts
  frontend/demo/BUILD
  lib/java/mapping/src/main/java/co/airy/mapping/OutboundMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java
  lib/typescript/types/BUILD
  lib/typescript/types/global.d.ts
  lib/typescript/types/index.ts
  tsconfig.json
Labels: feature

#655 [#620] Reload configuration based on config file
  infrastructure/cli/cmd/config/BUILD
  infrastructure/cli/cmd/config/config.go
  infrastructure/cli/cmd/config/configmaps.go
  infrastructure/cli/cmd/config/parser.go
  infrastructure/cli/cmd/root.go
  infrastructure/cli/go.mod
  infrastructure/cli/go.sum
  infrastructure/cli/main_test.go
  infrastructure/cli/pkg/tests/golden/airycli.yaml
  infrastructure/cli/pkg/tests/golden/cli.no-args.golden
Labels: feature

#696 [#693] Simplify display name contact API response
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ContactResponsePayload.java
  docs/docs/api/http.md
  frontend/demo/src/reducers/data/conversations/index.ts
  lib/typescript/httpclient/mappers/conversationMapper.ts
  lib/typescript/httpclient/model/Contact.ts
  lib/typescript/httpclient/payload/ConversationPayload.ts
Labels: chore

#697 [#695] Fix yq version incompatibility
  infrastructure/scripts/provision/core.sh
Labels: fix

#694 Reorganize integration tests
  infrastructure/cli/BUILD
  infrastructure/cli/integration/BUILD
  infrastructure/cli/integration/api_login_test.go
  infrastructure/cli/integration/golden/BUILD
  infrastructure/cli/integration/golden/cli.login.golden
  infrastructure/cli/integration/golden/cli.no-args.golden
  infrastructure/cli/integration/golden/cli.version.golden
  infrastructure/cli/integration/golden/cli.yaml
  infrastructure/cli/integration/golden/users.signup.golden
  infrastructure/cli/integration/mockserver.go
  infrastructure/cli/integration/noargs_test.go
  infrastructure/cli/integration/test_file.go
  infrastructure/cli/integration/version_test.go
  infrastructure/cli/main_test.go
  infrastructure/cli/pkg/tests/BUILD
  infrastructure/cli/pkg/tests/mockserver.go
  lib/go/httpclient/BUILD
  lib/go/httpclient/http-client-test/BUILD
  lib/go/httpclient/users_test.go
Labels: chore

#705 [#704] Update websocket documentation
  docs/docs/api/websocket.md
Labels: feature

#700 Update README.md
  README.md
Labels: docs

#709 Fix typo in readme
  README.md
Labels: chore

#714 [#713] Fix bug on tags list
  frontend/demo/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
Labels: fix

#715 Paginate messages for real :)
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
Labels: fix

#712 [#698] Provide endpoint configuration to the frontend
  WORKSPACE
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/development.html
  frontend/chat-plugin/example.html
  frontend/chat-plugin/nginx.conf
  frontend/demo/index.html
  frontend/demo/nginx.conf
  frontend/demo/src/InitializeAiryApi.ts
  frontend/demo/src/env.ts
  infrastructure/airy.tpl.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/api.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/frontend.yaml
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-demo/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/ingress/templates/configmap.yaml
  infrastructure/images/nginx/Dockerfile
  infrastructure/images/nginx/Makefile
Labels: feature

#717 Rm extra bracket
  frontend/demo/index.html
Labels: fix

#721 [#698] Use host config coming from the env
  frontend/demo/index.html
  frontend/demo/src/InitializeAiryApi.ts
  frontend/demo/src/env.ts
Labels: fix

#724 [#711] Add CI status badge
  README.md
Labels: chore

#725 Fix infinite recursion in chatplugin nginx location capture
  frontend/chat-plugin/nginx.conf
Labels: fix

#726 Improve config tests and introduce integration tests runner func
  infrastructure/cli/cmd/config/config.go
  infrastructure/cli/integration/BUILD
  infrastructure/cli/integration/api_login_test.go
  infrastructure/cli/integration/golden/cli.no-args.golden
  infrastructure/cli/integration/noargs_test.go
  infrastructure/cli/integration/runner.go
  infrastructure/cli/integration/version_test.go
Labels: chore

#702 Remove suppression
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
Labels: chore

#728 Return messages last to first so pagination makes sense
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/MessagesTreeSet.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  docs/docs/guides/airy-core-in-test-env.md
  docs/docs/index.md
  docs/docs/sources/chat-plugin.md
Labels: fix

#730 Fix numeric range queries
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/ExtendedQueryParser.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
Labels: fix

#719 [#623] Optional apps depend on config file
  docs/docs/guides/airy-core-in-production.md
  docs/docs/guides/airy-core-in-test-env.md
  docs/docs/index.md
  docs/docs/overview/architecture.md
  docs/docs/overview/release-process.md
  infrastructure/Vagrantfile
  infrastructure/airy.tpl.yaml
  infrastructure/cli/cmd/config/config.go
  infrastructure/cli/cmd/config/configmaps.go
  infrastructure/cli/cmd/config/parser.go
  infrastructure/helm-chart/charts/apps/charts/airy-config/templates/sources.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend-demo/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources-twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook-publisher/templates/deployment.yaml
  infrastructure/scripts/conf.sh
  infrastructure/scripts/provision/core.sh
  infrastructure/scripts/trigger/start.sh
  infrastructure/scripts/trigger/stop.sh
Labels: feature

#732 [#623] Fix manifest for the chatpluign
  infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
Labels: fix

#736 [#623] Fix Google safile sample config
  infrastructure/airy.tpl.yaml
Labels: fix

#747 Upgrade viper
  go_repositories.bzl
Labels: fix

#753 [#654] Replace scss files with scss modules
  frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx
  frontend/demo/src/components/IconChannel/index.module.scss
  frontend/demo/src/components/IconChannel/index.tsx
  frontend/demo/src/components/SearchField.tsx
  frontend/demo/src/components/index.module.scss
  frontend/demo/src/pages/Inbox/ConversationList/index.module.scss
  frontend/demo/src/pages/Inbox/ConversationList/index.tsx
Labels: fix

#760 [#691] Support tag_ids filter queries
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java
Labels: feature

#758 [#731] Doc revamp
  README.md
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  docs/docs/api/http/endpoints.md
  docs/docs/api/http/introduction.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/apps/ui.md
  docs/docs/concepts/architecture.md
  docs/docs/concepts/design-principles.md
  docs/docs/concepts/kafka.md
  docs/docs/concepts/release-process.md
  docs/docs/getting-started/cli.md
  docs/docs/getting-started/deployment/prod-environment.md
  docs/docs/getting-started/deployment/test-environment.md
  docs/docs/getting-started/glossary.md
  docs/docs/getting-started/installation.md
  docs/docs/getting-started/introduction/index.md
  docs/docs/getting-started/quickstart.md
  docs/docs/getting-started/troubleshooting.md
  docs/docs/index.md
  docs/docs/integrations/airy-core-and-rasa.md
  docs/docs/sources/chat-plugin.md
  docs/docs/sources/facebook.md
  docs/sidebars.js
  frontend/demo/README.md
Labels: docs

#748 Resolving source media without typed mapping
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/MessageContainer.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/MessagesTreeSet.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
Labels: feature

#766 Untrack .ijwb since it makes importing the project more difficult
  .gitignore
  .ijwb/.idea/fileTemplates/Stream App.java
Labels: chore

#720 Feat/611 infinite scroll for conversations list and messages
  frontend/demo/src/actions/conversations/index.ts
  frontend/demo/src/actions/messages/index.ts
  frontend/demo/src/pages/Inbox/ConversationList/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerListItem/index.tsx
  frontend/demo/src/reducers/data/conversations/index.ts
  frontend/demo/src/reducers/data/messages/index.ts
  lib/typescript/httpclient/payload/ResponseMetadataPayload.ts
Labels: feature

#759 fixed read conversation when it is active
  frontend/demo/src/pages/Inbox/ConversationListItem/index.tsx
Labels: fix

#768 [#742] Chatplugin example page crashes when…
  frontend/chat-plugin/src/defaultScript.tsx
Labels: feature

#769 [#752] airy version command should work without loading the config
  .bazelrc
  VERSION
  infrastructure/cli/BUILD
  infrastructure/cli/cmd/root.go
  infrastructure/cli/integration/golden/cli.yaml
  infrastructure/cli/integration/runner.go
  infrastructure/cli/integration/version_test.go
  lib/java/mapping/BUILD
  scripts/release.sh
Labels: feature

#771 [#491] Do not show the edit button for docs
  docs/docusaurus.config.js
Labels: docs

#776 [#774] Better favicon
  docs/static/img/favicon.ico
Labels: docs

#777 [#775] Add ga config
  docs/docusaurus.config.js
Labels: docs

#779 [#778] Fix display of messages in Chat Plugin
  frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  lib/typescript/types/content.ts
Labels: fix

#781 [#765] Restructure API docs
  docs/docs/api/authentication.md
  docs/docs/api/endpoints/channels.md
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/introduction.md
  docs/docs/api/endpoints/messages.md
  docs/docs/api/endpoints/metadata.md
  docs/docs/api/endpoints/tags.md
  docs/docs/api/endpoints/users.md
  docs/docs/api/http/endpoints.md
  docs/docs/api/introduction.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chat-plugin.md
  docs/sidebars.js
Labels: docs

#755 [#401] Implement input bar, write & send message functionality
  frontend/demo/src/actions/messages/index.ts
  frontend/demo/src/assets/images/icons/paperplane.svg
  frontend/demo/src/pages/Inbox/MessageInput/index.module.scss
  frontend/demo/src/pages/Inbox/MessageInput/index.tsx
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/demo/src/reducers/data/messages/index.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/messagesForChannels/index.ts
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/httpclient/payload/SendMessagesRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: feature

#789 [#788] Import StateModel instead of RootState
  frontend/demo/src/pages/Inbox/MessageInput/index.tsx
Labels: fix
