Repository airyhq/airy, pull requests merged in 2021-04, with the labels that each got.

#1426 [#1403] CLI Docs Revamp
  .prettierignore
  docs/cli-doc/generate_cli_docs.go
  docs/docs/cli/introduction.md
  docs/docs/cli/usage.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/configuration.md
  docs/docs/getting-started/installation/introduction.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/introduction.md
  docs/docs/ui/quickstart.md
  docs/sidebars.js
  scripts/lint.sh
Labels: docs

#1442 [#1304] Wait for core components during create
  infrastructure/helm-chart/charts/provisioning/templates/job-wait.yaml
Labels: fix

#1449 [#1439] Update release process with hotfix doc
  docs/docs/concepts/release-process.md
Labels: docs

#1448 [#1293] Add Prometheus doc
  docs/docs/guides/operations.md
  infrastructure/tools/prometheus/values.yaml
Labels: feature

#1463 [#1455] Configure lucene so queries are case insensitive
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/AiryAnalyzer.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
Labels: fix

#1454 [#1452] Show tags in contact info column
  frontend/ui/src/components/AiryWebsocket/index.tsx
Labels: fix

#1420 [#1384] Add more types suggested replies
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.module.scss
  frontend/ui/src/services/types/messageTypes.ts
  lib/typescript/httpclient/model/Message.ts
Labels: feature

#1444 added intro to sources
  docs/docs/sources/introduction.md
Labels: docs

#1440 Docs/1406 live chat docs quickstart
  docs/docs/sources/chatplugin/quickstart.md
  docs/static/img/sources/chatplugin/chatplugin-channel-connected.png
  docs/static/img/sources/chatplugin/chatplugin-channel-list.png
  docs/static/img/sources/chatplugin/chatplugin-channel.png
  docs/static/img/sources/chatplugin/chatplugin-connect-form.png
  docs/static/img/sources/chatplugin/chatplugin-connect.png
  docs/static/img/sources/chatplugin/chatplugin-conversations.png
  docs/static/img/sources/chatplugin/chatplugin-id.png
Labels: docs

#1445 [#1422] Add section for kubectl
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#1467 [#1466] Prepare the codebase for lib extraction
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/messagesForChannels/text/index.ts
  lib/typescript/httpclient/model/AiryRequestConfig.ts
  lib/typescript/httpclient/model/Channel.ts
  lib/typescript/httpclient/model/ConversationFilter.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/httpclient/model/Source.ts
  lib/typescript/httpclient/model/Template.ts
  lib/typescript/httpclient/model/index.ts
  lib/typescript/httpclient/payload/ConnectChannelRequestApiPayload.ts
  lib/typescript/httpclient/payload/DisconnectChannelRequestApiPayload.ts
  lib/typescript/httpclient/payload/ListTemplatesRequestPayload.ts
  lib/typescript/httpclient/payload/index.ts
Labels: chore

#1377 Readme - now with nice graph-ical improvements
  README.md
Labels: chore

#1468 [#1164] Document and improve message upsert endpoint
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  docs/docs/api/endpoints/metadata.md
  docs/docs/concepts/metadata.md
  docs/docs/getting-started/glossary.md
  docs/sidebars.js
Labels: chore

#1443 [#1310] Airy CLI sha changes after the release
  .github/workflows/main.yml
  docs/docs/concepts/release-process.md
  scripts/upload-cli-binaries.sh
Labels: fix

#1470 [#1262] Revamp the introduction
  README.md
  docs/docs/getting-started/introduction.md
  docs/static/img/getting-started/introduction-dark.png
  docs/static/img/getting-started/introduction-light.png
Labels: docs

#1458 [#572] Simplify senderType
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java
  backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java
  backend/avro/communication/message.avsc
  backend/media/src/test/java/co/airy/core/media/MessagesTest.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java
  backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
  backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/EventsRouter.java
  backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
  docs/docs/getting-started/glossary.md
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  lib/java/mapping/src/main/java/co/airy/mapping/ContentMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java
  lib/typescript/httpclient/model/Content.ts
  lib/typescript/httpclient/model/Message.ts
  lib/typescript/websocketclient/payload.ts
Labels: feature

#1475 added showmode flag that blocks functionality in chat plugin
  frontend/chat-plugin/src/App.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
Labels: feature

#1485 [#1476] Remove components
  docs/docs/ui/components.md
  docs/docs/ui/introduction.md
  docs/sidebars.js
  docs/static/icons/information-architecture.svg
  docs/static/img/ui/storybookExample.png
Labels: chore

#1490 [#572] Cleanup senderType code
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
Labels: feature

#1493 [#1466] Follow up on extract model
  lib/typescript/model/Message.ts
  lib/typescript/model/SuggestedReply.ts
  lib/typescript/model/User.ts
  lib/typescript/model/index.ts
Labels: chore

#1501 [#1473] Make release process more quiet
  docs/docs/changelog.md
  docs/docs/concepts/release-process.md
  scripts/release.sh
Labels: feature

#1487 [#1422] AWS Docs Revamp
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/minikube.md
  docs/docs/getting-started/introduction.md
Labels: feature

#1457 Fix/1438 fix logout when a user sends a message to a conversation from a disconnected channel
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.module.scss
Labels: fix

#1496 [#1408]Add missing tag gifs
  docs/docs/ui/tags.md
  docs/static/img/ui/create_tags.gif
  docs/static/img/ui/delete_tags.gif
  docs/static/img/ui/edit_tags.gif
Labels: docs

#1479 [#1290] Prometheus Metrics about Spring apps
  WORKSPACE
  docs/docs/guides/operations.md
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/chatplugin/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-publisher/templates/service.yaml
  infrastructure/tools/prometheus/values.yaml
  lib/java/spring/core/BUILD
  lib/java/spring/core/src/main/resources/default.properties
  maven_install.json
Labels: feature

#1494 [#1110] Add basic and advance customization to chatplugin docs
  docs/docs/sources/chatplugin/customization.md
  docs/static/img/sources/chatplugin/basicCustomizationChatpluginExample.png
  docs/static/img/sources/chatplugin/channelEditChatplugin.png
  docs/static/img/sources/chatplugin/channelListChatplugin.png
  docs/static/img/sources/chatplugin/customizedStyleChatplugin.png
  docs/static/img/sources/chatplugin/defaultStyleChatplugin.png
Labels: feature

#1509 Remove empty payloads
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/TagsController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTagResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TagsControllerTest.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/UsersController.java
  backend/api/auth/src/test/java/co/airy/core/api/auth/UsersControllerTest.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsTagTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/WebhookController.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/RedisQueue.java
  docs/docs/api/endpoints/chatplugin.md
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/tags.md
  docs/docs/getting-started/quickstart.md
  docs/docs/sources/chatplugin/quickstart.md
  lib/java/spring/web/src/main/java/co/airy/spring/web/payload/EmptyResponsePayload.java
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/endpoints/connectChatPluginChannel.ts
  lib/typescript/httpclient/endpoints/createTag.ts
  lib/typescript/httpclient/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/endpoints/exploreFacebookChannels.ts
  lib/typescript/httpclient/endpoints/getConfig.ts
  lib/typescript/httpclient/endpoints/listChannels.ts
  lib/typescript/httpclient/endpoints/listMessages.ts
  lib/typescript/httpclient/endpoints/listTags.ts
  lib/typescript/httpclient/endpoints/listTemplates.ts
  lib/typescript/httpclient/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/endpoints/readConversations.ts
  lib/typescript/httpclient/endpoints/tagConversation.ts
  lib/typescript/httpclient/endpoints/untagConversation.ts
  lib/typescript/httpclient/endpoints/updateTag.ts
Labels: chore

#1508 [#929]Implement the option to end chat
  frontend/assets/images/icons/minimize-button.svg
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/src/components/chat/index.module.scss
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/modal/index.module.scss
  frontend/chat-plugin/src/components/modal/index.tsx
  frontend/chat-plugin/src/components/newConversation/index.module.scss
  frontend/chat-plugin/src/components/newConversation/index.tsx
  frontend/chat-plugin/src/config.ts
  frontend/chat-plugin/src/defaultScript.tsx
Labels: feature

#1534 [#1532] Remove step 4 of airy cli installation docs
  docs/docs/cli/introduction.md
Labels: docs

#1538 [#1535] Release version uses correct app image tag
  cli/pkg/cmd/create/helm.go
  cli/pkg/workspace/template/airy.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/values.yaml
  infrastructure/helm-chart/values.yaml
Labels: fix

#1510 [#740] Label and introspect components
  infrastructure/helm-chart/charts/apps/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/values.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/values.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-chat-plugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-chat-plugin/values.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/frontend/charts/frontend-ui/values.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/templates/services.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/values.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/media-resolver/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/chatplugin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/chatplugin/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-events-router/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-events-router/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-events-router/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-events-router/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-events-router/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-events-router/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-events-router/values.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/values.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/templates/service.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-consumer/values.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-publisher/Chart.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-publisher/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/webhook/charts/webhook-publisher/values.yaml
Labels: feature

#1542 [#1540] Added return to messageBubble
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/render/components/Text/index.module.scss
Labels: fix

#1546 [#740] - Adding k8s endpoint to airy controller
  infrastructure/controller/BUILD
  infrastructure/controller/main.go
  infrastructure/controller/pkg/endpoints/BUILD
  infrastructure/controller/pkg/endpoints/endpoints.go
  infrastructure/helm-chart/charts/controller/templates/service.yaml
Labels: feature

#1543 [#1503] Cypress test to end a conversation in chatplugin
  frontend/chat-plugin/handles/index.ts
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/newConversation/index.tsx
  integration/chat-plugin/end_conversation.spec.ts
  integration/chat-plugin/websocket_test.spec.ts
  integration/cypress.json
  integration/ui/send_chatplugin_message.spec.ts
Labels: feature

#1556 fixed template button
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  lib/typescript/assets/images/icons/template-alt.svg
Labels: fix

#1548 [#1399] Add Rasa suggested reply guide
  backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/dto/MetadataNode.java
  docs/docs/api/endpoints/chatplugin.md
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/google-messages-send.mdx
  docs/docs/api/endpoints/messages-send.mdx
  docs/docs/api/endpoints/messages.md
  docs/docs/api/endpoints/suggest-replies.mdx
  docs/docs/api/event-payloads.mdx
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/getting-started/components.md
  docs/docs/guides/operations.md
  docs/docs/integrations/rasa-assistant.md
  docs/docs/integrations/rasa-suggested-replies.md
  docs/docs/ui/suggestedReplies.md
  docs/sidebars.js
  docs/static/img/integrations/rasa/suggested-replies.gif
Labels: docs

#1411 Fix/635 deployment of the library to npm
  .github/workflows/main.yml
  BUILD
  lib/typescript/httpclient/BUILD
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/index.ts
  lib/typescript/httpclient/package.json
  lib/typescript/httpclient/src/endpoints/connectChatPluginChannel.ts
  lib/typescript/httpclient/src/endpoints/connectFacebookChannel.ts
  lib/typescript/httpclient/src/endpoints/connectTwilioSmsChannel.ts
  lib/typescript/httpclient/src/endpoints/connectTwilioWhatsappChannel.ts
  lib/typescript/httpclient/src/endpoints/createTag.ts
  lib/typescript/httpclient/src/endpoints/deleteTag.ts
  lib/typescript/httpclient/src/endpoints/disconnectChannel.ts
  lib/typescript/httpclient/src/endpoints/exploreFacebookChannels.ts
  lib/typescript/httpclient/src/endpoints/getConfig.ts
  lib/typescript/httpclient/src/endpoints/getConversationInfo.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/endpoints/listChannels.ts
  lib/typescript/httpclient/src/endpoints/listConversations.ts
  lib/typescript/httpclient/src/endpoints/listMessages.ts
  lib/typescript/httpclient/src/endpoints/listTags.ts
  lib/typescript/httpclient/src/endpoints/listTemplates.ts
  lib/typescript/httpclient/src/endpoints/loginViaEmail.ts
  lib/typescript/httpclient/src/endpoints/readConversations.ts
  lib/typescript/httpclient/src/endpoints/sendMessages.ts
  lib/typescript/httpclient/src/endpoints/tagConversation.ts
  lib/typescript/httpclient/src/endpoints/untagConversation.ts
  lib/typescript/httpclient/src/endpoints/updateChannel.ts
  lib/typescript/httpclient/src/endpoints/updateTag.ts
  lib/typescript/httpclient/src/index.ts
  lib/typescript/httpclient/src/messagesForChannels/index.ts
  lib/typescript/httpclient/src/messagesForChannels/text/index.ts
  lib/typescript/httpclient/src/payload/ConnectChannelFacebookRequestPayload.ts
  lib/typescript/httpclient/src/payload/ConnectChannelRequestPayload.ts
  lib/typescript/httpclient/src/payload/ConnectChatPluginRequestPayload.ts
  lib/typescript/httpclient/src/payload/ConnectTwilioSmsRequestPayload.ts
  lib/typescript/httpclient/src/payload/ConnectTwilioWhatsappRequestPayload.ts
  lib/typescript/httpclient/src/payload/CreateTagRequestPayload.ts
  lib/typescript/httpclient/src/payload/DisconnectChannelRequestPayload.ts
  lib/typescript/httpclient/src/payload/ExploreChannelRequestPayload.ts
  lib/typescript/httpclient/src/payload/ListConversationsRequestPayload.ts
  lib/typescript/httpclient/src/payload/ListMessagesRequestPayload.ts
  lib/typescript/httpclient/src/payload/ListTemplatesRequestPayload.ts
  lib/typescript/httpclient/src/payload/LoginViaEmailRequestPayload.ts
  lib/typescript/httpclient/src/payload/PaginatedPayload.ts
  lib/typescript/httpclient/src/payload/PaginatedResponse.ts
  lib/typescript/httpclient/src/payload/SendMessagesRequestPayload.ts
  lib/typescript/httpclient/src/payload/TagConversationRequestPayload.ts
  lib/typescript/httpclient/src/payload/UntagConversationRequestPayload.ts
  lib/typescript/httpclient/src/payload/UpdateChannelRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
  tools/build/npm/BUILD
  tools/build/npm/README.md
  tools/build/npm/assemble.py
  tools/build/npm/rules.bzl
  tools/build/npm/templates/BUILD
  tools/build/npm/templates/deploy.py
Labels: fix

#1547 [#1502] Improve model lib
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/model/Content.ts
  lib/typescript/model/Message.ts
  lib/typescript/model/SuggestedReply.ts
  lib/typescript/model/Template.ts
  lib/typescript/render/components/MessageInfoWrapper/index.tsx
  lib/typescript/render/components/RichCard/Media/index.tsx
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/components/index.ts
  lib/typescript/render/index.tsx
  lib/typescript/render/props.ts
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
  lib/typescript/render/providers/chatplugin/components/QuickReplies/index.tsx
  lib/typescript/render/providers/chatplugin/components/RichCard/Media/index.module.scss
  lib/typescript/render/providers/chatplugin/components/RichCard/Media/index.tsx
  lib/typescript/render/providers/chatplugin/components/RichCard/index.module.scss
  lib/typescript/render/providers/chatplugin/components/RichCard/index.tsx
  lib/typescript/render/providers/chatplugin/components/RichCardCarousel/index.module.scss
  lib/typescript/render/providers/chatplugin/components/RichCardCarousel/index.tsx
  lib/typescript/render/providers/chatplugin/components/RichText/index.module.scss
  lib/typescript/render/providers/chatplugin/components/RichText/index.tsx
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
  lib/typescript/render/providers/facebook/components/QuickReplies/index.tsx
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/components/RichCard/Media/index.module.scss
  lib/typescript/render/providers/google/components/RichCard/Media/index.tsx
  lib/typescript/render/providers/google/components/RichCard/index.module.scss
  lib/typescript/render/providers/google/components/RichCard/index.tsx
  lib/typescript/render/providers/google/components/RichCardCarousel/index.module.scss
  lib/typescript/render/providers/google/components/RichCardCarousel/index.tsx
  lib/typescript/render/providers/google/components/RichText/index.module.scss
  lib/typescript/render/providers/google/components/RichText/index.tsx
  lib/typescript/render/providers/google/components/Suggestions/index.tsx
  lib/typescript/render/providers/google/googleModel.ts
  lib/typescript/render/providers/twilio/twilioSMS/TwilioSMSRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
  lib/typescript/websocketclient/payload.ts
Labels: feature

#1564 [#1537] AWS Uninstall Docs - Remove reference to…
  docs/docs/getting-started/installation/aws.md
Labels: feature

#1565 fixed github variable
  .github/workflows/main.yml
Labels: fix

#1571 fixed confikey chat plugin
  frontend/ui/src/pages/Channels/MainPage/index.tsx
  integration/chat-plugin/end_conversation.spec.ts
Labels: fix

#1572 added conversation count in inbox
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
Labels: feature

#1578 [#1577] /conversations.setState Returns 404
  infrastructure/helm-chart/templates/ingress.yaml
Labels: feature

#1550 [#1515] Create airy chat plugin library + use it in UI
  bazel.tsconfig.json
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/index.ts
  frontend/chat-plugin/src/AiryChatPlugin.module.scss
  frontend/chat-plugin/src/AiryChatPlugin.tsx
  frontend/chat-plugin/src/AiryWidget.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/config.ts
  frontend/ui/BUILD
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/EditChatPlugin.tsx
Labels: feature

#1582 [#1581] Prevent page from crashing when adding a channel
  frontend/ui/src/pages/Channels/MainPage/index.module.scss
  frontend/ui/src/pages/Channels/MainPage/index.tsx
Labels: fix

#1583 [#740] Fix env variables
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/chatplugin/templates/deployment.yaml
Labels: fix

#1560 [#1524] Added conversationState to conversationList
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/endpoints/metadataUpsert.ts
  lib/typescript/httpclient/src/endpoints/setStateConversation.ts
  lib/typescript/httpclient/src/payload/MetadataUpsertRequestPayload.ts
  lib/typescript/httpclient/src/payload/SetStateConversationRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
  lib/typescript/model/Conversation.ts
Labels: feature

#1591 [#1590] Fix api host variable injection in chatplugin
  frontend/chat-plugin/index.ts
  frontend/chat-plugin/src/App.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/src/api/index.tsx
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/config.ts
  frontend/chat-plugin/src/defaultScript.tsx
  frontend/chat-plugin/src/websocket/index.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: fix

#1593 [#1234] add old conversation header bar to core UI
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationHeader/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationHeader/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
Labels: feature

#1596 [#1557] fixed color picker for chat plugin customization
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: fix

#1597 [#1415] Fix Video & Image Rendering Problem
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/render/components/Image/index.module.scss
  lib/typescript/render/components/Video/index.tsx
Labels: feature

#1607 [#1602] checkmark svg broken
  lib/typescript/assets/images/icons/checkmark.svg
Labels: fix

#1610 [#1609] fix svg sizing
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  lib/typescript/assets/images/icons/airy_demo_login.png
  lib/typescript/assets/images/icons/checkmark.svg
  lib/typescript/assets/images/icons/template-alt.svg
  lib/typescript/components/inputs/Input/style.module.scss
Labels: fix

#1613 [#1517] Don't create a default system token
  infrastructure/helm-chart/charts/apps/charts/api/templates/security.yaml
Labels: feature

#1612 [#1486] Update spring
  WORKSPACE
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  maven_install.json
Labels: chore

#1595 [#1580] Create in existing VPC on AWS
  cli/pkg/cmd/create/create.go
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  docs/docs/cli/usage.md
  docs/docs/getting-started/installation/aws.md
Labels: feature

#1617 [#1603] Redirect when trying to add GBM channel
  frontend/ui/src/pages/Channels/MainPage/index.tsx
  frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.tsx
Labels: fix

#1619 [#1605] Fix Tags Flow
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Tags/EmptyStateTags.tsx
  frontend/ui/src/pages/Tags/SimpleTagForm.tsx
  frontend/ui/src/pages/Tags/TableRow.module.scss
  frontend/ui/src/pages/Tags/TableRow.tsx
  frontend/ui/src/pages/Tags/index.module.scss
  frontend/ui/src/pages/Tags/index.tsx
  lib/typescript/assets/images/icons/edit-pencil.svg
  lib/typescript/assets/images/icons/edit.svg
  lib/typescript/assets/images/icons/trash.svg
  lib/typescript/httpclient/src/endpoints/createTag.ts
  lib/typescript/httpclient/src/endpoints/listConversations.ts
  lib/typescript/httpclient/src/endpoints/listTags.ts
Labels: fix

#1626 [#1606] Conversation count on the title of the page
  frontend/ui/src/pages/Inbox/index.tsx
Labels: feature

#1627 [#1618] Remove intermediate call to action from new chat plugin
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/ConnectNewChatPlugin.tsx
Labels: fix

#1625 [#1620] Fix the config apply flag in the docs
  docs/docs/getting-started/installation/configuration.md
Labels: fix

#1636 [#1629] Remove hardcoded availability zones
  cli/pkg/providers/aws/aws.go
  docs/docs/getting-started/installation/aws.md
Labels: fix

#1643 [#1635] Update docs on configuring sources
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/twilio-sources.mdx
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/templates/deployments.yaml
Labels: docs

#1645 [#1628] Fix send button for selected templates
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
Labels: fix

#1649 [#1637] fix carousels
  lib/typescript/components/general/Carousel/index.module.scss
Labels: fix

#1644 [#1641] Specify the required minikube version
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#1653 [#1558] Docs for configuring https on AWS
  docs/docs/getting-started/installation/aws.md
Labels: docs

#1664 [#1661] Fix token name in docs
  docs/docs/getting-started/installation/configuration.md
Labels: docs

#1667 [#1666] Fix chatplugin cors config
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
Labels: fix

#1660 [#1525] Update quick filter
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/components/Tag/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.module.scss
  frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
  frontend/ui/src/selectors/conversations.ts
  lib/typescript/model/ConversationFilter.ts
Labels: feature

#1668 [#1495] Add kafka Prometheus exporter
  docs/docs/guides/operations.md
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/headless-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/nodeport-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/values.yaml
  infrastructure/tools/prometheus/values.yaml
Labels: feature

#1678 [#1674] Chatplugin customize problems
  frontend/chat-plugin/src/App.tsx
  frontend/chat-plugin/src/components/chat/index.module.scss
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: fix

#1675 [#1652] Fix rendering messages with render library
  lib/typescript/render/providers/google/GoogleRender.tsx
Labels: fix

#1677 [#1676] fix sending messages to google source
  docs/docs/api/endpoints/google-messages-send.mdx
  docs/docs/sources/google.md
Labels: docs

#1680 [#1646] fix avatar images styling
  lib/typescript/render/components/Avatar/index.module.scss
  lib/typescript/render/components/Avatar/index.tsx
Labels: fix

#1682 [#1665] Fix chatplugin reconnection problem
  frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/src/websocket/index.ts
Labels: fix
