Repository airyhq/airy, pull requests merged in 2021-12, with the labels that each got.

#2630 [#2611] Session timeout
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/websocket/index.ts
  frontend/ui/src/assets/scss/fonts.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  lib/typescript/assets/scss/fonts.scss
Labels: feature

#2639 [#2637] Fix channel prefill
  frontend/ui/src/AiryConfig.ts
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx
  lib/typescript/model/Channel.ts
Labels: fix

#2643 [#2586] Fix terraform
  infrastructure/terraform/main/files/defaultResourceLimits.yaml
  infrastructure/terraform/main/main.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/outputs.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/variables.tf
Labels: feature

#2648 [#2586] Set min and max size for EKS node group
  infrastructure/terraform/modules/aws_eks/main.tf
Labels: feature

#2650 [#2649] ui fix instagram messages
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.module.scss
  lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.tsx
Labels: fix

#2597 [#2550] Docs for multiple providers using helm
  docs/docs/getting-started/installation/helm.md
  docs/static/img/getting-started/installation/k8s-azure.jpg
  docs/static/img/getting-started/installation/k8s-digitalocean-setup.jpg
  docs/static/img/getting-started/installation/k8s-digitalocean.jpg
Labels: docs

#2661 [#2660] Refactor fargate_profiles in AWS EKS
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/outputs.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
Labels: fix

#2662 [#2626] Chat Plugin full screen for mobile
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/lib/src/components/chat/index.module.scss
Labels: feature

#2658 [#2622] api expose facebook page tokens via channels api
  backend/sources/facebook/connector/BUILD
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/model/FaceBookMetadataKeys.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/ChannelsControllerTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/WebhookControllerTest.java
  lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelper.java
  lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelperConfig.java
Labels: backend, feature

#2664 [#2663] Pull busybox from Github packages
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/communication/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/websocket/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/integration/charts/source-api/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/integration/charts/webhook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/media/charts/resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/backend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/frontend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/facebook/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/google/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/twilio/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/viber/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/statefulset.yaml
  infrastructure/helm-chart/templates/provisioning/job-kafka.yaml
  infrastructure/helm-chart/templates/provisioning/job-wait.yaml
  infrastructure/helm-chart/templates/upgrading/0.29.0.yaml
  infrastructure/helm-chart/values.yaml
  infrastructure/images/busybox/Dockerfile
  infrastructure/images/busybox/Makefile
Labels: fix

#2672 [#1497] media resolver crashes on bad configuration
  backend/media/src/main/java/co/airy/core/media/MediaController.java
  backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java
  backend/media/src/test/java/co/airy/core/media/services/MediaUploadTest.java
Labels: fix

#2677 [#2676] Prefill missing inputs instagram channel
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx
Labels: feature

#2628 Add contacts service
  backend/api/contacts/BUILD
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/MetadataRepository.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/ConversationContact.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ContactInfoRequestPayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ContactResponsePayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/CreateContactPayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ListContactsRequestPayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ListContactsResponsePayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/PaginationData.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/UpdateContactPayload.java
  backend/api/contacts/src/main/resources/application.properties
  backend/api/contacts/src/test/java/co/airy/core/contacts/CreateContactsTest.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/ListContactsTest.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/UpdateContactsTest.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/util/TestContact.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/util/Topics.java
  backend/api/contacts/src/test/resources/test.properties
  backend/model/conversation/src/main/java/co/airy/model/conversation/Conversation.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java
  docs/docs/api/contacts-response-payload.mdx
  docs/docs/api/contacts.md
  docs/docs/api/event-payloads.mdx
  docs/sidebars.js
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/values.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/values.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/values.yaml
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/application/ApplicationCommunicationContacts.java
Labels: backend, feature

#2679 [#2675] NPM package release rule needs username…
  .github/workflows/main.yml
  tools/build/npm/templates/deploy.py
Labels: feature
