Repository airyhq/airy, pull requests merged in 2021-07, with the labels that each got.

#2088 [#1916] Cypress test for display name edit
  frontend/ui/handles/index.ts
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  integration/ui/display_name_edit.spec.ts
  integration/ui/state_conversations.spec.ts
Labels: feature

#2087 [#2074] Added subtitle to Chatplugin
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx
  frontend/chat-plugin/src/config.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: feature

#2070 [#2069] fix http client and chat plugin packages
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/README.md
  frontend/chat-plugin/package.json
  lib/typescript/httpclient/README.md
  lib/typescript/httpclient/package.json
Labels: fix

#2089 [#2073] Added powered by airy to Chatplugin
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
Labels: feature

#2092 [#661] Added possibility to connect Google via UI
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.tsx
  frontend/ui/src/pages/Channels/MainPage/index.tsx
  frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/routes/routes.ts
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/connectGoogleChannel.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/payload/ConnectChannelGoogleRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
Labels: feature

#2094 [#2093] Fixed moving avatar in ConversationListItem
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
Labels: fix

#2095 [#2071] Redesigned inputbar Chatplugin
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
Labels: feature

#2106 [#1970] Add issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: chore

#2082 [#2051] Support instagram as a source
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Api.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/model/InstagramProfile.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/payload/ConnectInstagramRequestPayload.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/payload/ConnectPageRequestPayload.java
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/EventsRouter.java
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
  docs/docs/api/endpoints/channels.md
  docs/docs/api/endpoints/connect-instagram.mdx
  docs/docs/sources/facebook.md
  docs/docs/sources/inbox-messages.mdx
  docs/docs/sources/instagram.md
  docs/sidebars.js
  docs/static/img/sources/instagram/instagramAccountId.jpg
  docs/static/img/sources/instagram/webhookInstagram.jpg
  frontend/ui/src/components/IconChannel/index.tsx
  infrastructure/helm-chart/templates/ingress.yaml
  lib/typescript/assets/images/icons/instagram.svg
  lib/typescript/render/renderProviders.ts
Labels: feature

#2107 [#2014] Fix stable version file
  scripts/upload-cli-binaries.sh
Labels: chore

#2121 [#2072] Chat Plugin: Emoji Selector
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/src/components/emojiPicker/EmojiPicker.tsx
  frontend/chat-plugin/src/components/emojiPicker/EmojiPickerWrapper.tsx
Labels: fix

#2120 [#1590] Refactor: Split chatplugin into library and app targets
  bazel.tsconfig.json
  frontend/chat-plugin/BUILD
  frontend/chat-plugin/README.md
  frontend/chat-plugin/deps.bzl
  frontend/chat-plugin/dev/BUILD
  frontend/chat-plugin/dev/config.ts
  frontend/chat-plugin/dev/development.html
  frontend/chat-plugin/dev/index.tsx
  frontend/chat-plugin/development.html
  frontend/chat-plugin/image/BUILD
  frontend/chat-plugin/image/example.html
  frontend/chat-plugin/image/index.tsx
  frontend/chat-plugin/image/nginx.conf
  frontend/chat-plugin/lib/BUILD
  frontend/chat-plugin/lib/README.md
  frontend/chat-plugin/lib/index.ts
  frontend/chat-plugin/lib/package.json
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
  frontend/chat-plugin/lib/src/api/index.tsx
  frontend/chat-plugin/lib/src/components/bubble/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.module.scss
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/chat-plugin/lib/src/components/emojiPicker/EmojiPicker.tsx
  frontend/chat-plugin/lib/src/components/emojiPicker/EmojiPickerWrapper.tsx
  frontend/chat-plugin/lib/src/components/headerBar/index.tsx
  frontend/chat-plugin/lib/src/components/inputBar/index.tsx
  frontend/chat-plugin/lib/src/components/message/index.tsx
  frontend/chat-plugin/lib/src/components/modal/index.module.scss
  frontend/chat-plugin/lib/src/components/modal/index.tsx
  frontend/chat-plugin/lib/src/components/newConversation/index.module.scss
  frontend/chat-plugin/lib/src/components/newConversation/index.tsx
  frontend/chat-plugin/lib/src/config.ts
  frontend/chat-plugin/lib/src/storage.ts
  frontend/chat-plugin/lib/src/websocket/index.ts
  frontend/chat-plugin/src/AiryChatPlugin.module.scss
  frontend/chat-plugin/src/AiryChatPlugin.tsx
  frontend/chat-plugin/src/AiryWidget.tsx
  frontend/chat-plugin/src/App.module.scss
  frontend/chat-plugin/src/App.tsx
  frontend/chat-plugin/src/iframe.tsx
  frontend/chat-plugin/tsconfig.json
  frontend/ui/BUILD
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/EditChatPlugin.module.scss
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookMessengerRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioRequirementsDialog/index.module.scss
  package.json
  yarn.lock
Labels: chore

#2136 [#2132] Allow deleting messages
  .github/dependabot.yml
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketController.java
  backend/sources/chat-plugin/BUILD
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
  backend/sources/facebook/connector/src/main/resources/application.properties
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java
  backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java
  backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
Labels: feature

#2147 [#2078] Add endpoint for uploading media
  backend/media/BUILD
  backend/media/src/main/java/co/airy/core/media/MediaController.java
  backend/media/src/main/java/co/airy/core/media/MessageMediaResolver.java
  backend/media/src/main/java/co/airy/core/media/MetadataResolver.java
  backend/media/src/main/java/co/airy/core/media/Stores.java
  backend/media/src/main/java/co/airy/core/media/config/AwsConfig.java
  backend/media/src/main/java/co/airy/core/media/dto/MessageMediaRequest.java
  backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java
  backend/media/src/main/resources/application.properties
  backend/media/src/test/java/co/airy/core/media/MediaControllerTest.java
  backend/media/src/test/java/co/airy/core/media/MessagesTest.java
  backend/media/src/test/java/co/airy/core/media/MetadataTest.java
  backend/media/src/test/resources/giphy.gif
  backend/media/src/test/resources/test.properties
  docs/docs/api/endpoints/attachments.md
  docs/docs/getting-started/installation/configuration.md
  infrastructure/helm-chart/charts/apps/charts/media/charts/resolver/templates/deployment.yaml
  infrastructure/helm-chart/templates/ingress.yaml
  lib/java/mapping/BUILD
  lib/java/mapping/README.md
  lib/java/mapping/src/main/java/co/airy/mapping/ContentMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/OutboundMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/SourceMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Audio.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Content.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/DataUrl.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/File.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Image.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/SourceTemplate.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Text.java
  lib/java/mapping/src/main/java/co/airy/mapping/model/Video.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java
  lib/java/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java
  lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java
  lib/java/mapping/src/test/java/co/airy/mapping/TwilioTest.java
  lib/java/mapping/src/test/resources/facebook/audio.json
  lib/java/mapping/src/test/resources/facebook/file.json
  lib/java/mapping/src/test/resources/facebook/image.json
  lib/java/mapping/src/test/resources/facebook/template_generic.json
  lib/java/mapping/src/test/resources/facebook/text.json
  lib/java/mapping/src/test/resources/facebook/video.json
  lib/java/mapping/src/test/resources/google/suggestionResponse.json
  lib/java/mapping/src/test/resources/google/text.json
  lib/java/uuid/BUILD
  lib/java/uuid/src/main/java/co/airy/uuid/UUIDv5.java
  lib/java/uuid/src/main/java/co/airy/uuid/UUIDv5Builder.java
  lib/java/uuid/src/test/java/co/airy/uuid/UUIDv5Test.java
Labels: feature

#2152 [#2149] UI crashes when filtering with unknown source involved
  frontend/ui/src/components/SourceIcon/index.tsx
  lib/typescript/assets/images/icons/bubble.svg
  lib/typescript/assets/images/icons/instagramSource.svg
Labels: fix

#2157 Release 0.26.0
  docs/docs/changelog.md
Labels: fix

#2156 Enable Prometheus endpoint on webhook publisher
  backend/webhook/publisher/BUILD
Labels: fix

#2161 Release 0.26.0
  docs/docs/changelog.md
Labels: fix

#2159 [#2150] Messages with same sent at time don't disappear in the message list
  .github/workflows/main.yml
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Messages.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/MessagesTreeSet.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java
Labels: fix

#2163 [#2155] Add springboot actuator dep
  backend/webhook/publisher/BUILD
Labels: fix

#2164 [#2162] Only log post requests to kafka
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/HttpPostLogFilter.java
  lib/java/spring/web/src/main/java/co/airy/spring/web/filters/RequestLoggingConfig.java
Labels: fix

#2165 [#1972] [#1598] Apply configuration after create and supress minikube download output
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/create/BUILD
  cli/pkg/cmd/create/create.go
  cli/pkg/providers/minikube/minikube.go
  docs/docs/cli/usage.md
Labels: feature

#2167 [#1211] Rename conversations.read endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java
  docs/docs/api/endpoints/conversations.md
  docs/sidebars.js
  infrastructure/helm-chart/templates/ingress.yaml
  lib/typescript/httpclient/src/endpoints/readConversations.ts
Labels: chore

#2166 [#2151] Removed fixed sidebar
  frontend/ui/src/components/Sidebar/index.module.scss
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/SMS/TwilioSmsConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/WhatsApp/TwilioWhatsappConnect.module.scss
  frontend/ui/src/pages/Channels/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/index.module.scss
  frontend/ui/src/pages/Tags/index.module.scss
Labels: fix

#2170 [#1805] Fix Chatplugin reconnection
  frontend/chat-plugin/lib/src/api/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/chat-plugin/lib/src/websocket/index.ts
Labels: fix

#2178 [#2176] Set sendButton fixed Chatplugin
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
Labels: fix

#2183 [#2182] release script fails if GITHUB_TOKEN env is not set
  .github/ISSUE_TEMPLATE/---bug-report.md
  frontend/chat-plugin/image/nginx.conf
  scripts/release.sh
Labels: chore

#2188 [#2187] Hotfix chatplugin bundle loading
  VERSION
  frontend/chat-plugin/image/BUILD
  frontend/chat-plugin/image/index.tsx
  frontend/chat-plugin/image/nginx.conf
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
Labels: fix

#2189 [#2187] Hotfix chatplugin bundle loading
  frontend/chat-plugin/image/BUILD
  frontend/chat-plugin/image/index.tsx
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx
Labels: fix

#2190 General improvement of libs lib
  lib/typescript/components/loaders/AiryLoader/data.ts
  lib/typescript/components/loaders/AiryLoader/index.tsx
Labels: chore

#2193 [#2192] Hotfix: inbox crashing when selecting conversations in filtered view
  VERSION
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
Labels: fix

#2194 [#2192] Hotfix: inbox message list crash
  docs/docs/changelog.md
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
Labels: fix

#2196 Fix chatplugin code generator
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: fix

#2191 [#2168] Support Twilio media url messages
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/services/Api.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
  docs/docs/api/endpoints/messages-send.mdx
  docs/docs/getting-started/installation/configuration.md
  docs/docs/sources/facebook.md
  docs/docs/sources/inbox-messages.mdx
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/twilio-send-message.mdx
  docs/docs/sources/whatsapp-twilio.md
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/ui/src/App.module.scss
  frontend/ui/src/App.tsx
  frontend/ui/src/components/Dialog/index.module.scss
  frontend/ui/src/components/DialogCustomizable/index.module.scss
  frontend/ui/src/components/Sidebar/index.module.scss
  frontend/ui/src/components/Sidebar/index.tsx
  frontend/ui/src/components/TopBar/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookMessengerRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioRequirementsDialog/index.tsx
  frontend/ui/src/pages/Channels/SourceDescriptionCard/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/index.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.module.scss
  frontend/ui/src/pages/Inbox/QuickFilter/index.module.scss
  frontend/ui/src/pages/Inbox/TemplateSelector/index.module.scss
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
  lib/typescript/assets/scss/z-index.scss
  lib/typescript/httpclient/src/index.ts
  lib/typescript/httpclient/src/messagesForChannels/index.ts
  lib/typescript/httpclient/src/messagesForChannels/text/index.ts
  lib/typescript/httpclient/src/payload/SendMessagesRequestPayload.ts
  lib/typescript/render/index.ts
  lib/typescript/render/outbound/chatplugin.ts
  lib/typescript/render/outbound/facebook.ts
  lib/typescript/render/outbound/google.ts
  lib/typescript/render/outbound/index.ts
  lib/typescript/render/outbound/mapper.ts
  lib/typescript/render/outbound/twilio.ts
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/twilio/TwilioRender.tsx
  lib/typescript/render/providers/twilio/twilioModel.ts
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/twilioWhatsappModel.ts
  lib/typescript/render/renderProviders.ts
Labels: feature

#2199 [#2117] Ingest and render Google Business Messages requests for live agents
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java
  backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java
  lib/typescript/components/general/Emoji/index.tsx
  lib/typescript/components/general/index.ts
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/render/providers/google/components/RequestedLiveAgent/index.module.scss
  lib/typescript/render/providers/google/components/RequestedLiveAgent/index.tsx
  lib/typescript/render/providers/google/googleModel.ts
Labels: feature

#2198 [#2140] Call to /webhooks.subscribe fails when the component is not enabled or crashing
  .bazelrc
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ServiceDiscovery.java
  backend/api/admin/src/main/java/co/airy/core/api/config/dto/ComponentInfo.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
Labels: feature

#2129 [#2115] Conversation Status Changes occasionally not reflected in Inbox UI
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
Labels: fix

#2169 [#2148] enable users to connect via instagram
  frontend/ui/handles/index.ts
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/components/ChannelAvatar/index.tsx
  frontend/ui/src/components/SourceIcon/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.tsx
  frontend/ui/src/pages/Channels/MainPage/index.tsx
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramRequirementsDialog/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramRequirementsDialog/index.tsx
  frontend/ui/src/pages/Channels/SourceDescriptionCard/index.module.scss
  frontend/ui/src/pages/Channels/SourceDescriptionCard/index.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/routes/routes.ts
  lib/typescript/assets/images/icons/instagramSource.svg
  lib/typescript/assets/images/icons/instagram_avatar.svg
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/connectInstagramChannel.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/payload/ConnectChannelInstagramRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
  lib/typescript/model/Source.ts
Labels: feature

#2214 [#2186] Small docs fixes
  docs/docs/concepts/release-process.md
  docs/docs/sources/instagram.md
  lib/typescript/httpclient/README.md
Labels: docs

#2216 [#2215] fix instagram mapper
  lib/typescript/render/outbound/index.ts
Labels: fix

#2220 [#2219] fixed inbox ui overflow bug
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/index.module.scss
Labels: fix

#2222 Inbox UI carousels facebook break the UI
  VERSION
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/index.module.scss
Labels: fix

#2225 fix changelog
  docs/docs/changelog.md
Labels: fix
