Repository airyhq/airy, pull requests merged in 2021-05, with the labels that each got.

#1688 [#1687] Kafka Prometheus exporter error on…
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/_helpers.tpl
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/headless-service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/prometheus.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/service.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/kafka/charts/kafka/values.yaml
Labels: feature

#1697 [#1689] Bug: Conversation Counter: Optimize Filter Use
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
Labels: fix

#1699 [#1698] Webhook config error
  docs/docs/getting-started/installation/configuration.md
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/templates/deployments.yaml
Labels: fix

#1623 Add OIDC authentication backend
  BUILD
  WORKSPACE
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigResponsePayload.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketConfig.java
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/config/parser.go
  cli/pkg/cmd/create/helm.go
  cli/pkg/workspace/template/airy.yaml
  docs/docs/api/authentication.md
  docs/docs/getting-started/installation/configuration.md
  infrastructure/helm-chart/charts/apps/charts/api/templates/security.yaml
  infrastructure/helm-chart/templates/ingress.yaml
  lib/java/spring/auth/BUILD
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/PrincipalAccess.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ClientConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/CommonProviders.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ConfigProvider.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/EmailFilter.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/UserProperties.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/UserService.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/github/EmailsResponse.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/github/GithubApi.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/AiryAuth.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/AuthCookie.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/CookieSecurityContextRepository.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/Jwt.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/UserProfile.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/token/AuthenticationFilter.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/token/TokenAuth.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/AuthenticationTest.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/NoAuthTest.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/test_app/Controller.java
  maven_install.json
Labels: feature

#1690 [#1642] Add dev cli script
  scripts/dev_cli.sh
Labels: feature

#1712 [#1642] Fix flag
  scripts/dev_cli.sh
Labels: fix

#1715 [#1714] Webhook config updates only once
  backend/webhook/consumer/pkg/worker/worker.go
Labels: feature

#1703 [#1695] Twilio SMS does not display the channelSourceId correctly
  frontend/ui/src/components/IconChannel/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsBySourceCard/index.tsx
Labels: fix

#1683 [#1558] Enable loadbalancer annotations
  cli/pkg/providers/aws/aws.go
  docs/docs/getting-started/installation/aws.md
  infrastructure/helm-chart/templates/ingress-controller.yaml
  infrastructure/helm-chart/values.yaml
Labels: fix

#1717 [#1706] Fixed gap between conversationList and conversationListHeader
  frontend/ui/src/pages/Inbox/ConversationsFilter/index.module.scss
Labels: fix

#1704 [#1694] Adding icons for lastMessage
  frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  lib/typescript/assets/images/icons/attachmentImage.svg
  lib/typescript/assets/images/icons/attachmentTemplate.svg
  lib/typescript/assets/images/icons/attachmentVideo.svg
Labels: fix

#1720 [#1713] Fix crash conversation from search
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationHeader/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  frontend/ui/src/selectors/conversations.ts
Labels: feature

#1722 [#1721] Webhook consumer should start consuming…
  backend/webhook/consumer/main.go
  backend/webhook/consumer/pkg/worker/consumer.go
  backend/webhook/consumer/pkg/worker/worker.go
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/templates/deployments.yaml
Labels: feature

#1728 [#1696] Fix backgroundColor accountName
  frontend/ui/src/components/TopBar/index.module.scss
Labels: fix

#1731 [#1726] Customize Start a New Conversation button
  frontend/chat-plugin/src/components/chat/index.tsx
  frontend/chat-plugin/src/components/newConversation/index.module.scss
  frontend/chat-plugin/src/components/newConversation/index.tsx
  frontend/chat-plugin/src/config.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: fix

#1735 [#1729] Fix lastMessageIcon
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  lib/typescript/assets/images/icons/richCardIcon.svg
Labels: fix

#1737 [#1519] Implement auth UI behavior
  WORKSPACE
  backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
  frontend/ui/src/App.tsx
  frontend/ui/src/InitializeAiryApi.ts
  frontend/ui/src/components/TopBar/index.module.scss
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/reducers/data/index.ts
  frontend/ui/src/reducers/data/user/index.ts
  infrastructure/helm-chart/templates/ingress.yaml
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/CookieSecurityContextRepository.java
  lib/typescript/httpclient/client.ts
  lib/typescript/httpclient/src/endpoints/getConfig.ts
  lib/typescript/model/Config.ts
  lib/typescript/model/User.ts
  scripts/web-dev.sh
Labels: feature

#1691 [#1486] Upgrade kafka images
  WORKSPACE
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  backend/media/src/test/java/co/airy/core/media/MessagesTest.java
  backend/media/src/test/java/co/airy/core/media/MetadataTest.java
  backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java
  backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java
  backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
  infrastructure/helm-chart/charts/kafka/charts/kafka/values.yaml
  infrastructure/helm-chart/charts/kafka/charts/zookeeper/values.yaml
  infrastructure/helm-chart/charts/provisioning/values.yaml
  infrastructure/images/kafka/Dockerfile
  infrastructure/images/kafka/Makefile
  lib/java/kafka/streams/src/main/java/co/airy/kafka/streams/KafkaStreamsWrapper.java
  lib/java/kafka/test/BUILD
  maven_install.json
Labels: chore

#1749 [#1748] Add missing default redirect uri
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/CommonProviders.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ConfigProvider.java
Labels: fix

#1754 [#1745] Update chat plugin customization docs
  docs/docs/sources/chatplugin/customization.md
Labels: docs

#1755 [#1486] Upgrade rules_pkg and rules_docker
  WORKSPACE
Labels: chore

#1756 [#1736] improve render library for facebook
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/components/Video/index.module.scss
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: fix

#1757 [#1486] upgrade react
  package.json
  yarn.lock
Labels: chore

#1772 [#1681] Clean phone number input
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsStateTest.java
  backend/sources/twilio/connector/BUILD
  backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java
  backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
Labels: feature

#1774 [#1764] Filter fixed + state header bar toggle fix
  frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx
  frontend/ui/src/selectors/conversations.ts
Labels: fix

#1785 [#1743] Return proper status code for unauthorized access
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/CookieSecurityContextRepository.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/AuthenticationTest.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
  lib/typescript/httpclient/client.ts
Labels: feature

#1775 [#1768] bad calls to conversations info when opening inbox
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
Labels: fix

#1786 [#1743] Permit public auth pages
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
Labels: fix

#1797 [#1781] Add Documentation on Source Connection Page
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Twilio/SMS/TwilioSmsConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Twilio/WhatsApp/TwilioWhatsappConnect.tsx
  lib/typescript/assets/images/icons/info-circle.svg
  lib/typescript/components/cta/InfoButton/index.tsx
  lib/typescript/components/cta/InfoButton/style.module.scss
  lib/typescript/components/cta/index.ts
Labels: fix

#1814 [#1813] Update docs on conersations states
  docs/docs/api/endpoints/conversations.md
Labels: docs

#1799 Add health status to components endpoint
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ComponentResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ComponentsResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/config/HealthApi.java
  backend/api/admin/src/main/java/co/airy/core/api/config/ServiceDiscovery.java
  backend/api/admin/src/main/java/co/airy/core/api/config/dto/ServiceInfo.java
  backend/api/admin/src/main/java/co/airy/core/api/config/payload/ClientConfigResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/config/payload/ServicesResponsePayload.java
  backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java
  frontend/chat-plugin/nginx.conf
  frontend/ui/nginx.conf
  frontend/ui/src/reducers/data/config/index.ts
  infrastructure/controller/pkg/endpoints/endpoints.go
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/integration/charts/webhook/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/media/charts/resolver/templates/deployment.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/templates/deployments.yaml
  infrastructure/helm-chart/charts/apps/charts/sources/charts/google/templates/deployments.yaml
  infrastructure/helm-chart/charts/provisioning/templates/kafka-create-topics.yaml
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/ops/OpsApplicationHealth.java
  lib/java/spring/core/src/main/java/co/airy/spring/core/AirySpringBootApplication.java
  lib/java/spring/kafka/healthcheck/BUILD
  lib/java/spring/kafka/healthcheck/healtcheck.avsc
  lib/java/spring/kafka/healthcheck/src/main/java/co/airy/spring/kafka/healthcheck/ProducerHealthCheck.java
  lib/typescript/model/Config.ts
Labels: fix

#1818 [#1798] fix not rendered content messages in facebook render library
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx
  lib/typescript/render/providers/facebook/components/Buttons/index.module.scss
  lib/typescript/render/providers/facebook/components/Buttons/index.tsx
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx
  lib/typescript/render/providers/facebook/components/MediaTemplate/index.module.scss
  lib/typescript/render/providers/facebook/components/MediaTemplate/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: fix

#1822 [#1809] Channels page breaks when there are too many channels
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/SMS/TwilioSmsConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/TwilioConnect.module.scss
  frontend/ui/src/pages/Channels/Providers/Twilio/WhatsApp/TwilioWhatsappConnect.module.scss
Labels: fix

#1651 [#1650] Message pagination
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/dto/LuceneQueryResult.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneDiskStore.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/ReadOnlyLuceneStore.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelper.java
Labels: feature

#1835 [#1843] Fix Airy core reachability
  infrastructure/helm-chart/templates/ngrok.yaml
Labels: infrastructure

#1836 [#1843] Fix Airy core reachability followup
  infrastructure/helm-chart/templates/ngrok.yaml
Labels: fix

#1852 [#1838] Add call to pagination when filtering conversations
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
Labels: fix

#1840 [#1823] Improve login/logout behavior
  docs/docs/api/authentication.md
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ClientConfig.java
  lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/LoginRedirect.java
  lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
Labels: feature

#1855 [#1820] Sending messages UX improvement: focus on input and send on Enter
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
Labels: fix

#1839 [#1837] improve facebook render library follow-up
  lib/typescript/render/providers/facebook/FacebookRender.tsx
Labels: fix

#1849 fix getting started-introduction
  docs/docs/getting-started/components.md
  docs/docs/getting-started/introduction.md
Labels: docs

#1858 [#1853] minor grammar edits sources + UI
  docs/docs/sources/chatplugin/installation.md
  docs/docs/sources/chatplugin/overview.md
  docs/docs/sources/chatplugin/quickstart.md
  docs/docs/sources/debugging-twilio.mdx
  docs/docs/sources/facebook.md
  docs/docs/sources/google.md
  docs/docs/sources/introduction.md
  docs/docs/sources/sms-twilio.md
  docs/docs/sources/twilio-config.mdx
  docs/docs/sources/twilio-sources.mdx
  docs/docs/sources/whatsapp-twilio.md
  docs/docs/ui/channels.md
  docs/docs/ui/inbox.md
  docs/docs/ui/introduction.md
  docs/docs/ui/suggestedReplies.md
  docs/docs/ui/tags.md
Labels: docs

#1821 [#1808] Improved lastMessageSent
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationHeader/index.tsx
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/props.ts
  lib/typescript/render/providers/twilio/twilioSMS/TwilioSMSRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
Labels: fix

#1864 [#1773] Filter conversations by source
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/components/IconChannelFilter/index.module.scss
  frontend/ui/src/components/SourceIcon/index.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.module.scss
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/index.tsx
  frontend/ui/src/reducers/data/conversations/index.ts
  frontend/ui/src/selectors/conversations.ts
  lib/typescript/model/ConversationFilter.ts
  lib/typescript/model/Source.ts
  lib/typescript/model/index.ts
Labels: feature

#1874 [#1815] Added emptyState for filtered items
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/NoConversations/index.tsx
Labels: feature

#1876 [#1733] fix cypress tests
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  integration/chat-plugin/end_conversation.spec.ts
  integration/chat-plugin/websocket_test.spec.ts
  integration/ui/connect_chatplugin.spec.ts
  integration/ui/create_tag.spec.ts
  integration/ui/filter_conversation.spec.ts
  integration/ui/send_chatplugin_message.spec.ts
Labels: fix, testing

#1867 [#1863] Added SourceMessagePreview
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  lib/typescript/render/SourceMessage.tsx
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/index.ts
  lib/typescript/render/props.ts
  lib/typescript/render/providers/twilio/twilioSMS/TwilioSMSRender.tsx
  lib/typescript/render/providers/twilio/twilioWhatsapp/TwilioWhatsappRender.tsx
Labels: fix

#1873 [#1732] Fix display name search typo
  backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java
  frontend/ui/src/actions/conversationsFilter/index.ts
Labels: fix
