Repository airyhq/airy, pull requests merged in 2022-05, with the labels that each got.

#3124 [#3123] Update docs for webhooks
  docs/docs/api/webhook.md
Labels: docs

#3129 [#3128] Fix npm deployment
  frontend/chat-plugin/lib/BUILD
  frontend/chat-plugin/lib/publish_package.json
  lib/typescript/httpclient/BUILD
  lib/typescript/httpclient/publish_package.json
  tools/build/npm/templates/deploy.py
Labels: fix

#3135 chore/update test libraries
  maven_install.json
  repositories.bzl
Labels: chore

#3137 chore/add mockito inline to deps
  repositories.bzl
Labels: chore

#3136 [#3121] Fix InfoCard and update connectors docs
  docs/static/img/ui/controlCenterConnectors.png
  frontend/control-center/src/pages/Catalog/CatalogItemList.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/InfoCard/index.module.scss
  frontend/control-center/src/pages/Connectors/InfoCard/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
Labels: frontend, docs

#3142 [#3141] conversations for contacts fix
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
Labels: fix

#3149 Feature/3004 add service to every connector
  backend/sources/facebook/events-router/BUILD
  backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/EventsRouter.java
  backend/sources/google/events-router/BUILD
  backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java
  backend/sources/twilio/events-router/BUILD
  backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/EventsRouter.java
  backend/webhook/consumer/src/main/java/co/airy/core/webhook/consumer/Stores.java
  infrastructure/helm-chart/charts/components/charts/sources/charts/facebook/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/google/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/twilio/templates/service.yaml
Labels: feature

#3150 [#3144] Show just enabled components
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/index.tsx
Labels: feature

#3143 [#3126] Added Webhooks to docs
  docs/docs/ui/control-center/introduction.md
  docs/docs/ui/control-center/webhooks.md
  docs/sidebars.js
  docs/static/icons/webhooksIcon.svg
  docs/static/img/ui/controlCenterWebhooks.png
Labels: docs

#3164 [#3163] darkmode follow-up
  lib/typescript/components/inputs/Toggle/index.tsx
Labels: fix

#3162 [#3158] Added animations control center
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
  frontend/control-center/src/pages/Webhooks/SubscriptionModal/index.tsx
  frontend/control-center/src/pages/Webhooks/index.module.scss
  frontend/inbox/src/assets/animations/animations.scss
  frontend/inbox/src/assets/animations/index.ts
  frontend/inbox/src/components/TopBar/index.module.scss
  frontend/inbox/src/components/TopBar/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  lib/typescript/assets/scss/animations.scss
  lib/typescript/render/services/index.ts
  lib/typescript/render/services/useAnimation.ts
Labels: feature

#3166 [#3148] Docs for mandatory API security attributes
  docs/docs/getting-started/installation/security.md
Labels: docs

#3147 [#2755] Authenticate controller
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  cli/go.sum
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/controller/go.mod
  infrastructure/controller/go.sum
  infrastructure/controller/pkg/endpoints/BUILD
  infrastructure/controller/pkg/endpoints/auth.go
  infrastructure/controller/pkg/endpoints/server.go
  infrastructure/controller/pkg/endpoints/services.go
  infrastructure/helm-chart/templates/controller/deployment.yaml
  infrastructure/lib/go/k8s/handler/go.sum
  tools/update-deps/main.go
Labels: feature

#3180 Hotfix/update release changelog docs
  docs/docs/changelog.md
Labels: fix

#3182 [#3066] New design sidebar inbox
  frontend/inbox/src/components/Sidebar/index.module.scss
  frontend/inbox/src/components/Sidebar/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/index.module.scss
  frontend/inbox/src/pages/Tags/index.module.scss
Labels: feature

#3190 [#3184] Update release notes with testing
  docs/docs/concepts/release-process.md
Labels: docs

#3191 [#3185] update cypress tests
  frontend/control-center/src/components/SourceInfo/index.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/inbox/handles/index.ts
  frontend/inbox/src/pages/Inbox/Messenger/MessageList/index.tsx
  integration/chat-plugin/websocket_test.spec.ts
  integration/cypress.json
  integration/ui/connect_chatplugin.spec.ts
  integration/ui/contact_edit.spec.ts
  integration/ui/create_tag.spec.ts
  integration/ui/display_name_edit.spec.ts
  integration/ui/filter_conversation.spec.ts
  integration/ui/send_chatplugin_message.spec.ts
  integration/ui/state_conversations.spec.ts
  integration/ui/suggested_replies.spec.ts
Labels: testing

#3219 [#3171] Admin api unhealthy on minikube
  backend/api/admin/src/main/java/co/airy/core/api/config/HealthApi.java
  backend/api/admin/src/main/resources/application.properties
  backend/api/admin/src/test/resources/test.properties
  infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml
Labels: fix

#3176 [#2756] Apply config through the airy controller
  cli/pkg/cmd/BUILD
  cli/pkg/cmd/api/BUILD
  cli/pkg/cmd/api/endpoint.go
  cli/pkg/cmd/config/BUILD
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/create/BUILD
  cli/pkg/cmd/create/create.go
  cli/pkg/cmd/root.go
  cli/pkg/cmd/ui/BUILD
  cli/pkg/cmd/ui/ui.go
  cli/pkg/cmd/upgrade/BUILD
  cli/pkg/cmd/upgrade/upgrade.go
  cli/pkg/kube/BUILD
  cli/pkg/workspace/BUILD
  cli/pkg/workspace/files.go
  docs/docs/api/endpoints/cluster.md
  docs/docs/api/endpoints/components.md
  docs/sidebars.js
  go_repositories.bzl
  infrastructure/controller/pkg/endpoints/BUILD
  infrastructure/controller/pkg/endpoints/cluster_update.go
  infrastructure/controller/pkg/endpoints/components_delete.go
  infrastructure/controller/pkg/endpoints/components_get.go
  infrastructure/controller/pkg/endpoints/components_update.go
  infrastructure/controller/pkg/endpoints/server.go
  infrastructure/controller/pkg/endpoints/services.go
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-communication/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/api/charts/api-websocket/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-inbox/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-inbox/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/backend/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/configmap.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/frontend/deployment.yaml
  infrastructure/helm-chart/charts/components/templates/api/admin/configmap.yaml
  infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml
  infrastructure/helm-chart/templates/controller/ingress.yaml
  lib/go/config/BUILD
  lib/go/config/airy_yaml.go
  lib/go/config/components.go
  lib/go/config/security.go
  lib/go/httpclient/BUILD
  lib/go/httpclient/client.go
  lib/go/httpclient/cluster.go
  lib/go/httpclient/components.go
  lib/go/httpclient/httpclient.go
  lib/go/k8s/BUILD
  lib/go/k8s/configmaps.go
  lib/go/kubectl/configmaps/get.go
  lib/go/payloads/BUILD
  lib/go/payloads/client_config_request_payload.go
  lib/go/payloads/client_config_response_payload.go
  lib/go/payloads/cluster.go
  lib/go/payloads/components.go
Labels: feature

#3230 [#2756] Fix values inside api-admin configMap
  infrastructure/helm-chart/charts/components/templates/api/admin/configmap.yaml
Labels: fix
