Repository airyhq/airy, pull requests merged in 2022-01, with the labels that each got.

#2683 [#2682] AKHQ for multiple namespaced Kafkas
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/configmap.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/ingress.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/service.yaml
  infrastructure/helm-chart/charts/tools/charts/akhq/values.yaml
Labels: feature

#2638 [#1246] Add documentation on how to run images locally
  docs/docs/guides/contributing.md
Labels: feature

#2690 [#2678] Make clear distiction between inbound outbound webhook
  docs/README.md
  docs/docs/api/webhook.md
  docs/docs/getting-started/components.md
Labels: docs

#2692 [#2691] Beanstalk service needs a label
  infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/templates/configmap.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/templates/service.yaml
Labels: feature

#2694 [#2667] Fix vulnerable Github action
  .github/workflows/main.yml
Labels: fix

#2698 [#2293] Fix contact creation
  backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java
  infrastructure/helm-chart/charts/components/templates/ingress.yaml
Labels: feature

#2700 [#2699] Kafka Connect is not activatable with Helm
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/deployment.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/jmx-configmap.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/service.yaml
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/values.yaml
Labels: feature

#2703 [#2651] Helm installation tabItem is swapped
  docs/docs/getting-started/installation/helm.md
Labels: docs

#2704 [#2577] Notification Badge Chatplugin
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.tsx
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/chat-plugin/lib/src/config.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: feature

#2708 [#2684] Fix refresh inbox
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
Labels: fix

#2719 [#2718] Fix schema registry url
  infrastructure/helm-chart/charts/tools/charts/akhq/templates/configmap.yaml
Labels: fix

#2725 [#2724] Fix incorrect imageTag for viber
  infrastructure/helm-chart/charts/components/charts/sources/charts/viber/Chart.yaml
Labels: fix

#2705 [#2693] contacts import endpoint
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/CreateContactPayload.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java
  backend/api/contacts/src/test/resources/test.properties
Labels: feature

#2733 [#2693] contacts service delete endpoint
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/DeleteContactPayload.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/DeleteContactTest.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java
  backend/api/contacts/src/test/resources/test.properties
Labels: feature

#2739 [#2737] Added Airy config files to gitignore
  .gitignore
  infrastructure/.gitignore
Labels: feature

#2740 [#2736] Re-provision topics on upgrade
  VERSION
  docs/docs/changelog.md
  infrastructure/helm-chart/templates/provisioning/job-kafka.yaml
Labels: fix

#2746 [#2647] Add sender information to messages
  backend/api/admin/src/main/java/co/airy/core/api/admin/Stores.java
  backend/api/communication/BUILD
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsInfoTest.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/util/Topics.java
  backend/api/communication/src/test/resources/test.properties
  backend/api/contacts/src/test/resources/test.properties
  backend/api/websocket/src/test/resources/test.properties
  backend/media/src/test/resources/test.properties
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageContainer.java
  backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java
  backend/model/message/src/main/java/co/airy/model/message/dto/Sender.java
  backend/sources/api/src/test/resources/test.properties
  backend/sources/chat-plugin/src/test/resources/test.properties
  backend/sources/facebook/connector/src/test/resources/test.properties
  backend/sources/facebook/events-router/src/test/resources/test.properties
  backend/sources/google/connector/src/test/resources/test.properties
  backend/sources/google/events-router/src/test/resources/test.properties
  backend/sources/twilio/connector/src/test/resources/test.properties
  backend/sources/twilio/events-router/src/test/resources/test.properties
  backend/sources/viber/connector/src/test/resources/test.properties
  backend/webhook/consumer/src/test/resources/test.properties
  backend/webhook/publisher/src/test/resources/test.properties
  docs/docs/api/endpoints/chatplugin.md
  docs/docs/api/endpoints/conversations.md
  docs/docs/api/endpoints/messages.md
  docs/docs/api/webhook.md
  docs/docs/api/websocket.md
  docs/docs/sources/google.md
  lib/java/spring/web/src/main/java/co/airy/spring/web/events/KafkaListener.java
Labels: feature

#2747 [#2745] conversations.refetch endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
Labels: feature

#2752 [#2693] Docs/2693 contacts service endpoins
  docs/docs/api/contacts.md
  docs/docs/api/endpoints/conversations.md
Labels: docs

#2765 [#2715] Fixed notification badge after reload
  frontend/chat-plugin/lib/src/components/chat/index.tsx
Labels: fix

#2767 [#2764] Bug null pointer exception on api contacts service
  backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java
  lib/java/kafka/streams/src/main/java/co/airy/kafka/streams/KafkaStreamsWrapper.java
Labels: fix

#2735 [#2562] Possibility to send media/templates with text
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputSelector.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.module.scss
  lib/typescript/assets/images/icons/template-alt.svg
  lib/typescript/model/Source.ts
  lib/typescript/render/components/Audio/index.module.scss
  lib/typescript/render/components/Video/index.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/twilio/TwilioRender.tsx
Labels: feature

#2770 [#2768] Make hostname optional for frontend-ui
  frontend/ui/src/httpClient.ts
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
Labels: feature

#2772 [#2769] Added custom host url
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
Labels: feature

#2773 [#2693] contacts merge endpoint
  .gitignore
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ContactWithMergeHistoryResponsePayload.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/MergeContactsRequestPayload.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/MergeContactsTest.java
  docs/docs/api/contacts.md
Labels: feature

#2783 [#2781] endless loop for channels.list
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.tsx
  frontend/ui/src/pages/Channels/MainPage/index.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  frontend/ui/src/pages/Inbox/MessageInput/index.tsx
  lib/typescript/assets/images/icons/paperclipChatplugin.svg
  lib/typescript/assets/scss/colors.scss
Labels: bug, fix
