Repository airyhq/airy, pull requests merged in 2022-10, with the labels that each got.

#3781 [#3641] Added filtering to catalog view
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.module.scss
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/FilterCatalogModal/FilterCatalogModal.module.scss
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/FilterCatalogModal/FilterCatalogModal.tsx
  frontend/control-center/src/pages/Catalog/index.module.scss
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  lib/typescript/assets/images/icons/filterAlt.svg
  lib/typescript/components/inputs/SearchField/index.tsx
  lib/typescript/render/services/useAnimation.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3797 [#3796] fix link topbar
  frontend/inbox/src/components/TopBar/index.tsx
Labels: fix

#3803 [#3800] Minor fixes
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/FilterCatalogModal/FilterCatalogModal.tsx
  frontend/control-center/src/pages/Catalog/index.module.scss
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/ConnectNewChatPlugin.tsx
  frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappConnect.tsx
  frontend/inbox/src/components/TopBar/index.tsx
  frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  lib/typescript/components/cta/SmartButton/index.tsx
  lib/typescript/components/inputs/Input/index.tsx
  lib/typescript/components/inputs/Input/style.module.scss
  lib/typescript/components/tooltip/index.module.scss
  lib/typescript/translations/translations.ts
Labels: fix

#3778 [#3762] Cognigy connector
  backend/components/cognigy/BUILD
  backend/components/cognigy/helm/BUILD
  backend/components/cognigy/helm/Chart.yaml
  backend/components/cognigy/helm/templates/configmap.yaml
  backend/components/cognigy/helm/templates/deployment.yaml
  backend/components/cognigy/helm/templates/service.yaml
  backend/components/cognigy/helm/values.yaml
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/CognigyClient.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/CognigyClientConfig.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/CognigyConnectorService.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/MessageHandler.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/Stores.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/models/MessageSend.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/models/MessageSendResponse.java
  backend/components/cognigy/src/main/resources/application.properties
  backend/components/cognigy/src/test/java/co/airy/core/cognigy_connector/CognigyConnectorServiceTest.java
  backend/components/cognigy/src/test/resources/test.properties
  backend/components/rasa/src/main/java/co/airy/core/rasa_connector/models/AiryPayload.java
Labels: backend, feature

#3812 [#3804] Fix using existing subnets for AWS
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/gcp-gke/main.tf
  infrastructure/terraform/modules/gcp-gke/outputs.tf
  infrastructure/terraform/modules/gcp-gke/variables.tf
Labels: fix

#3818 [#3813] Fixes to SearchBar on the Control Center UI
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.module.scss
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
Labels: fix

#3821 [#3820] fixes for cognigy ai on control center
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx
  lib/typescript/assets/images/icons/cognigyLogo.svg
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: fix

#3807 [#3801] cognigy ai docs
  docs/docs/integrations/cognigy-ai.md
  docs/sidebars.js
  docs/static/img/integrations/cognigy/flow.png
  docs/static/img/integrations/cognigy/messagingExample.png
  lib/typescript/translations/translations.ts
Labels: docs

#3761 Feature/3693 api components installer
  BUILD
  backend/components/installer/BUILD
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/CatalogHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/HelmJobHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstalledComponentsHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerController.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/JobEmptyException.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/NotCompletedException.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/config/InstalledComponentsCache.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/config/K8sClientConfig.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/Component.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentDetails.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/Repository.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/payload/InstallPayload.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/payload/UninstallPayload.java
  backend/components/installer/src/main/resources/application.properties
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallerHandlerTest.java
  backend/components/installer/src/test/resources/helm-install-cmd.txt
  backend/components/installer/src/test/resources/repositories.json
  backend/components/installer/src/test/resources/test.properties
  docs/docs/api/endpoints/components.md
  infrastructure/helm-chart/templates/components/api-components-installer/configmap.yaml
  infrastructure/helm-chart/templates/components/api-components-installer/deployment.yaml
  infrastructure/helm-chart/templates/components/api-components-installer/service.yaml
  infrastructure/helm-chart/templates/components/ingress.yaml
  infrastructure/helm-chart/templates/controller/ingress.yaml
  infrastructure/helm-chart/values.yaml
  maven_install.json
  repositories.bzl
Labels: feature

#3834 [#3822] Added Notification Configurations
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3840 [#3839] Adapted connectors useSelector according components.get response
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx
  frontend/control-center/src/selectors/connectors.ts
  frontend/control-center/src/services/format.ts
Labels: fix

#3836 [#3835] Fix unread counter crash
  backend/components/unread-counter/src/main/java/co/airy/core/unread_counter/dto/UnreadCountState.java
Labels: fix

#3826 [#3825] support cognigy ai non text flow nodes
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/MessageHandler.java
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/models/MessageSendResponse.java
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/chatPluginModel.ts
  lib/typescript/render/providers/chatplugin/components/QuickReplies/index.module.scss
  lib/typescript/render/providers/chatplugin/components/QuickReplies/index.tsx
  lib/typescript/render/providers/meta/MetaRender.tsx
Labels: backend, feature

#3849 [#3719] Updating all Source Connector
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
Labels: fix

#3859 [#3642] Added tooltips to channel connectors
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx
  lib/typescript/components/tooltip/index.module.scss
  lib/typescript/components/tooltip/index.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3863 [#3862] Fixed icons and improved animations
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.module.scss
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/inbox/src/components/TopBar/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactInformation/index.module.scss
  frontend/inbox/src/pages/Inbox/ConversationListHeader/index.module.scss
  frontend/inbox/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  lib/typescript/assets/scss/animations.scss
  lib/typescript/components/inputs/SearchField/index.tsx
Labels: fix

#3876 [#3836] Hotfix crashing whatsapp
  VERSION
  backend/components/rasa/helm/BUILD
  backend/components/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/Stores.java
  backend/components/whatsapp/connector/src/main/resources/application.properties
  backend/components/whatsapp/helm/templates/deployments.yaml
  docs/docs/changelog.md
Labels: fix

#3870 [#3861] IBM Watson assistant connector backend
  backend/components/ibm-watson-assistant/BUILD
  backend/components/ibm-watson-assistant/helm/BUILD
  backend/components/ibm-watson-assistant/helm/Chart.yaml
  backend/components/ibm-watson-assistant/helm/templates/configmap.yaml
  backend/components/ibm-watson-assistant/helm/templates/deployment.yaml
  backend/components/ibm-watson-assistant/helm/templates/service.yaml
  backend/components/ibm-watson-assistant/helm/values.yaml
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/IbmWatsonAssistantClient.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/IbmWatsonAssistantClientConfig.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/IbmWatsonAssistantConnectorService.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/MessageHandler.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/Stores.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/models/MessageSend.java
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm-watson-assistant-connector/models/MessageSendResponse.java
  backend/components/ibm-watson-assistant/src/main/resources/application.properties
  backend/components/ibm-watson-assistant/test/java/co/airy/core/ibm-watson-assistant_connector/IbmWatsonAssistantConnectorServiceTest.java
  backend/components/ibm-watson-assistant/test/resources/test.properties
Labels: feature

#3887 [#3883] Feature add pending status to components.list call
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/CatalogHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstalledComponentsHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentDetails.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/InstallationStatus.java
  backend/components/installer/src/main/resources/application.properties
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallerHandlerTest.java
Labels: feature

#3891 [#3885] Whatsapp connector !config error
  frontend/control-center/src/pages/Connectors/ChannelCard/index.module.scss
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
Labels: fix

#3898 [#3894] fixes for ibm watson assistant
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: fix
