Repository airyhq/airy, pull requests merged in 2022-03, with the labels that each got.

#2896 [#2627] prevent 404 responses for the messages send endpoint
  backend/api/communication/src/main/java/co/airy/core/api/communication/AsyncSendMessagesHandler.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
  backend/api/communication/src/main/resources/application.properties
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/api/communication/src/test/resources/test.properties
  docs/docs/api/endpoints/messages.md
Labels: feature

#2911 [#2909] Fix restore from backup inconsistencies
  docs/docs/guides/backup.md
  docs/docs/guides/component-reset.md
  docs/sidebars.js
Labels: docs

#2921 [#2920] UI fixes
  frontend/chat-plugin/lib/src/components/chat/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/AudioRecording/WaveformAudio.tsx
Labels: fix

#2919 [#2918] Resend messages
  backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java
  backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ResendMessageRequestPayload.java
  backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java
  backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java
  docs/docs/api/endpoints/messages.md
Labels: feature

#2879 Point custom instance from UI local
  .env.example
  .gitignore
  WORKSPACE
  lib/typescript/websocketclient/index.ts
  package.json
  scripts/web-dev.sh
  yarn.lock
Labels: chore

#2924 [#2774] Fix: point staging from UI local
  WORKSPACE
  package.json
  yarn.lock
Labels: chore

#2929 [#2929] Rename draft release on finish
  scripts/release.sh
Labels: fix

#2934 [#2933] fix inbound audio messages bug
  frontend/ui/src/pages/Inbox/MessageInput/AudioRecording/index.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.module.scss
  frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
  lib/typescript/components/general/AudioClip/index.module.scss
  lib/typescript/components/general/AudioClip/index.tsx
  lib/typescript/components/general/AudioClip/services/decodeAudioData.ts
  lib/typescript/components/general/AudioClip/services/drawCanvasPaths.ts
  lib/typescript/components/general/AudioClip/services/generateRandomFrequencies.ts
  lib/typescript/components/general/AudioClip/services/index.ts
  lib/typescript/components/message/MessageInfoWrapper/index.module.scss
  lib/typescript/components/message/MessageInfoWrapper/index.tsx
Labels: fix

#2950 Bump @bazel/typescript from 4.6.1 to 5.2.0
  WORKSPACE
  bazel.tsconfig.json
  frontend/chat-plugin/bazel.tsconfig.json
  frontend/chat-plugin/deps.bzl
  frontend/chat-plugin/dev/BUILD
  frontend/chat-plugin/image/BUILD
  frontend/chat-plugin/lib/BUILD
  frontend/ui/BUILD
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.tsx
  integration/BUILD
  integration/chat-plugin/BUILD
  integration/ui/BUILD
  lib/typescript/dates/BUILD
  lib/typescript/httpclient/BUILD
  lib/typescript/model/BUILD
  lib/typescript/types/BUILD
  lib/typescript/types/global.d.ts
  lib/typescript/websocketclient/BUILD
  package.json
  tools/build/npm/README.md
  tools/build/npm/assemble.py
  tools/build/npm/rules.bzl
  tsconfig.json
  yarn.lock
Labels: dependencies, chore, javascript

#2955 Bump jvm rules external
  WORKSPACE
  maven_install.json
  repositories.bzl
Labels: dependencies, chore

#2838 [#2195] Move tag settings from frontend to backend
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/payload/ClientConfigResponsePayload.java
  backend/api/admin/src/main/resources/tagConfig.json
  backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java
  frontend/ui/src/App.tsx
  frontend/ui/src/actions/channel/index.ts
  frontend/ui/src/actions/config/index.ts
  frontend/ui/src/actions/conversations/index.ts
  frontend/ui/src/actions/conversationsFilter/index.ts
  frontend/ui/src/actions/index.ts
  frontend/ui/src/actions/messages/index.ts
  frontend/ui/src/actions/metadata/index.ts
  frontend/ui/src/actions/settings/index.tsx
  frontend/ui/src/actions/tags/index.tsx
  frontend/ui/src/actions/templates/index.ts
  frontend/ui/src/components/AiryWebsocket/index.tsx
  frontend/ui/src/components/ColorSelector.tsx
  frontend/ui/src/components/Tag/index.tsx
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/ChannelListItem/index.tsx
  frontend/ui/src/pages/Channels/ConnectedChannelsList/index.tsx
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.tsx
  frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx
  frontend/ui/src/pages/Channels/index.tsx
  frontend/ui/src/pages/Inbox/ConversationList/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx
  frontend/ui/src/pages/Inbox/ConversationListItem/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/index.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/Popup.tsx
  frontend/ui/src/pages/Inbox/QuickFilter/index.tsx
  frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx
  frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx
  frontend/ui/src/pages/Inbox/index.tsx
  frontend/ui/src/pages/Tags/FAKESETTINGS.ts
  frontend/ui/src/pages/Tags/TableRow.tsx
  frontend/ui/src/pages/Tags/index.tsx
  frontend/ui/src/reducers/data/config/index.ts
  frontend/ui/src/reducers/data/index.ts
  frontend/ui/src/reducers/data/settings/index.ts
  frontend/ui/src/reducers/index.ts
  frontend/ui/src/selectors/conversations.ts
  frontend/ui/src/services/image/index.ts
  lib/typescript/httpclient/src/endpoints/getConfig.ts
  lib/typescript/model/Config.ts
Labels: feature

#2935 [#248] userid for all telemetry events
  cli/pkg/cmd/create/create.go
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/minikube.go
Labels: feature

#2967 [#2936] Added control-center structure
  WORKSPACE
  frontend/control-center/BUILD
  frontend/control-center/development.html
  frontend/control-center/handles/BUILD
  frontend/control-center/index.html
  frontend/control-center/nginx.conf
  frontend/control-center/public/BUILD
  frontend/control-center/public/favicon.ico
  frontend/control-center/public/manifest.json
  frontend/control-center/src/App.module.scss
  frontend/control-center/src/App.tsx
  frontend/control-center/src/actions/channel/index.ts
  frontend/control-center/src/actions/config/index.ts
  frontend/control-center/src/actions/index.ts
  frontend/control-center/src/actions/metadata/index.ts
  frontend/control-center/src/components/Sidebar/index.module.scss
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/env.ts
  frontend/control-center/src/httpClient.ts
  frontend/control-center/src/index.scss
  frontend/control-center/src/index.tsx
  frontend/control-center/src/reducers/data/channels/index.ts
  frontend/control-center/src/reducers/data/config/index.ts
  frontend/control-center/src/reducers/data/index.ts
  frontend/control-center/src/reducers/data/user/index.ts
  frontend/control-center/src/reducers/index.ts
  frontend/control-center/src/routes/routes.ts
  frontend/control-center/src/store.ts
Labels: feature

#2940 Upgrade to Kafka 3.1.0
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/Chart.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/_helpers.tpl
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/values.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/Chart.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/_helpers.tpl
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/headless-service.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/service.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/statefulset.yaml
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/values.yaml
  infrastructure/helm-chart/templates/config/kafka.yaml
  infrastructure/helm-chart/templates/provisioning/job-kafka.yaml
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  infrastructure/helm-chart/values.yaml
  infrastructure/images/kafka/Dockerfile
  infrastructure/images/kafka/Makefile
  infrastructure/images/kafka/config/server.properties
  infrastructure/images/kafka/config/zookeeper.properties
  infrastructure/images/kafka/scripts/configure-kafka.sh
  infrastructure/images/kafka/scripts/configure-zookeeper.sh
  infrastructure/images/kafka/scripts/entrypoint.sh
  infrastructure/terraform/main/files/defaultResourceLimits.yaml
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
Labels: feature

#2972 add language key metadata
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java
Labels: feature

#2969 [#2942] contacts cypress test
  frontend/ui/handles/index.ts
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/ContactInfoPoint.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/Expandable.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  integration/ui/contact_edit.spec.ts
Labels: testing

#2975 Fix bug introduced in PR #2950
  bazel.tsconfig.json
  frontend/ui/src/components/Tag/index.tsx
Labels: fix
