Repository airyhq/airy, pull requests merged in 2022-08, with the labels that each got.

#3482 Feature/3353 components.list endpoint version 2
  go.mod
  infrastructure/controller/pkg/cache/BUILD
  infrastructure/controller/pkg/cache/deployed_charts.go
  infrastructure/controller/pkg/endpoints/BUILD
  infrastructure/controller/pkg/endpoints/components_install_uninstall.go
  infrastructure/controller/pkg/endpoints/components_list.go
  infrastructure/controller/pkg/endpoints/components_update.go
  infrastructure/controller/pkg/endpoints/server.go
Labels: feature

#3512 [#3511] Update helm repo before install or upgrade
  docs/docs/getting-started/installation/helm.md
  docs/docs/getting-started/upgrade.md
Labels: fix

#3521 [#3373] Document how we work with rules_go, gazelle, and update-deps
  docs/docs/guides/contributing.md
Labels: docs

#3531 [#2755] Add an "airy login" command to the CLI
  cli/integration/golden/cli.no-args.golden
  cli/pkg/cmd/BUILD
  cli/pkg/cmd/config/config.go
  cli/pkg/cmd/login/BUILD
  cli/pkg/cmd/login/login.go
  cli/pkg/cmd/root.go
  cli/pkg/cmd/status/status.go
  docs/docs/cli/usage.md
  lib/go/httpclient/httpclient.go
Labels: feature

#3404 [#3397] Airy CLI Installation with Terraform
  .gitignore
  BUILD
  cli/go.mod
  cli/go.sum
  cli/pkg/cmd/create/create.go
  cli/pkg/cmd/status/BUILD
  cli/pkg/cmd/status/status.go
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  cli/pkg/workspace/init.go
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/terraform.md
  docs/sidebars.js
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/terraform/install/airy-core/main.tf
  infrastructure/terraform/install/airy-core/outputs.tf
  infrastructure/terraform/install/airy-core/variables.tf
  tools/update-deps/go.mod
  tools/update-deps/go.sum
Labels: feature

#3537 [#3533] Connect whatsapp channels
  backend/sources/whatsapp/connector/BUILD
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/ChannelsController.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/Connector.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/Stores.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/WebhookController.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/Api.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/ApiException.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/model/LongLivingUserAccessToken.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/dto/Conversation.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/dto/SendMessageRequest.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/ConnectChannelRequestPayload.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/DisconnectChannelRequestPayload.java
  backend/sources/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/ChannelsControllerTest.java
  backend/sources/whatsapp/connector/src/test/resources/test.properties
  docs/docs/api/endpoints/channels.md
  docs/docs/api/endpoints/components.md
  docs/docs/api/endpoints/connect-whatsapp.mdx
  docs/docs/sources/whatsapp-cloud.md
  docs/sidebars.js
  infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/templates/deployments.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/values.yaml
  infrastructure/helm-chart/charts/components/templates/ingress.yaml
  infrastructure/helm-chart/charts/ingress-controller/templates/ngrok.yaml
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/source/SourceWhatsappEvents.java
Labels: feature

#3547 [#3541] Rename Terraform Module to `airy_core`
  infrastructure/terraform/install/airy-core/main.tf
  infrastructure/terraform/install/aws-eks/variables.tf
Labels: fix

#3363 [#3356] Create and destroy Minikube with Bazel
  WORKSPACE
  infrastructure/BUILD
Labels: feature

#3557 [#3402] adjust catalog view to remove install and uninstalled title
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/InfoCard/index.module.scss
  frontend/control-center/src/components/InfoCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/getRouteForCard.ts
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemList.tsx
  frontend/control-center/src/pages/Catalog/index.module.scss
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/index.tsx
  frontend/control-center/src/pages/Webhooks/EmptyState/index.tsx
  frontend/control-center/src/reducers/data/catalog/index.ts
  frontend/control-center/src/routes/routes.ts
  frontend/control-center/src/services/format.ts
  frontend/control-center/src/services/getComponentStatus.ts
  lib/typescript/assets/images/icons/checkmarkFilled.svg
  lib/typescript/assets/scss/colors.scss
  lib/typescript/components/alerts/SettingsModal/ModalHeader.module.scss
  lib/typescript/components/alerts/SettingsModal/index.tsx
  lib/typescript/components/cta/Button/index.tsx
  lib/typescript/components/cta/Button/style.module.scss
  lib/typescript/components/general/TabsPanel/index.module.scss
  lib/typescript/components/general/TabsPanel/index.tsx
  lib/typescript/components/general/index.ts
  lib/typescript/components/index.ts
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
  lib/typescript/components/wrapper/ContentWrapper/index.tsx
  lib/typescript/model/Components.ts
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3559 [#3540] Simplify the spanish flag to reduce bundle size
  lib/typescript/assets/images/icons/flagFrance.svg
  lib/typescript/assets/images/icons/flagGermany.svg
  lib/typescript/assets/images/icons/flagSpain.svg
  lib/typescript/assets/images/icons/flagUS.svg
Labels: chore

#3562 [#3530] airy controller component name mapping
  infrastructure/controller/pkg/endpoints/components_update.go
  lib/go/k8s/configmaps.go
Labels: fix

#3564 [#3563] update components.get handling
  frontend/control-center/src/components/SourceInfo/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/reducers/data/connector/index.ts
  lib/typescript/model/Source.ts
Labels: fix

#3573 [#3572] Hotfix - Use only Kafka when provisioning topics
  VERSION
  docs/docs/changelog.md
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
Labels: fix

#3569 [#3489] component card details on catalog
  frontend/control-center/src/App.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Catalog/getRouteForCard.ts
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/routes/routes.ts
  lib/typescript/components/cta/Button/index.tsx
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
  lib/typescript/components/wrapper/ContentWrapper/index.tsx
  lib/typescript/model/Components.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3577 [#3575] Fix Kafka topics provisioning
  VERSION
  docs/docs/changelog.md
  infrastructure/helm-chart/templates/provisioning/job-kafka.yaml
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
Labels: fix

#3588 [#3508] Fix empty state connectors
  frontend/control-center/src/components/InfoCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Catalog/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Webhooks/WebhooksListItem/index.tsx
  frontend/control-center/src/pages/Webhooks/index.tsx
  lib/typescript/components/alerts/Notification/index.module.scss
  lib/typescript/components/alerts/Notification/index.tsx
  lib/typescript/components/alerts/SettingsModal/index.tsx
  lib/typescript/components/alerts/SettingsModal/style.module.scss
  lib/typescript/components/alerts/index.ts
  lib/typescript/model/Modal.ts
  lib/typescript/model/Notification.ts
  lib/typescript/model/index.ts
  lib/typescript/translations/translations.ts
Labels: fix

#3576 [#3571] update dialogflow configuration form
  docs/docs/api/endpoints/components.md
  frontend/control-center/src/components/SourceInfo/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectNewDialogflow.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3574 [#3558] Docs for Contributing and Defining Components
  docs/docs/getting-started/componentDefinition.mdx
  docs/docs/getting-started/components.md
  docs/docs/getting-started/glossary.md
  docs/docs/guides/contributing-components.md
  docs/docs/guides/contributing-to-airy.md
  docs/sidebars.js
Labels: docs

#3592 [#3589] Retrieve installed components from cm
  docs/docs/api/endpoints/components.md
  docs/docs/getting-started/components.md
  infrastructure/controller/pkg/endpoints/components_install_uninstall.go
  infrastructure/controller/pkg/endpoints/components_list.go
  infrastructure/controller/pkg/endpoints/components_update.go
  lib/go/k8s/configmaps.go
Labels: fix

#3604 [#3603] Fix integration-source-api helm code
  backend/sources/api/helm/templates/deployment.yaml
Labels: fix

#3601 [#3591] Enhancement enable/disable
  frontend/control-center/src/App.module.scss
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  lib/typescript/components/general/Pagination/index.tsx
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
  lib/typescript/model/Screen.ts
  lib/typescript/model/index.ts
  lib/typescript/translations/translations.ts
Labels: fix

#3602 [#3600] display all components in catalog
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Catalog/getRouteForCard.ts
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/routes/routes.ts
  lib/typescript/assets/images/icons/ameliaLogo.svg
  lib/typescript/assets/images/icons/congnigyLogo.svg
  lib/typescript/assets/images/icons/rasaLogo.svg
  lib/typescript/assets/images/icons/viber.svg
  lib/typescript/assets/images/icons/viberLogoFilled.svg
  lib/typescript/components/general/ConnectorAvatar/index.tsx
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: fix

#3607 [#3606] logo fix
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
Labels: fix

#3610 [#3605] Fix connectors connected channels
  frontend/control-center/src/components/SourceInfo/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/CustomiseSection.tsx
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
  lib/typescript/translations/translations.ts
Labels: fix

#3612 Fix chatplugin preview url
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/CustomiseSection.tsx
Labels: fix

#3614 [#3534] Whatsapp: Receive messages
  backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java
  backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/ChannelsController.java
  backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/ConnectChannelRequestPayload.java
  backend/sources/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/ChannelsControllerTest.java
  backend/sources/whatsapp/events-router/BUILD
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/EventsRouter.java
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/MessageMapper.java
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/dto/Event.java
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/Value.java
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/WebhookEntry.java
  backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/WebhookEvent.java
  backend/sources/whatsapp/events-router/src/test/java/co/airy/core/sources/whatsapp/EventsRouterTest.java
  backend/sources/whatsapp/events-router/src/test/resources/image.json
  backend/sources/whatsapp/events-router/src/test/resources/status.json
  backend/sources/whatsapp/events-router/src/test/resources/test.properties
  backend/sources/whatsapp/events-router/src/test/resources/text.json
  backend/sources/whatsapp/helm/templates/deployments.yaml
  docs/docs/api/endpoints/connect-whatsapp.mdx
  docs/docs/concepts/release-process.md
  docs/docs/sources/whatsapp-cloud.md
  tools/build/npm/templates/deploy.py
Labels: feature

#3637 [#3634] Support whatsApp source in the render library
  frontend/inbox/src/components/IconChannel/index.tsx
  lib/typescript/model/Source.ts
  lib/typescript/render/SourceMessage.tsx
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/outbound/index.ts
  lib/typescript/render/outbound/whatsapp.ts
Labels: fix

#3636 [#3609] Added catch for promises
  frontend/control-center/src/actions/channel/index.ts
  frontend/control-center/src/components/InfoCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CreateUpdateSection/CreateUpdateSection.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/CustomiseSection.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/InputToggleSection/index.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Instagram/InstagramConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Instagram/InstagramConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Twilio/SMS/TwilioSmsConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Twilio/TwilioConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Twilio/WhatsApp/TwilioWhatsappConnect.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Inbox/ChannelsList/ChannelListItem/index.tsx
  frontend/control-center/src/pages/Status/index.tsx
  frontend/control-center/src/pages/Webhooks/index.tsx
  frontend/control-center/src/reducers/data/channels/index.ts
  frontend/inbox/src/App.tsx
  frontend/inbox/src/reducers/data/channels/index.ts
  lib/typescript/components/cta/SmartButton/index.module.scss
  lib/typescript/components/cta/SmartButton/index.tsx
  lib/typescript/components/cta/index.ts
  lib/typescript/components/general/Pagination/index.tsx
  lib/typescript/model/Notification.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3624 [#3560] control center remove sources info component
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/Description/index.tsx
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/SourceInfo/index.tsx
  frontend/control-center/src/components/index.ts
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/InfoCard/index.module.scss
  frontend/control-center/src/pages/Connectors/InfoCard/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Inbox/index.module.scss
  frontend/control-center/src/pages/Inbox/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
  frontend/control-center/src/pages/Status/index.tsx
  frontend/control-center/src/routes/routes.ts
  frontend/control-center/src/services/format.ts
  frontend/control-center/src/services/getRouteForCard.ts
  frontend/control-center/src/services/index.ts
  frontend/inbox/handles/index.ts
  lib/typescript/model/Components.ts
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: fix

#3635 [#3613] docs about cypress testing
  docs/docs/ui/control-center/introduction.md
  docs/docs/ui/inbox/introduction.md
  docs/docs/ui/testing/integration-testing.md
  docs/sidebars.js
  docs/static/img/ui/controlCenterCatalog.png
  docs/static/img/ui/controlCenterConnectors.png
  docs/static/img/ui/controlCenterStatus.png
  docs/static/img/ui/cypressDashboard.png
Labels: docs

#3639 [#3638] Added last refresh on Status page
  frontend/control-center/src/pages/Status/index.module.scss
  frontend/control-center/src/pages/Status/index.tsx
Labels: feature

#3647 [#3491] Added Whatsapp Business Cloud
  frontend/control-center/src/App.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/InfoCard/index.module.scss
  frontend/control-center/src/pages/Connectors/InfoCard/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectNewDialogflow.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectorDialogflow.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/DialogflowConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx
  frontend/control-center/src/pages/Connectors/Providers/Twilio/TwilioConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/ConnectorWhatsappBusinessCloud.tsx
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappBusinessCloudConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappBusinessCloudConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  lib/typescript/components/alerts/NotificationComponent/index.tsx
  lib/typescript/model/Components.ts
  lib/typescript/model/Connectors.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3660 [#3631] control center reorganize routing for connectors
  frontend/control-center/src/App.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorsOutlet.tsx
  frontend/control-center/src/pages/Connectors/InfoCard/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/ConnectNewChatPlugin.tsx
  frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CreateUpdateSection/CreateUpdateSection.tsx
  frontend/control-center/src/routes/routes.ts
  frontend/control-center/src/services/getRouteForCard.ts
  lib/typescript/model/Components.ts
Labels: fix
