Repository airyhq/airy, pull requests merged in 2022-06, with the labels that each got.

#3233 [#3101] Added contacts to Inbox
  frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx
  frontend/inbox/src/App.tsx
  frontend/inbox/src/actions/contacts/index.ts
  frontend/inbox/src/components/Sidebar/index.tsx
  frontend/inbox/src/components/TopBar/index.tsx
  frontend/inbox/src/pages/Contacts/ContactDetails/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactDetails/index.tsx
  frontend/inbox/src/pages/Contacts/ContactInformation/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx
  frontend/inbox/src/pages/Contacts/ContactListItem/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactListItem/index.tsx
  frontend/inbox/src/pages/Contacts/DeleteContactModal/index.module.scss
  frontend/inbox/src/pages/Contacts/DeleteContactModal/index.tsx
  frontend/inbox/src/pages/Contacts/index.module.scss
  frontend/inbox/src/pages/Contacts/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/ContactInfoPoint.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/util/fillContactInfo.ts
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/inbox/src/pages/Inbox/NoConversations/index.tsx
  frontend/inbox/src/reducers/data/contacts/index.ts
  frontend/inbox/src/routes/routes.ts
  lib/typescript/assets/images/icons/airyContactIcon.svg
  lib/typescript/assets/images/icons/contactIcon.svg
  lib/typescript/assets/images/icons/facebookContactIcon.svg
  lib/typescript/assets/images/icons/googleContactIcon.svg
  lib/typescript/assets/images/icons/instagramContactIcon.svg
  lib/typescript/assets/images/icons/trash.svg
  lib/typescript/assets/images/icons/twilioSmsContactIcon.svg
  lib/typescript/assets/images/icons/twilioWhatsappContactIcon.svg
  lib/typescript/assets/scss/animations.scss
  lib/typescript/components/BUILD
  lib/typescript/components/general/Pagination/index.module.scss
  lib/typescript/components/general/Pagination/index.tsx
  lib/typescript/components/general/index.ts
  lib/typescript/httpclient/src/client.ts
  lib/typescript/httpclient/src/endpoints/deleteContact.ts
  lib/typescript/httpclient/src/endpoints/getContactDetails.ts
  lib/typescript/httpclient/src/endpoints/index.ts
  lib/typescript/httpclient/src/endpoints/listContacts.ts
  lib/typescript/httpclient/src/endpoints/updateContactDetails.ts
  lib/typescript/httpclient/src/payload/GetContactDetailsRequestPayload.ts
  lib/typescript/httpclient/src/payload/ListContactsRequestPayload.ts
  lib/typescript/httpclient/src/payload/index.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3235 [#3234] Sort contacts alphabetically
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
Labels: feature

#3237 [#3030] Added enabled service component check
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/inbox/src/App.tsx
  frontend/inbox/src/components/Sidebar/index.tsx
  lib/typescript/model/Config.ts
Labels: feature

#3242 [#3241] Fixed staging crashing
  frontend/control-center/src/components/Sidebar/index.module.scss
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/inbox/src/components/Sidebar/index.module.scss
  frontend/inbox/src/components/Sidebar/index.tsx
Labels: fix

#3244 Chore/upgrade go to 1.18.2
  WORKSPACE
  cli/go.mod
  cli/go.sum
  cli/integration/golden/cli.no-args.golden
  cli/pkg/providers/aws/aws.go
  docs/cli-doc/go.mod
  docs/docs/api/endpoints/components.md
  go.mod
  go.sum
  go_repositories.bzl
  infrastructure/controller/go.mod
  infrastructure/controller/go.sum
  infrastructure/lib/go/k8s/handler/go.mod
  infrastructure/lib/go/k8s/handler/go.sum
  infrastructure/lib/go/k8s/util/go.mod
  infrastructure/lib/go/k8s/util/go.sum
  lib/go/httpclient/client.go
  lib/go/httpclient/cluster.go
  lib/go/httpclient/components.go
  lib/go/httpclient/go.mod
  lib/go/httpclient/httpclient.go
  tools/update-deps/go.mod
  tools/update-deps/go.sum
Labels: chore

#3250 [#3227] darkmode fix on safari
  lib/typescript/components/inputs/Toggle/index.tsx
Labels: fix

#3232 [#3228] control center fix status view
  frontend/control-center/src/components/Sidebar/index.module.scss
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
Labels: fix

#3259 [#3249] fixed bug contacts
  frontend/inbox/src/actions/contacts/index.ts
  frontend/inbox/src/pages/Contacts/ContactDetails/index.tsx
  frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx
  frontend/inbox/src/pages/Contacts/ContactListItem/index.tsx
  frontend/inbox/src/pages/Contacts/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  frontend/inbox/src/reducers/data/contacts/index.ts
  lib/typescript/components/inputs/Input/index.tsx
  lib/typescript/httpclient/src/endpoints/updateContactDetails.ts
Labels: fix

#3260 [#3258] Fix airy create on AWS
  cli/pkg/cmd/create/create.go
  cli/pkg/providers/aws/kubeConfigTemplate.yaml
  docs/docs/cli/usage.md
  scripts/dev_cli.sh
Labels: fix

#3268 [#3267] Putting components.* endpoints behind auth
  VERSION
  docs/docs/changelog.md
  docs/docs/concepts/release-process.md
  docs/docs/getting-started/installation/security.md
  infrastructure/controller/pkg/endpoints/server.go
Labels: fix

#3245 [#3178] feature/3178-enable-disable-componets-from-control-center
  infrastructure/controller/BUILD
  infrastructure/controller/pkg/configmap-controller/BUILD
  infrastructure/controller/pkg/configmap-controller/create.go
  infrastructure/controller/pkg/configmap-controller/update.go
  infrastructure/controller/pkg/endpoints/cluster_update.go
  infrastructure/controller/pkg/endpoints/components_get.go
  infrastructure/controller/pkg/endpoints/components_update.go
  infrastructure/lib/go/k8s/handler/deployments.go
  lib/go/k8s/configmaps.go
Labels: feature

#3298 [#3292] french translations UI fix
  lib/typescript/translations/translations.ts
Labels: fix

#3297 [#3178] Fix scald-down logic for components
  infrastructure/controller/pkg/configmap-controller/update.go
Labels: fix

#3304 [#3283] google survey response fix
  lib/typescript/render/providers/google/GoogleRender.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3309 [#3308] Terrraform installation bugs fix
  infrastructure/terraform/airy-core/files/airyConfig.yaml
  infrastructure/terraform/airy-core/files/defaultResourceLimits.yaml
  infrastructure/terraform/airy-core/main.tf
  infrastructure/terraform/airy-core/variables.tf
  infrastructure/terraform/demos/analytics/main.tf
  infrastructure/terraform/kubernetes/variables.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
Labels: fix

#3340 [#3339] Improve commit message
  docs/docs/guides/contributing.md
Labels: docs

#3338 [#3333] - Update kubeconfig api version
  infrastructure/terraform/modules/aws_eks/main.tf
Labels: fix

#3335 [#3332] Authenticate AWS using profile
  infrastructure/terraform/kubernetes/main.tf
  infrastructure/terraform/kubernetes/variables.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
Labels: feature

#3341 [#3279] Clarifications to minikube install
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#3320 [#3296] Update Concepts Architecture Docs
  docs/docs/concepts/architecture.md
Labels: docs

#3303 [#3208] Initial setup for helm chart per component
  docs/docs/api/endpoints/components.md
  docs/docs/api/endpoints/repositories.md
  docs/docs/concepts/architecture.md
  docs/docs/getting-started/components.md
  docs/docs/getting-started/installation/introduction.md
  infrastructure/helm-chart/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/sources/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/BUILD
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/templates/backend/service.yaml
  infrastructure/helm-chart/charts/components/charts/sources/charts/chatplugin/values.yaml
  infrastructure/helm-chart/charts/components/charts/sources/values.yaml
  infrastructure/helm-chart/templates/config/configmap.yaml
  infrastructure/helm-chart/templates/controller/configmap.yaml
  infrastructure/helm-chart/templates/controller/deployment.yaml
Labels: feature

#3347 Fix/3343 components.get does not responds with all compoenents
  infrastructure/controller/pkg/endpoints/components_get.go
  lib/go/k8s/configmaps.go
Labels: fix

#3349 [#3334] Terraform module improvements
  infrastructure/terraform/modules/aws_eks/outputs.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/outputs.tf
Labels: feature

#3350 [#3316] Added emptyState contacts
  frontend/inbox/src/pages/Contacts/EmptyState/index.module.scss
  frontend/inbox/src/pages/Contacts/EmptyState/index.tsx
  frontend/inbox/src/pages/Contacts/index.tsx
  lib/typescript/assets/images/icons/emptyContactIcon.svg
  lib/typescript/translations/translations.ts
Labels: feature

#3355 [#3315] Added webhooks emptyState
  frontend/control-center/src/pages/Webhooks/EmptyState/index.module.scss
  frontend/control-center/src/pages/Webhooks/EmptyState/index.tsx
  frontend/control-center/src/pages/Webhooks/index.tsx
  lib/typescript/components/wrapper/ContentWrapper/index.module.scss
  lib/typescript/components/wrapper/ContentWrapper/index.tsx
  lib/typescript/translations/translations.ts
Labels: feature

#3351 [#3334] Terraform install in two environments: AWS-EKS
  .gitignore
  infrastructure/terraform/airy-core/files/airyConfig.yaml
  infrastructure/terraform/airy-core/main.tf
  infrastructure/terraform/airy-core/variables.tf
  infrastructure/terraform/install/airy-core/files/defaultResourceLimits.yaml
  infrastructure/terraform/install/airy-core/main.tf
  infrastructure/terraform/install/airy-core/outputs.tf
  infrastructure/terraform/install/airy-core/state.tf
  infrastructure/terraform/install/airy-core/variables.tf
  infrastructure/terraform/install/aws-eks/main.tf
  infrastructure/terraform/install/aws-eks/outputs.tf
  infrastructure/terraform/install/aws-eks/state.tf
  infrastructure/terraform/install/aws-eks/variables.sh
  infrastructure/terraform/install/aws-eks/variables.tf
  infrastructure/terraform/install/install.flags
  infrastructure/terraform/install/install.sh
  infrastructure/terraform/install/uninstall.sh
  infrastructure/terraform/kubernetes/main.tf
  infrastructure/terraform/kubernetes/outputs.tf
  infrastructure/terraform/modules/aws_eks/main.tf
  infrastructure/terraform/modules/aws_eks/variables.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/outputs.tf
Labels: feature
