Repository airyhq/airy, pull requests merged in 2022-02, with the labels that each got.

#2786 [#2641] Internally display message sender
  frontend/chat-plugin/lib/src/components/chat/index.tsx
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/components/message/MessageInfoWrapper/index.module.scss
  lib/typescript/components/message/MessageInfoWrapper/index.tsx
  lib/typescript/model/Message.ts
Labels: feature

#2803 [#634] http client library documentation
  docs/docs/api/httpClient.md
  docs/docs/api/introduction.md
  docs/sidebars.js
  docs/static/icons/package.svg
Labels: docs

#2798 [#2766] ReactMarkdown error
  lib/typescript/components/message/MessageInfoWrapper/index.module.scss
  lib/typescript/components/message/MessageInfoWrapper/index.tsx
  lib/typescript/render/SourceMessagePreview.tsx
  lib/typescript/render/providers/facebook/components/InstagramShare/index.module.scss
  lib/typescript/render/providers/facebook/components/InstagramShare/index.tsx
  yarn.lock
Labels: fix

#2792 [#2791] Contacts service should be off by default
  backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java
  backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ImportContactsResponsePayload.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java
  backend/api/contacts/src/test/java/co/airy/core/contacts/MergeContactsTest.java
  docs/docs/api/contacts-response-payload.md
  docs/docs/api/contacts.md
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
Labels: fix

#2828 [#2827] Fix bug in the chatplugin dev environment
  WORKSPACE
Labels: fix

#2830 [#2612] Update ClusterIssuer resource
  infrastructure/helm-chart/charts/ingress-controller/templates/letsencrypt.yaml
Labels: fix

#2831 [#2602] Upgrade PodDisruptionBudget resource
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
Labels: fix

#2824 [#2652] Add telemetry docs
  docs/docs/concepts/telemetry.md
Labels: docs

#2835 [#2826] Added instagram echo payload to render library
  lib/typescript/render/providers/facebook/FacebookRender.tsx
  lib/typescript/render/providers/facebook/components/Buttons/index.tsx
  lib/typescript/render/providers/facebook/facebookModel.ts
Labels: fix

#2837 [#2836] Disable api-contacts by default
  infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
Labels: fix

#2832 [#2809] Added custom fonts to Chatplugin
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
  frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.module.scss
  frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
  frontend/chat-plugin/lib/src/components/chat/index.module.scss
  frontend/chat-plugin/lib/src/components/dragAndDrop/index.module.scss
  frontend/chat-plugin/lib/src/components/modal/index.module.scss
  frontend/chat-plugin/lib/src/components/newConversation/index.module.scss
  frontend/chat-plugin/lib/src/config.ts
  frontend/ui/src/App.module.scss
  frontend/ui/src/api/index.ts
  frontend/ui/src/assets/scss/colors.scss
  frontend/ui/src/assets/scss/fonts.scss
  frontend/ui/src/index.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss
  frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
  lib/typescript/assets/scss/fonts.scss
  lib/typescript/render/components/Text/index.module.scss
  lib/typescript/render/props.ts
  lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx
  lib/typescript/render/providers/chatplugin/components/RichCard/index.tsx
  lib/typescript/render/providers/chatplugin/components/RichText/index.tsx
Labels: feature

#2847 [#2722] Webhook subscription editable and resubscribable
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListResponsePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookUpdatePayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  docs/docs/api/webhook.md
Labels: feature

#2863 [#2861] adding instagram in the sources list
  docs/docs/sources/introduction.md
  docs/sidebars.js
  docs/static/icons/instagram.svg
Labels: docs

#2878 [#2877] Fixed wrong chatplugin font
  frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
Labels: fix
