Repository airyhq/airy, pull requests merged in 2022-04, with the labels that each got.

#2977 [#2932] Fix the Changelog creation
  .github/workflows/release-drafter.yml
  docs/docs/concepts/release-process.md
  scripts/release.sh
Labels: chore

#2982 [#2981] add contacts docs
  docs/docs/api/endpoints/contacts-response-payload.mdx
  docs/docs/api/endpoints/contacts.md
  docs/docs/ui/channels.md
  docs/docs/ui/contacts.md
  docs/docs/ui/introduction.md
  docs/sidebars.js
  docs/static/icons/contacts.svg
  docs/static/img/ui/contacts.png
  docs/static/img/ui/contactsEdit.png
Labels: docs

#2989 [#2937] Added Component Service
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/Sidebar/index.module.scss
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/pages/Components/ComponentsListItem/index.module.scss
  frontend/control-center/src/pages/Components/ComponentsListItem/index.tsx
  frontend/control-center/src/pages/Components/index.module.scss
  frontend/control-center/src/pages/Components/index.tsx
  frontend/control-center/src/routes/routes.ts
  lib/typescript/assets/images/icons/checkmarkFilled.svg
  lib/typescript/assets/images/icons/componentsIcon.svg
  lib/typescript/assets/images/icons/facebookMessengerCCLogo.svg
  lib/typescript/assets/images/icons/refreshIcon.svg
  lib/typescript/assets/images/icons/serviceUnhealthy.svg
  lib/typescript/assets/images/icons/twilioLogo.svg
  lib/typescript/assets/images/logo/airyLogo.svg
Labels: feature

#3000 [#1405] Added Message Types to Chatplugin
  .prettierignore
  docs/docs/api/introduction.md
  docs/docs/sources/chatplugin/messageExamples.md
  docs/sidebars.js
  docs/static/icons/package.svg
  docs/static/img/sources/chatplugin/AudioMessagePreview.png
  docs/static/img/sources/chatplugin/SuggestionResponseMessagePreview.png
  docs/static/img/sources/chatplugin/fileMessagePreview.png
  docs/static/img/sources/chatplugin/imageMessagePreview.png
  docs/static/img/sources/chatplugin/quickRepliesMessagePreview.png
  docs/static/img/sources/chatplugin/richTextMessagePreview.png
  docs/static/img/sources/chatplugin/textMessagePreview.png
  docs/static/img/sources/chatplugin/videoMessagePreview.png
Labels: docs

#3008 [#2974] add client config endpoint
  docs/docs/api/endpoints/client-config.md
  docs/docs/ui/contacts.md
  docs/docs/ui/introduction.md
  docs/docs/ui/tags.md
  docs/sidebars.js
  docs/static/icons/package.svg
Labels: docs

#3017 [#3014] Added navigation to Control-Center from Inbox
  frontend/ui/src/components/TopBar/index.module.scss
  frontend/ui/src/components/TopBar/index.tsx
Labels: feature

#3029 Deploy the control center
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/Chart.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/deployment.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/ingress.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/service.yaml
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/values.yaml
Labels: feature

#3034 [#3027] carousel template bug
  frontend/README.md
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.module.scss
  frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx
  lib/typescript/components/general/AudioClip/index.module.scss
  lib/typescript/components/general/Carousel/index.module.scss
  lib/typescript/components/general/Carousel/index.tsx
  lib/typescript/components/message/MessageInfo/index.module.scss
  lib/typescript/components/message/MessageInfo/index.tsx
  lib/typescript/components/message/MessageWrapper/MessageContainer/index.module.scss
  lib/typescript/components/message/MessageWrapper/MessageContainer/index.tsx
  lib/typescript/components/message/MessageWrapper/index.module.scss
  lib/typescript/components/message/MessageWrapper/index.tsx
  lib/typescript/render/providers/google/components/Suggestions/index.module.scss
  lib/typescript/render/providers/google/components/Suggestions/index.tsx
Labels: bug, inbox

#3047 [#3023] Return cluster version on client.config endpoint
  WORKSPACE
  backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java
  backend/api/admin/src/main/java/co/airy/core/api/config/payload/ClientConfigResponsePayload.java
  backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java
  docs/docs/api/endpoints/client-config.md
  lib/typescript/model/Config.ts
  tools/build/springboot.bzl
Labels: feature

#3049 [#3032] Redesigned connectors
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/pages/Channels/ChannelCard/index.module.scss
  frontend/control-center/src/pages/Channels/ChannelCard/index.tsx
  frontend/control-center/src/pages/Webhooks/index.module.scss
  frontend/control-center/src/pages/Webhooks/index.tsx
  frontend/control-center/src/routes/routes.ts
  lib/typescript/assets/images/icons/releaseNotesIcon.svg
  lib/typescript/assets/images/icons/webhooksIcon.svg
Labels: feature

#3048 New routing for frontend
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/start/BUILD
  frontend/start/favicon.ico
  frontend/start/index.html
  frontend/start/manifest.json
  frontend/start/nginx.conf
  frontend/ui/BUILD
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-ui/templates/ingress.yaml
Labels: feature

#3051 [#3016] Display version Inbox and Control-Center
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/Sidebar/index.module.scss
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/components/TopBar/index.tsx
  frontend/control-center/src/reducers/data/config/index.ts
  frontend/ui/src/components/TopBar/index.module.scss
  frontend/ui/src/components/TopBar/index.tsx
  frontend/ui/src/reducers/data/config/index.ts
  lib/typescript/model/Config.ts
Labels: feature

#3054 Bump Bazel to 5.1.1
  .bazelrc
  .bazelversion
  frontend/start/nginx.conf
Labels: chore

#3053 [#2941] Move start in the control-center app
  frontend/control-center/public/start.html
  frontend/start/BUILD
  frontend/start/favicon.ico
  frontend/start/manifest.json
  frontend/start/nginx.conf
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/ingress.yaml
Labels: fix

#3057 [#2886] Overwrite minikube driver
  cli/pkg/providers/minikube/minikube.go
  docs/docs/getting-started/installation/helm.md
  docs/docs/getting-started/installation/minikube.md
Labels: fix

#3056 [#3031] component status
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/pages/Components/ComponentsListItem/index.module.scss
  frontend/control-center/src/pages/Components/ComponentsListItem/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
  frontend/control-center/src/pages/Status/index.module.scss
  frontend/control-center/src/pages/Status/index.tsx
  frontend/control-center/src/reducers/data/config/index.ts
  frontend/control-center/src/services/format.ts
  frontend/control-center/src/services/hooks/index.ts
  frontend/control-center/src/services/index.ts
  lib/typescript/assets/images/icons/dialogflowLogo.svg
  lib/typescript/assets/images/icons/statusIcon.svg
  lib/typescript/assets/images/icons/zendeskLogo.svg
  lib/typescript/assets/scss/colors.scss
  lib/typescript/components/inputs/Toggle/index.tsx
  lib/typescript/components/inputs/Toggle/style.module.scss
  lib/typescript/httpclient/src/endpoints/getConfig.ts
  lib/typescript/model/Config.ts
  lib/typescript/model/Source.ts
Labels: feature

#3059 [#3058] components status follow up
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/components/TopBar/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemList.tsx
  frontend/control-center/src/pages/Catalog/index.module.scss
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Channels/ChannelCard/index.module.scss
  frontend/control-center/src/pages/Channels/ChannelCard/index.tsx
  frontend/control-center/src/pages/Channels/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss
  frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
  frontend/control-center/src/pages/Status/index.module.scss
  frontend/control-center/src/routes/routes.ts
  frontend/control-center/src/services/format.ts
  lib/typescript/assets/scss/fonts.scss
  lib/typescript/components/inputs/Toggle/index.tsx
  lib/typescript/components/inputs/Toggle/style.module.scss
  lib/typescript/model/Source.ts
Labels: fix

#3070 [#1297] Update filter in release scripts
  .github/workflows/main.yml
  scripts/push-helm-charts.sh
  scripts/push-images.sh
  tools/build/helm.bzl
Labels: fix

#3076 [#3075] Fix Styling in start page
  frontend/control-center/public/start.html
Labels: fix

#3080 [#3079] Fix start redirect
  infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/ingress.yaml
Labels: fix

#3094 [#3092] Adding name to webhooks
  backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListPayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookSubscribePayload.java
  backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookUpdatePayload.java
  backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
  backend/avro/webhook.avsc
  backend/webhook/consumer/src/test/java/co/airy/core/webhook/consumer/ConsumerTest.java
  backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
Labels: feature

#3111 [#3109] Make name optional webhook
  backend/avro/webhook.avsc
Labels: fix

#3114 [#3108] control center update
  docs/docs/ui/control-center/catalog.md
  docs/docs/ui/control-center/components.md
  docs/docs/ui/control-center/introduction.md
  docs/docs/ui/control-center/status.md
  docs/docs/ui/overview.md
  docs/sidebars.js
  docs/static/img/sources/google/googleConnect.png
  docs/static/img/sources/instagram/instagramConnect.png
  docs/static/img/sources/twilio/whatsAppConnect.png
  docs/static/img/ui/controlCenterCatalog.png
  docs/static/img/ui/controlCenterCatalogDemo.png
  docs/static/img/ui/controlCenterCatalogExample.png
  docs/static/img/ui/controlCenterComponents.png
  docs/static/img/ui/controlCenterConnectors.png
  docs/static/img/ui/controlCenterConnectorsDemo.png
  docs/static/img/ui/controlCenterStatus.png
  docs/static/img/ui/ui.png
Labels: docs

#3107 [#3073] show available conversation for same contact
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.module.scss
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
  infrastructure/helm-chart/BUILD
  infrastructure/helm-chart/charts/ingress-controller/BUILD
  infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/BUILD
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/BUILD
  infrastructure/helm-chart/charts/tools/charts/akhq/BUILD
  infrastructure/helm-chart/charts/tools/charts/kafka-connect/BUILD
  lib/typescript/components/general/ConnectorAvatar/index.module.scss
  lib/typescript/components/general/ConnectorAvatar/index.tsx
  lib/typescript/components/general/index.ts
Labels: feature
