Repository airyhq/airy, pull requests merged in 2022-11, with the labels that each got.

#3903 [#3886] fixed status page error
  frontend/control-center/src/pages/Status/index.tsx
Labels: fix

#3911 [#3909] rasa control center fix
  backend/components/ibm-watson-assistant/helm/templates/deployment.yaml
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3913 [#3907] fixed input disable
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx
  lib/typescript/translations/translations.ts
Labels: fix

#3914 [3901 & 3900] Feature/3901 create kafka topic for components events
  backend/components/installer/BUILD
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/CatalogHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/GitHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/HelmJobHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallationStatusComponentsHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java
  backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentStatus.java
  backend/components/installer/src/main/resources/application.properties
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallationStatusComponentsHandlerTest.java
  backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallerHandlerTest.java
  backend/components/installer/src/test/resources/test.properties
  backend/model/component/BUILD
  backend/model/component/src/main/java/co/airy/model/component/Component.java
  backend/model/component/src/main/java/co/airy/model/component/MetadataRepository.java
  infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml
  lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/ops/OpsApplicationComponents.java
Labels: feature

#3922 [#3878] Adding Loading indicators to control-center
  bazel.tsconfig.json
  frontend/control-center/BUILD
  frontend/control-center/src/App.tsx
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogSearchBar/FilterCatalogModal/FilterCatalogModal.module.scss
  frontend/control-center/src/pages/Catalog/index.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.module.scss
  frontend/control-center/src/pages/Connectors/InfoCard/index.module.scss
  frontend/control-center/src/pages/Connectors/index.module.scss
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/index.tsx
  frontend/control-center/src/pages/Webhooks/EmptyState/index.module.scss
  frontend/control-center/src/pages/Webhooks/EmptyState/index.tsx
  frontend/control-center/src/pages/Webhooks/index.tsx
  frontend/control-center/src/reducers/data/catalog/index.ts
  frontend/control-center/src/selectors/connectors.ts
  lib/typescript/assets/images/icons/amazonLexV2Logo.svg
  lib/typescript/components/BUILD
  lib/typescript/components/alerts/NotificationComponent/index.module.scss
  lib/typescript/components/loaders/AiryLoader/data.json
  lib/typescript/components/loaders/AiryLoader/index.module.scss
  lib/typescript/components/loaders/AiryLoader/index.tsx
  lib/typescript/components/loaders/InstallerLoader/index.module.scss
  lib/typescript/components/loaders/InstallerLoader/index.tsx
  lib/typescript/components/loaders/InstallerLoader/spinnerLoader.json
  lib/typescript/components/loaders/index.ts
  lib/typescript/components/tooltip/index.module.scss
  lib/typescript/components/tooltip/index.tsx
  lib/typescript/model/Components.ts
  lib/typescript/model/Connectors.ts
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
  package.json
  yarn.lock
Labels: feature

#3882 [#3764] Kafka 3.3.1 docker image and helm chart
  infrastructure/kafka/2.7.0/image/Dockerfile
  infrastructure/kafka/2.7.0/image/Makefile
  infrastructure/kafka/2.7.0/image/config/server.properties
  infrastructure/kafka/2.7.0/image/config/zookeeper.properties
  infrastructure/kafka/2.7.0/image/scripts/configure-kafka.sh
  infrastructure/kafka/2.7.0/image/scripts/configure-zookeeper.sh
  infrastructure/kafka/2.7.0/image/scripts/entrypoint.sh
  infrastructure/kafka/2.7.0/kafka/BUILD
  infrastructure/kafka/2.7.0/kafka/Chart.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/Chart.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/templates/_helpers.tpl
  infrastructure/kafka/2.7.0/kafka/charts/kafka/templates/headless-service.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/templates/prometheus.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/templates/service.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/templates/statefulset.yaml
  infrastructure/kafka/2.7.0/kafka/charts/kafka/values.yaml
  infrastructure/kafka/2.7.0/kafka/charts/schema-registry/Chart.yaml
  infrastructure/kafka/2.7.0/kafka/charts/schema-registry/templates/deployment.yaml
  infrastructure/kafka/2.7.0/kafka/charts/schema-registry/templates/service.yaml
  infrastructure/kafka/2.7.0/kafka/charts/schema-registry/values.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/Chart.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/templates/_helpers.tpl
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/templates/headless-service.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/templates/service.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/templates/statefulset.yaml
  infrastructure/kafka/2.7.0/kafka/charts/zookeeper/values.yaml
  infrastructure/kafka/2.7.0/kafka/templates/kafka-helper-scripts.yaml
  infrastructure/kafka/2.7.0/kafka/values.yaml
  infrastructure/kafka/3.3.1/helm/BUILD
  infrastructure/kafka/3.3.1/helm/Chart.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/Chart.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/_helpers.tpl
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/configmap.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/headless-service.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/prometheus.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/service.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/templates/statefulset.yaml
  infrastructure/kafka/3.3.1/helm/charts/kafka/values.yaml
  infrastructure/kafka/3.3.1/helm/charts/schema-registry/Chart.yaml
  infrastructure/kafka/3.3.1/helm/charts/schema-registry/templates/deployment.yaml
  infrastructure/kafka/3.3.1/helm/charts/schema-registry/templates/service.yaml
  infrastructure/kafka/3.3.1/helm/charts/schema-registry/values.yaml
  infrastructure/kafka/3.3.1/helm/templates/kafka-helper-scripts.yaml
  infrastructure/kafka/3.3.1/helm/values.yaml
  infrastructure/kafka/3.3.1/image/Dockerfile
  infrastructure/kafka/3.3.1/image/Makefile
  infrastructure/kafka/3.3.1/image/config/server.properties
  infrastructure/kafka/3.3.1/image/scripts/configure-kafka.sh
  infrastructure/kafka/3.3.1/image/scripts/entrypoint.sh
Labels: feature

#3932 [#3927] Added airy contacts to catalog
  frontend/control-center/src/components/Sidebar/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/services/getRouteForCard.ts
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3924 [#3923] Use auth-provider in GCP kubeconfig file
  infrastructure/terraform/install/uninstall.sh
  infrastructure/terraform/modules/gcp-gke/main.tf
  infrastructure/terraform/modules/gcp-gke/outputs.tf
Labels: fix

#3938 [#2456] Documentation update in quickstart - consume from Kafka
  docs/docs/getting-started/quickstart.md
  docs/static/img/getting-started/quickstart/messages_topic.gif
Labels: bug, docs

#3942 [#3941] add ingress rule for /conversations.mark-read
  backend/components/unread-counter/src/main/java/co/airy/core/unread_counter/UnreadCounterController.java
  infrastructure/helm-chart/templates/components/ingress.yaml
Labels: fix

#3944 [#3943] Fix of the gcp-gke terraform modules output file
  infrastructure/terraform/install/gcp-gke/outputs.tf
Labels: infrastructure

#3950 [#3949] Updated conversation.list docs
  docs/docs/api/endpoints/components.md
Labels: docs

#3958 [#3957] Disable Preemptible nodes in GCP
  infrastructure/terraform/modules/gcp-gke/main.tf
Labels: fix

#3961 [#3960] Updated kafka topic link
  docs/docs/concepts/kafka.md
Labels: docs

#3971 [#3969] Fixed health status icon
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
Labels: fix

#3972 [#3841] Add translations catalog components
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  lib/typescript/model/Components.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3975 [#3974] Update docs on Airy Core
  docs/docs/getting-started/components.md
  docs/docs/getting-started/introduction.md
  docs/docs/guides/contributing-to-airy.md
  docs/static/img/getting-started/introduction-dark.png
  docs/static/img/getting-started/introduction-light.png
Labels: docs
