Repository airyhq/airy, pull requests merged in 2022-12, with the labels that each got.

#3978 [#3974] Fix broken link in the docs
  docs/docs/connectors/sources/whatsapp-cloud.md
Labels: docs

#3981 [#3974] Fix pushing local images to Minikube
  docs/docs/guides/contributing-to-airy.md
Labels: fix

#3956 [#3890] abstract sources parser for connectors in backend
  backend/components/cognigy/BUILD
  backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/MessageHandler.java
  backend/components/ibm-watson-assistant/BUILD
  backend/components/ibm-watson-assistant/src/main/java/co/airy/core/ibm_watson_assistant_connector/MessageHandler.java
  backend/components/rasa/BUILD
  backend/components/rasa/src/main/java/co/airy/core/rasa_connector/MessageHandler.java
  lib/java/sources-parser/BUILD
  lib/java/sources-parser/src/main/java/co/airy/sources-parser/SourcesParser.java
Labels: feature

#3989 [#3988] Fix deprecated tf parameter
  infrastructure/helm-chart/charts/ingress-controller/templates/letsencrypt.yaml
  infrastructure/terraform/modules/core/main.tf
Labels: fix

#3990 [#3966] Update Catalog Images
  docs/static/img/ui/controlCenterCatalog.png
Labels: docs

#3996 [#3995] Add init container to the installer
  docs/docs/getting-started/installation/helm.md
  infrastructure/helm-chart/templates/components/api-components-installer/deployment.yaml
Labels: fix

#3998 [#3997] Fixed navigation chatplugin
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
Labels: fix

#3994 [#3475] Updated Status and Catalog docs
  docs/docs/ui/control-center/status.md
  docs/static/icons/checkmarkFilled.svg
  docs/static/icons/uncheckIconGray.svg
  docs/static/icons/uncheckIconRed.svg
  docs/static/icons/uncheckIconYellow.svg
Labels: docs

#3999 [#3995] Fix resources for installer
  infrastructure/helm-chart/templates/components/api-components-installer/deployment.yaml
Labels: fix

#4007 [#4006] Update oauth scopes for GCP
  infrastructure/terraform/modules/gcp-gke/main.tf
  infrastructure/terraform/modules/gcp-gke/variables.tf
Labels: fix
