Repository airyhq/airy, pull requests merged in 2022-09, with the labels that each got.

#3665 [#3664] Fixed connect button and fixed notification color
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/DialogflowConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Instagram/InstagramConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx
  frontend/control-center/src/pages/Connectors/Providers/Twilio/TwilioConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx
  frontend/control-center/src/pages/Connectors/RestartPopUp/index.module.scss
  lib/typescript/model/Components.ts
Labels: fix

#3663 [#3361] Fixed z-Index issue on customize page chatplugin
  lib/typescript/components/alerts/SettingsModal/style.module.scss
Labels: fix

#3670 [#3668] Added not healthy to connectors
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.module.scss
  frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/services/getComponentStatus.ts
  lib/typescript/assets/scss/colors.scss
Labels: feature

#3611 [#3403] Rasa Connector
  BUILD
  backend/connectors/rasa-connector/BUILD
  backend/connectors/rasa-connector/helm/BUILD
  backend/connectors/rasa-connector/helm/Chart.yaml
  backend/connectors/rasa-connector/helm/templates/configmap.yaml
  backend/connectors/rasa-connector/helm/templates/deployment.yaml
  backend/connectors/rasa-connector/helm/templates/service.yaml
  backend/connectors/rasa-connector/helm/values.yaml
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/MessageHandler.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/RasaClient.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/RasaClientConfig.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/RasaConnectorService.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/Stores.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/models/AiryAttachment.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/models/AiryPayload.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/models/AiryResponse.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/models/MessageSend.java
  backend/connectors/rasa-connector/src/main/java/co/airy/core/rasa_connector/models/MessageSendResponse.java
  backend/connectors/rasa-connector/src/main/resources/application.properties
  backend/connectors/rasa-connector/src/test/java/co/airy/core/rasa_connector/RasaConnectorServiceTest.java
  backend/connectors/rasa-connector/src/test/resources/test.properties
  lib/java/spring/async/BUILD
  lib/java/spring/async/src/main/java/co/airy/spring/async/AsyncExecutorConfig.java
  maven_install.json
  repositories.bzl
Labels: feature

#3674 [#3673] downgrade camelcase
  backend/components/rasa/helm/BUILD
  package.json
  yarn.lock
Labels: fix

#3705 [#3485] Add notify me catalog
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Catalog/NotifyMeModal/index.module.scss
  frontend/control-center/src/pages/Catalog/NotifyMeModal/index.tsx
  lib/typescript/assets/scss/colors.scss
  lib/typescript/components/alerts/NotificationComponent/index.tsx
  lib/typescript/components/cta/Button/index.tsx
  lib/typescript/components/cta/Button/style.module.scss
  lib/typescript/components/cta/SmartButton/index.module.scss
  lib/typescript/components/cta/SmartButton/index.tsx
  lib/typescript/components/inputs/Input/index.tsx
  lib/typescript/components/inputs/Input/style.module.scss
  lib/typescript/model/Connectors.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3707 [#3667] Added IBM and Amazon S3 to catalog
  frontend/control-center/src/components/ChannelAvatar/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  lib/typescript/assets/images/icons/amazons3Logo.svg
  lib/typescript/assets/images/icons/ibmWatsonAssistantLogo.svg
  lib/typescript/model/Source.ts
  lib/typescript/translations/translations.ts
Labels: feature

#3555 [#2757] Use Terraform for Minikube provider
  cli/pkg/cmd/create/create.go
  cli/pkg/cmd/status/BUILD
  cli/pkg/providers/aws/BUILD
  cli/pkg/providers/aws/aws.go
  cli/pkg/providers/minikube/BUILD
  cli/pkg/providers/minikube/minikube.go
  cli/pkg/providers/provider.go
  infrastructure/terraform/install/airy-core/outputs.tf
  infrastructure/terraform/install/minikube/main.tf
  infrastructure/terraform/install/minikube/outputs.tf
  infrastructure/terraform/install/minikube/state.tf
  infrastructure/terraform/modules/core/main.tf
  infrastructure/terraform/modules/core/outputs.tf
  infrastructure/terraform/modules/core/variables.tf
  infrastructure/terraform/modules/minikube/main.tf
  infrastructure/terraform/modules/minikube/outputs.tf
  infrastructure/terraform/modules/minikube/variables.tf
  lib/go/tools/BUILD
  lib/go/tools/tools.go
Labels: feature

#3712 [#3708] Sort status alphabetically
  frontend/control-center/src/pages/Status/index.tsx
  lib/typescript/model/Config.ts
Labels: feature

#3716 [#3469] Removed animation contacts and added installed check
  frontend/inbox/handles/index.ts
  frontend/inbox/src/actions/contacts/index.ts
  frontend/inbox/src/components/ContactDetails/index.tsx
  frontend/inbox/src/components/DialogCustomizable/index.module.scss
  frontend/inbox/src/components/Sidebar/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactInformation/index.module.scss
  frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx
  frontend/inbox/src/pages/Contacts/ContactListItem/index.module.scss
  frontend/inbox/src/pages/Contacts/index.module.scss
  frontend/inbox/src/pages/Contacts/index.tsx
  frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
  integration/ui/list_contacts_page.spec.ts
Labels: fix

#3729 [#3723] Sort catalog by installed, name, price
  frontend/control-center/src/pages/Catalog/index.tsx
Labels: fix

#3726 [#3725] Rendering of WhatsApp Cloud messages in the Conversation List Preview
  lib/typescript/render/SourceMessagePreview.tsx
Labels: feature

#3721 [#3700] support the rendering of whatsapp cloud messages
  frontend/inbox/src/pages/Inbox/MessageInput/index.tsx
  lib/typescript/assets/images/icons/productList.svg
  lib/typescript/assets/scss/colors.scss
  lib/typescript/render/components/CurrentLocation/index.module.scss
  lib/typescript/render/components/CurrentLocation/index.tsx
  lib/typescript/render/components/Image/index.tsx
  lib/typescript/render/components/Text/index.tsx
  lib/typescript/render/components/index.ts
  lib/typescript/render/outbound/facebook.ts
  lib/typescript/render/outbound/index.ts
  lib/typescript/render/outbound/whatsapp.ts
  lib/typescript/render/providers/meta/MetaModel.ts
  lib/typescript/render/providers/meta/MetaRender.tsx
  lib/typescript/render/providers/meta/components/ButtonTemplate/index.module.scss
  lib/typescript/render/providers/meta/components/ButtonTemplate/index.tsx
  lib/typescript/render/providers/meta/components/Buttons/index.module.scss
  lib/typescript/render/providers/meta/components/Buttons/index.tsx
  lib/typescript/render/providers/meta/components/DeletedMessage/index.module.scss
  lib/typescript/render/providers/meta/components/DeletedMessage/index.tsx
  lib/typescript/render/providers/meta/components/FallbackAttachment/index.module.scss
  lib/typescript/render/providers/meta/components/FallbackAttachment/index.tsx
  lib/typescript/render/providers/meta/components/GenericTemplate/index.module.scss
  lib/typescript/render/providers/meta/components/GenericTemplate/index.tsx
  lib/typescript/render/providers/meta/components/InstagramShare/index.module.scss
  lib/typescript/render/providers/meta/components/InstagramShare/index.tsx
  lib/typescript/render/providers/meta/components/InstagramStoryMention/index.module.scss
  lib/typescript/render/providers/meta/components/InstagramStoryMention/index.tsx
  lib/typescript/render/providers/meta/components/InstagramStoryReplies/index.module.scss
  lib/typescript/render/providers/meta/components/InstagramStoryReplies/index.tsx
  lib/typescript/render/providers/meta/components/MediaTemplate/index.module.scss
  lib/typescript/render/providers/meta/components/MediaTemplate/index.tsx
  lib/typescript/render/providers/meta/components/QuickReplies/index.module.scss
  lib/typescript/render/providers/meta/components/QuickReplies/index.tsx
  lib/typescript/render/providers/meta/components/WhatsAppContacts/index.module.scss
  lib/typescript/render/providers/meta/components/WhatsAppContacts/index.tsx
  lib/typescript/render/providers/meta/components/WhatsAppInteractive/index.module.scss
  lib/typescript/render/providers/meta/components/WhatsAppInteractive/index.tsx
  lib/typescript/render/providers/meta/components/WhatsAppMedia/index.module.scss
  lib/typescript/render/providers/meta/components/WhatsAppMedia/index.tsx
  lib/typescript/render/providers/meta/components/WhatsAppTemplate/index.module.scss
  lib/typescript/render/providers/meta/components/WhatsAppTemplate/index.tsx
  lib/typescript/render/providers/meta/components/index.ts
  lib/typescript/render/providers/twilio/TwilioRender.tsx
  lib/typescript/render/providers/twilio/components/CurrentLocation/index.tsx
  lib/typescript/render/renderProviders.ts
  lib/typescript/render/services/mediaAttachments.ts
Labels: feature

#3733 [#2754] Improve installation and release docs
  docs/docs/concepts/release-process.md
  docs/docs/getting-started/installation/aws.md
  docs/docs/getting-started/installation/minikube.md
Labels: docs

#3717 Infrastructure/2556 google cloud platform terraform module
  infrastructure/terraform/install/gcp-gke/main.tf
  infrastructure/terraform/install/gcp-gke/variables.tf
  infrastructure/terraform/modules/gcp-gke/main.tf
  infrastructure/terraform/modules/gcp-gke/outputs.tf
  infrastructure/terraform/modules/gcp-gke/variables.tf
Labels: infrastructure

#3759 [#3758] Channels filter not appearing on the Inbox UI
  frontend/inbox/src/pages/Inbox/QuickFilter/Popup.tsx
  frontend/inbox/src/reducers/data/channels/index.ts
Labels: fix

#3757 [#3616] Validate incoming facebook webhook signatures
  backend/components/facebook/connector/BUILD
  backend/components/facebook/connector/src/main/java/co/airy/core/sources/facebook/WebhookController.java
  backend/components/facebook/connector/src/test/java/co/airy/core/sources/facebook/WebhookControllerTest.java
  backend/components/whatsapp/connector/BUILD
  backend/components/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/WebhookController.java
  backend/components/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/WebhookControllerTest.java
  lib/java/crypto/src/main/java/co/airy/crypto/Signature.java
Labels: fix

#3777 fix routing
  frontend/control-center/public/start.html
Labels: fix

#3774 [#3744] Added possibility to configure channel connectors
  frontend/control-center/src/App.tsx
  frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
  frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx
  frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.module.scss
  frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.module.scss
  frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss
  frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx
  frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/DialogflowConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Dialogflow/index.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Instagram/InstagramConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx
  frontend/control-center/src/pages/Connectors/Providers/Salesforce/index.module.scss
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappBusinessCloudConnect.module.scss
  frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappBusinessCloudConnect.tsx
  frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx
  frontend/control-center/src/pages/Connectors/Providers/Zendesk/index.module.scss
  frontend/control-center/src/pages/Connectors/index.tsx
  frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
  frontend/control-center/src/services/getComponentStatus.ts
  frontend/control-center/src/services/getRouteForCard.ts
  lib/typescript/components/tooltip/index.tsx
  lib/typescript/translations/translations.ts
Labels: feature
