Repository airyhq/airy, pull requests merged in 2023-04, with the labels that each got.

#4069 [#4068] Fix Docs build
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/ButtonBox/index.js
  docs/src/components/Image/index.js
  docs/src/components/SuccessBox/index.js
  docs/src/components/SuccessBox/styles.module.css
  docs/src/components/TLDR/index.js
  docs/yarn.lock
  yarn.lock
Labels: docs

#4077 [#4076] Upgrade k8s registry
  infrastructure/helm-chart/charts/ingress-controller/templates/ingress-controller.yaml
Labels: fix

#4087 [#4086] Fix link to contributing guide
  README.md
Labels: bug, docs

#4088 [#4057] Fix env vars for schema-registry
  infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/schema-registry/templates/deployment.yaml
Labels: fix
